import {useState} from 'react'
import {shiftPracticeDate} from '../household/operatingPractices.js'
import {ADULTS,defaultPreferences,escalationReadiness} from './governanceModel.js'

const FACTORS=[['urgency','Urgency'],['impact','Impact'],['recurrence','Recurrence'],['crossPillarEffect','Cross-pillar effect']]
export default function GovernanceControls({model,member,date,review,disabled}){
 const [policy,setPolicy]=useState(model.configuration?{...model.configuration,expiresOn:model.configuration.expiresOn||model.configuration.reviewDate}:{effectiveDate:date,reviewDate:shiftPracticeDate(date,28),expiresOn:shiftPracticeDate(date,90),supportMembers:[],decisionMaker:'',promptMinutes:240,threshold:64,recurrenceWindow:28,workerEnabled:false})
 const [prefs,setPrefs]=useState(model.preferences||defaultPreferences())
 const [recovery,setRecovery]=useState({title:'Temporary household recovery',reason:'',startsOn:date,endsOn:date,essential:'',routineIds:[]})
 const send=(type,targetId,payload,description,extra={})=>review({type,targetId,targetDate:date,payload,description},extra)
 const policyFields=()=>Object.fromEntries(['effectiveDate','reviewDate','expiresOn','supportMembers','decisionMaker','promptMinutes','threshold','recurrenceWindow','workerEnabled'].map(key=>[key,policy[key]]))
 return <div className="governance-controls">
  <details><summary>GOV-001 approval and authority controls</summary>
   <p>{model.policyActive?`Ratified by ${model.configuration.approvedBy} · revision ${model.configuration.revision}`:'Not yet ratified for current use. Assistance previews remain available.'}</p>
   {model.configuration?.reviewDate<=date&&model.policyActive&&<p>Policy review is due. Current authorization ends {model.configuration.expiresOn||model.configuration.reviewDate}; review does not silently extend it.</p>}<p>L0 observes; L1 prompts in Brevity; L2 prepares; L3 requests accepted support; L4 uses existing reviewed actions; L5 shares decision-ready exceptions; L6 retains explicit restrictions. No level expands existing account permissions.</p>
   {model.configuration&&<p>Effective {model.configuration.effectiveDate} through {model.configuration.expiresOn||model.configuration.reviewDate}. Review reminder: {model.configuration.reviewDate}. Decision-maker: {model.configuration.decisionMaker}. Approved support: {model.configuration.supportMembers.join(', ')||'None'}. In-app follow-up: {model.configuration.workerEnabled?'Enabled':'Disabled'}.</p>}
   {model.isAdmin&&<form onSubmit={e=>{e.preventDefault();send('orchestration.policy.update','GOV-001',policyFields(),'Review GOV-001 configuration. Changes invalidate prior ratification; no permissions are expanded.')}}>
    <label>Effective date<input type="date" value={policy.effectiveDate} onChange={e=>setPolicy({...policy,effectiveDate:e.target.value})} required/></label><label>Policy review reminder<input type="date" min={policy.effectiveDate} value={policy.reviewDate} onChange={e=>setPolicy({...policy,reviewDate:e.target.value})} required/></label><label>Authorization ends (inclusive)<input type="date" min={policy.reviewDate} value={policy.expiresOn} onChange={e=>setPolicy({...policy,expiresOn:e.target.value})} required/></label>
    <label>Designated decision-maker<select value={policy.decisionMaker} onChange={e=>setPolicy({...policy,decisionMaker:e.target.value})} required><option value="">Choose explicitly</option>{ADULTS.map(name=><option key={name}>{name}</option>)}</select></label>
    <fieldset><legend>Approved support candidates — each request still requires acceptance</legend>{ADULTS.map(name=><label key={name}><input type="checkbox" checked={policy.supportMembers.includes(name)} onChange={e=>setPolicy({...policy,supportMembers:e.target.checked?[...policy.supportMembers,name]:policy.supportMembers.filter(m=>m!==name)})}/>{name}</label>)}</fieldset>
    <label>Minimum minutes between in-app follow-ups<input type="number" min="60" max="1440" value={policy.promptMinutes} onChange={e=>setPolicy({...policy,promptMinutes:Number(e.target.value)})}/></label><label>Reviewed consequence threshold (1–256)<input type="number" min="1" max="256" value={policy.threshold} onChange={e=>setPolicy({...policy,threshold:Number(e.target.value)})}/></label><label>Observation window in days<input type="number" min="7" max="90" value={policy.recurrenceWindow} onChange={e=>setPolicy({...policy,recurrenceWindow:Number(e.target.value)})}/></label>
    <label><input type="checkbox" checked={policy.workerEnabled} onChange={e=>setPolicy({...policy,workerEnabled:e.target.checked})}/>Allow scheduled in-app follow-up within member prompting windows, including evidence-qualified decision packets to the designated leader</label><p>Review this policy before its authorization end date. Expiry stops coordination; reviewed Recovery exit remains available.</p><p>No email, text message, purchase, payment, permission change or automatic task reassignment is authorized.</p><button disabled={disabled}>Review policy configuration</button>
   </form>}
   {member==='Lorenzo'&&model.configuration&&!model.policyActive&&<button disabled={disabled} onClick={()=>send('orchestration.policy.approve','GOV-001',{revision:model.configuration.revision},`Ratify GOV-001 configuration revision ${model.configuration.revision}, including its support candidates, decision-maker and in-app follow-up limits.`)}>Review GOV-001 ratification</button>}
  </details>
  <details><summary>My assistance preferences and learning consent</summary><form onSubmit={e=>{e.preventDefault();send('orchestration.preferences.update',member,Object.fromEntries(Object.keys(defaultPreferences()).map(k=>[k,prefs[k]])),'Review my assistance preferences and adaptive observation consent.',{expectedVersion:model.preferenceVersion})}}>
   <label>Preparation style<select value={prefs.style} onChange={e=>setPrefs({...prefs,style:e.target.value})}><option value="checklist">Checklist</option><option value="options">Options to choose from</option><option value="prepared-draft">Prepared draft to review</option></select></label>
   <label>Prompting starts<input type="time" value={prefs.startTime} onChange={e=>setPrefs({...prefs,startTime:e.target.value})}/></label><label>Prompting ends<input type="time" value={prefs.endTime} onChange={e=>setPrefs({...prefs,endTime:e.target.value})}/></label>
   <label>Available household minutes per day (optional)<input type="number" min="0" max="1440" value={prefs.capacityMinutes??''} onChange={e=>setPrefs({...prefs,capacityMinutes:e.target.value===''?null:Number(e.target.value)})}/></label>
   <label>Support strategy that helps me<textarea rows="2" maxLength="500" value={prefs.supportStrategy} onChange={e=>setPrefs({...prefs,supportStrategy:e.target.value})}/></label>
   <label><input type="checkbox" checked={prefs.learning} onChange={e=>setPrefs({...prefs,learning:e.target.checked})}/>Use my reviewed workflow observations to improve assistance. I can turn this off or correct my preferences.</label>
   <label>Learning window (days)<input type="number" min="7" max="90" value={prefs.retentionDays} onChange={e=>setPrefs({...prefs,retentionDays:Number(e.target.value)})}/></label>
   <p>Known scheduled time: {model.capacity?.scheduledMinutes??0} minutes. Stated daily capacity: {model.capacity?.availableMinutes??"Not provided"}{model.capacity?.overCapacity?" — scheduled time exceeds stated capacity; review priorities.":""}. External commitments may add time.</p><p>Turning learning off stops derived use. Scheduled retention cleanup continues while follow-up is disabled or paused. Derived observations use the responsibility date and are excluded immediately from learning when consent is off. Immutable Action Mode receipts remain in the existing audit history, including administrator access.</p><button disabled={disabled||!Number.isInteger(model.preferenceVersion)}>Review my preferences</button>
  </form><p>{model.adaptation?.notice} {model.adaptation?.evidence}</p>{model.adaptation?.enabled&&<><p>{model.adaptation.acknowledgements} acknowledgements · {model.adaptation.retainedPreparations} retained preparations across {model.adaptation.observedCases} visible owned cases. This is not a personal score.</p><p>Observed initiation: {model.adaptation.observedInitiation?`${model.adaptation.observedInitiation.initiated} of ${model.adaptation.observedInitiation.observed} known states`:"Not enough evidence"}. Completion: {model.adaptation.observedCompletion?`${model.adaptation.observedCompletion.completed} of ${model.adaptation.observedCompletion.observed} known states`:"Not enough evidence"}. Typical acknowledgement time: {model.adaptation.responseTime?`${Math.round(model.adaptation.responseTime.medianMinutes)} minutes (${model.adaptation.responseTime.samples} observations)`:"Unknown"}.</p><p>Prompting observations compare your own workflows and do not prove that a method caused a response.</p><ul>{model.adaptation.promptingMethods?.filter(method=>method.responses>0).map(method=><li key={method.style}>{method.style}: {method.responses} recorded responses, average {Math.round(method.averageMinutes)} minutes.</li>)}</ul><ul>{model.adaptation.strategies.map((s,i)=><li key={i}>{s.note}</li>)}</ul></>}</details>
  <details><summary>Household System Health and cross-pillar conflicts</summary><p>{model.systemHealth.unresolvedDependencies} dependencies not confirmed resolved (including unavailable linked sources) · {model.systemHealth.pendingSupport} support requests awaiting an answer · {model.systemHealth.acceptedSupport} accepted · {model.systemHealth.confirmedConflicts} Schedule conflicts</p><p>{model.systemHealth.closedAssistanceOutstanding??0} closed assistance cases still have an unconfirmed source outcome. {model.systemHealth.recurringExceptions??0} recorded exceptions in the policy window · {model.systemHealth.coverageStability??0} open cases with accepted support or established coverage · {model.systemHealth.recoveryPlans??0} active recovery plans.</p><p>Current orchestration covers dated assignments across the Seven Pillars, operating practices, meal readiness, maintenance chores and Shared Health. Shared Health needs and appointments within seven days now appear as member/admin-scoped cases. Health details are not routed to support or leadership through orchestration. Confirmed overlaps below use named Schedule attendance. External appointments and unassigned travel may add constraints; this is not a complete calendar availability check.</p>
   <ul>{(model.workload||[]).map(row=><li key={row.member}>{row.member}: {row.count} visible open responsibilities. Counts do not establish effort or capacity.</li>)}</ul>
   {Boolean(model.healthTrends?.length)&&<table><caption>Observed system conditions by day</caption><thead><tr><th>Date</th><th>Open</th><th>Unknown</th><th>Blocked</th><th>Conflicts</th></tr></thead><tbody>{model.healthTrends.slice(-7).map(row=><tr key={row.date}><td>{row.date}</td><td>{row.open}</td><td>{row.unknown}</td><td>{row.blocked}</td><td>{row.conflicts}</td></tr>)}</tbody></table>}
   {(model.conflicts||[]).map(conflict=><article key={conflict.id}><h4>{conflict.member}: {conflict.left.title} / {conflict.right.title}</h4><p>{conflict.start}–{conflict.end} · {conflict.crossPillar?'Cross-pillar conflict':'Competing responsibilities'}</p><ul>{conflict.options.map(option=><li key={option}>{option}</li>)}</ul></article>)}
  </details>
  <details><summary>Recovery Mode</summary><p>Protect essential outcomes during illness, travel, work demands or disruption. Activation applies reviewed dated routine deferrals; it does not change standing owners. Deferred occurrences expire naturally. Exiting reviews restoration of unchanged remaining occurrences. Newer edits and past occurrences are preserved; review the Schedule for any occurrences excluded from restoration.</p>
   {model.isAdmin&&<form onSubmit={e=>{e.preventDefault();send('orchestration.recovery.update',`recovery-${date}-${crypto.randomUUID()}`,{intent:'propose',...recovery,scheduleVersion:model.sourceVersions['shared:brevity_household_schedule_v1']},'Prepare temporary Recovery Mode with explicit essential outcomes and dated routine deferrals.')}}>
    <label>Recovery title<input value={recovery.title} onChange={e=>setRecovery({...recovery,title:e.target.value})} required/></label><label>Capacity change and reason<textarea maxLength="1000" value={recovery.reason} onChange={e=>setRecovery({...recovery,reason:e.target.value})} required/></label><label>Essential outcomes and coverage to protect<textarea maxLength="1000" value={recovery.essential} onChange={e=>setRecovery({...recovery,essential:e.target.value})} required/></label>
    <label>Starts<input type="date" value={recovery.startsOn} onChange={e=>setRecovery({...recovery,startsOn:e.target.value})} required/></label><label>Ends (within seven days)<input type="date" value={recovery.endsOn} onChange={e=>setRecovery({...recovery,endsOn:e.target.value})} required/></label>
    <fieldset><legend>Optional routines to defer temporarily (up to two)</legend>{(model.routines||[]).filter(r=>r.enabled).map(r=><label key={r.id}><input type="checkbox" checked={recovery.routineIds.includes(r.id)} onChange={e=>setRecovery({...recovery,routineIds:e.target.checked?[...recovery.routineIds,r.id]:recovery.routineIds.filter(id=>id!==r.id)})}/>{r.title} · {r.owner}</label>)}</fieldset><button disabled={disabled||!model.policyActive}>Review recovery proposal</button>
   </form>}
   {(model.recovery||[]).map(r=><article key={r.id}><h4>{r.title}</h4><p>{r.startsOn}–{r.endsOn} · {r.displayStatus}</p><p>{r.essential}</p>{r.status==='active'&&<p>{r.exitOperations.length} remaining unchanged occurrences can be restored. Other occurrences will be preserved.</p>}<ul>{r.operations.map((op,i)=><li key={i}>{op.description}</li>)}</ul>{model.isAdmin&&r.status==='proposed'&&<button disabled={disabled||!model.policyActive} onClick={()=>send('orchestration.recovery.update',r.id,{intent:'activate'},`Activate ${r.title} with its exact dated changes.`,{operations:r.operations,expectedVersions:{'shared:brevity_orchestration_v1':model.version,'shared:brevity_household_schedule_v1':r.scheduleVersion}})}>Review recovery activation</button>}{model.isAdmin&&r.status==='active'&&<button disabled={disabled} onClick={()=>send('orchestration.recovery.update',r.id,{intent:'end'},`End ${r.title} and restore its remaining dated routines.`,{operations:r.exitOperations,expectedVersions:{'shared:brevity_orchestration_v1':model.version,'shared:brevity_household_schedule_v1':model.sourceVersions['shared:brevity_household_schedule_v1']}})}>Review recovery exit</button>}</article>)}
  </details>
 </div>
}
export function CoordinationControls({item,model,member,review,disabled}){
 const [recipient,setRecipient]=useState(''),[note,setNote]=useState(''),[dependencyId,setDependency]=useState('')
 const [factors,setFactors]=useState(Object.fromEntries(FACTORS.map(([key])=>[key,{value:1,evidence:''}])))
 const owns=model.isAdmin||item.owners.includes(member)||item.coveredBy===member
 const closed=item.resolved||['completed','verified'].includes(item.state),readiness=escalationReadiness(item,model.configuration)
 const send=(event,extra={})=>review({type:'orchestration.coordination.update',targetId:item.id,targetDate:item.date,payload:{event,note,sourceVersions:item.sourceVersions||model.sourceVersions,...extra},description:`Review ${event} for ${item.title}. Ownership remains with the recorded owner.`})
 return <details><summary>Coordinate support, consequences and decisions</summary><p>{model.policyActive?'GOV-001 is active. Every change below still requires Action Mode.':'Ratify GOV-001 before coordinating. No support request or escalation has been sent.'}</p>
  <p>Resolve assistance and an exception decision close this assistance case and stop its prompts. They do not complete or verify the source responsibility. Use Open source workflow to record the actual outcome; reopen assistance if help is still needed.</p>{item.kind==='care'&&<p>Health assistance is visible only to the member and existing administrators. Support sharing and escalation are unavailable here.</p>}<label>Shared coordination reason or observed strategy<textarea maxLength="1000" value={note} onChange={e=>setNote(e.target.value)} rows="3"/></label>
  {owns&&!closed&&item.kind!=='care'&&<><label>Approved support candidate<select value={recipient} onChange={e=>setRecipient(e.target.value)}><option value="">Choose a person</option>{(model.configuration?.supportMembers||[]).filter(m=>!item.owners.includes(m)).map(m=><option key={m}>{m}</option>)}</select></label><button disabled={disabled||!model.policyActive||!recipient} onClick={()=>send('request-support',{recipient})}>Review support request</button></>}
  {item.requests?.map(request=><div key={request.id}><p>{request.recipient}: {request.response}</p>{owns&&!closed&&!['decline-support','withdraw-support'].includes(request.response)&&<button disabled={disabled||!model.policyActive||!note.trim()} onClick={()=>send('withdraw-support',{requestId:request.id})}>Review withdraw support request</button>}{request.recipient===member&&request.response==='pending'&&<><button disabled={disabled||!model.policyActive} onClick={()=>send('accept-support',{requestId:request.id})}>Review accept support</button><button disabled={disabled||!model.policyActive} onClick={()=>send('decline-support',{requestId:request.id})}>Review decline support</button></>}</div>)}
  {owns&&!closed&&<><fieldset><legend>Consequence assessment — evidence is required for every factor</legend><p>Score = urgency × impact × recurrence × cross-pillar effect. For urgency: 1 flexible, 2 approaching, 3 near deadline, 4 immediate consequence. Impact: 1 minor, 2 limited disruption, 3 substantial disruption, 4 severe. Recurrence: 1 isolated, 2 repeated, 3 frequent, 4 persistent despite assistance. Cross-pillar effect: 1 contained, 2 another outcome affected, 3 several outcomes, 4 household-wide. Missing evidence remains unknown.</p>{FACTORS.map(([key,label])=><div key={key}><label>{label}<select value={factors[key].value} onChange={e=>setFactors({...factors,[key]:{...factors[key],value:Number(e.target.value)}})}>{[1,2,3,4].map(n=><option key={n} value={n}>{n}</option>)}</select></label><label>{label} evidence<input value={factors[key].evidence} maxLength="500" onChange={e=>setFactors({...factors,[key]:{...factors[key],evidence:e.target.value}})}/></label></div>)}</fieldset><button disabled={disabled||!model.policyActive} onClick={()=>send('assess',{factors})}>Review consequence assessment</button>
   <label>Dependency<select value={dependencyId} onChange={e=>setDependency(e.target.value)}><option value="">Choose an exact responsibility</option>{model.cases.filter(c=>c.id!==item.id&&c.kind!=='care').map(c=><option key={c.id} value={c.id}>{c.title}</option>)}</select></label><button disabled={disabled||!model.policyActive||!dependencyId||item.kind==='care'} onClick={()=>send('dependency',{dependencyId})}>Review dependency</button>
   <p>{readiness.reason}</p><button disabled={disabled||!model.policyActive||!note.trim()} onClick={()=>send('owner-intervention')}>Review owner intervention</button><button disabled={disabled||!model.policyActive||!note.trim()} onClick={()=>send('support-exhausted')}>Review support and coverage outcome</button><button disabled={disabled||!model.policyActive||!readiness.allowed||!note.trim()||item.kind==='care'} onClick={()=>send('escalate')}>Review leadership exception</button><button disabled={disabled||!model.policyActive||!note.trim()} onClick={()=>send('resolve')}>Review resolve assistance</button></>}
   {owns&&<><button disabled={disabled||!model.policyActive||!note.trim()} onClick={()=>send('learn')}>Review what helped</button>{item.resolved&&!['completed','verified'].includes(item.state)&&<button disabled={disabled||!model.policyActive||!note.trim()} onClick={()=>send('reopen')}>Review reopen assistance</button>}{item.dependencies.map(dependency=><button key={dependency.id} disabled={disabled||!model.policyActive} onClick={()=>send('remove-dependency',{dependencyId:dependency.id})}>Review remove dependency: {dependency.title}</button>)}</>}
   {model.configuration?.decisionMaker===member&&(item.automaticException||item.events.some(e=>e.event==='escalate'&&e.recipient===member))&&<button disabled={disabled||!model.policyActive||!note.trim()} onClick={()=>send('decision')}>Review decision and close assistance</button>}
 </details>
}
