import './ModuleWorkspace.css'
import {useEffect,useState} from 'react'
import {requestAssistantConversation} from '../assistant/actionEvents.js'
export default function ModuleWorkspace({module,currentMember,revision}){
 const [state,setState]=useState({loading:true,entries:[]})
 useEffect(()=>{let active=true;setState({loading:true,entries:[]});fetch('/.netlify/functions/brevity-activity',{credentials:'include'}).then(async response=>{const data=await response.json();if(!response.ok)throw Error(data.error);if(active)setState({...data,loading:false})}).catch(error=>{if(active)setState({entries:[],error:error.message})});return()=>{active=false}},[module.id,currentMember,revision])
 const entries=state.entries.filter(entry=>entry.moduleId===module.id)
 return <section className="brevity-module-workspace"><p>Household module · {currentMember}</p><h1>{module.label}</h1><p>{module.description||'Capture notes and review next steps through Brevity.'}</p><button onClick={()=>requestAssistantConversation(`Help me add a note to my ${module.label} module. Ask what I want to record, then let me review it before saving.`)}>Talk to Brevity</button><p>Saved notes from your last seven days. Household records and permissions remain separate.</p>{state.loading&&<p>Loading notes…</p>}{state.error&&<p role="alert">{state.error}</p>}{state.unavailableDates?.length>0&&<p role="alert">Some dates could not be loaded.</p>}{!state.loading&&!state.error&&!entries.length&&<p>No notes are recorded in the available dates.</p>}{entries.map(entry=><article key={entry.id}><small>{entry.date}</small><h2>{entry.title}</h2><p>{entry.notes}</p><button onClick={()=>requestAssistantConversation(`Help me correct my saved module note “${entry.title}” from ${entry.date}. Find the saved activity and ask what should change.`)}>Correct with Brevity</button></article>)}</section>
}
