import test from'node:test'
import assert from'node:assert/strict'
import{buildAssistantContext,sanitizeForAssistant,selectRelevantTransactions,summarizeTransactions}from'./assistantContext.js'
import{PILLAR_ANALYSIS_SCHEMA_VERSION}from'../household/pillarAnalysisCache.js'
function storage(records={}){const keys=Object.keys(records);return{length:keys.length,key:index=>keys[index],getItem:key=>key in records?JSON.stringify(records[key]):null}}
test('summarizes income, expenses, transfers and reporting groups',()=>{const result=summarizeTransactions([{date:'2026-08-01',amount:-1000,category:'Income',name:'Payroll'},{date:'2026-08-02',amount:250,category:'Groceries',name:'Market'},{date:'2026-08-03',amount:100,category:'TRANSFER_OUT',name:'Savings transfer'}]);assert.equal(result.income,1000);assert.equal(result.expenses,250);assert.equal(result.transfers,100);assert.equal(result.net,750);assert.equal(result.byCategory[0].name,'Income')})
test('keeps refunds, merchant credits, transfers, and pending payroll out of realized income',()=>{const result=summarizeTransactions([{date:'2026-08-01',amount:-1000,category:'Income',name:'Payroll'},{date:'2026-08-02',amount:-45,category:'General Merchandise',name:'Purchase refund'},{date:'2026-08-03',amount:-15,category:'General Merchandise',name:'Cash back reward'},{date:'2026-08-04',amount:-500,category:'TRANSFER_IN',name:'Savings transfer'},{date:'2026-08-05',amount:-800,category:'Income',name:'Pending payroll',pending:true}]);assert.equal(result.income,1000);assert.equal(result.otherInflows,60);assert.equal(result.pendingInflows,800);assert.equal(result.inflows,1860);assert.equal(result.transfers,500);assert.equal(result.net,1860)})
test('surfaces older query-relevant transactions alongside recent activity',()=>{const rows=Array.from({length:140},(_,index)=>({id:`r${index}`,date:`2026-08-${String((index%28)+1).padStart(2,'0')}`,name:'Recent merchant',amount:10}));rows.push({id:'older-match',date:'2025-01-02',name:'Phoenix Health Payroll',category:'Income',amount:-500});assert.ok(selectRelevantTransactions(rows,'Analyze Phoenix Health income').some(row=>row.id==='older-match'))})
test('removes secrets and large encoded values',()=>{const cleaned=sanitizeForAssistant({access_token:'nope',nested:{password:'nope',safe:'yes'},image:'A'.repeat(500)});assert.equal(cleaned.access_token,undefined);assert.equal(cleaned.nested.password,undefined);assert.equal(cleaned.nested.safe,'yes');assert.equal(cleaned.image,'[large value omitted]')})
test('builds signed member and page-aware bounded context',()=>{const actuals=Array.from({length:400},(_,index)=>({id:index,date:'2026-08-01',name:'Example',amount:1}));const value=buildAssistantContext({storage:storage({plaid_actuals_cache:actuals,homehq_items_v1:[{title:'Roof'}],brevity_daily_plans_v1:{stale:true}}),member:'Larry',activeView:'dashboard',activePillar:'finance',pageLabel:'Finance Dashboard',query:'cash flow',now:new Date('2026-08-22T12:00:00Z')});assert.equal(value.signedInMember,'Larry');assert.equal(value.currentPage.label,'Finance Dashboard');assert.equal(value.finance.transactionSummary.count,400);assert.ok(value.finance.relevantTransactions.length<=250);assert.equal(value.projects[0].title,'Roof');assert.equal(value.dailyPlans,undefined)})
test('obsolete manual balance overrides never enter Assistant financial context',()=>{const value=buildAssistantContext({storage:storage({lslj_finance_v9:{accounts:[{id:'operating',balance:1200}]},lslj_bal_overrides_v1:{'2026-09-07':999999}}),member:'Larry',activeView:'dashboard',activePillar:'finance',pageLabel:'Finance Dashboard',query:'balance',now:new Date('2026-09-07T12:00:00Z')});assert.equal(value.finance.plan.accounts[0].balance,1200);assert.equal('balanceOverrides' in value.finance,false);assert.equal(JSON.stringify(value).includes('999999'),false)})
test('assistant snapshot reads only the signed member current-schema analyses for the household date',()=>{const larry={schemaVersion:PILLAR_ANALYSIS_SCHEMA_VERSION,member:'Larry',pillar:'finance',analysis:{headline:'Larry truth'}},lorenzo={...larry,member:'Lorenzo',analysis:{headline:'Lorenzo truth'}};const prefix=`brevity_pillar_analysis_v${PILLAR_ANALYSIS_SCHEMA_VERSION}_2026-09-06_finance`;const records={[`${prefix}_larry`]:larry,[`${prefix}_lorenzo`]:lorenzo,'brevity_pillar_analysis_v1_2026-09-06_finance':{analysis:{headline:'Stale'}}};const larryValue=buildAssistantContext({storage:storage(records),member:'Larry',activeView:'dashboard',activePillar:'finance',pageLabel:'Finance Dashboard',query:'today',now:new Date('2026-09-07T02:30:00.000Z')});const lorenzoValue=buildAssistantContext({storage:storage(records),member:'Lorenzo',activeView:'dashboard',activePillar:'finance',pageLabel:'Finance Dashboard',query:'today',now:new Date('2026-09-07T02:30:00.000Z')});assert.equal(larryValue.todayPillarAnalyses.finance.analysis.headline,'Larry truth');assert.equal(lorenzoValue.todayPillarAnalyses.finance.analysis.headline,'Lorenzo truth')})
