const ELEVENLABS_WORKER='https://bold-lab-61d5.lls3s.workers.dev'
export async function askBrevityAssistant({messages,conversationVersion,image,member,activeView,activePillar,pageLabel,storage=localStorage}){const {buildAssistantContext}=await import('./assistantContext.js');const latest=messages.at(-1)?.content||'';const context=buildAssistantContext({storage,member,activeView,activePillar,pageLabel,query:latest});let response=await fetch('/.netlify/functions/brevity-assistant',{method:'POST',credentials:'include',headers:{'content-type':'application/json'},body:JSON.stringify({messages:messages.slice(-16),conversationVersion,...(image?{image}:{}),page:{activeView,activePillar,pageLabel},context})});let payload=await response.json().catch(()=>({}));if(!response.ok)throw new Error(payload.error||`Brevity Assistant request failed (${response.status}).`);if(response.status===202){const jobId=payload.jobId;if(!/^[0-9a-f-]{36}$/.test(jobId||''))throw new Error('Brevity Assistant returned an invalid job.');for(let attempt=0;attempt<144;attempt+=1){await new Promise(resolve=>setTimeout(resolve,5000));response=await fetch(`/.netlify/functions/brevity-assistant?jobId=${encodeURIComponent(jobId)}`,{credentials:'include'});payload=await response.json().catch(()=>({}));if(response.status!==202)break}if(response.status===202)throw new Error('Brevity Assistant took too long. Please retry.')}if(!response.ok)throw new Error(payload.error||`Brevity Assistant request failed (${response.status}).`);return payload}
async function actionRequest(method,action,body){const response=await fetch(`/.netlify/functions/brevity-assistant-actions?action=${encodeURIComponent(action)}`,{method,credentials:'include',headers:{'content-type':'application/json'},body:body?JSON.stringify(body):undefined});const payload=await response.json().catch(()=>({}));if(!response.ok){const error=new Error(payload.error||`Action Mode request failed (${response.status}).`);error.status=response.status;throw error}return payload}
export function getActionMode(){return actionRequest('GET','history')}
export function prepareCalendarAction({summary,operation,expectedEventToken}){return actionRequest('POST','prepare-calendar',{summary,operation,expectedEventToken})}
export function prepareDirectAction({summary,operation,operations,expectedVersion}){return actionRequest('POST','prepare-direct',{summary,operation,operations,expectedVersion})}
export function executeAssistantProposal({proposalId,selections,confirmed,confirmation}){return actionRequest('POST','execute',{proposalId,selections,confirmed,confirmation})}
export function undoAssistantAction({auditId,confirmation}){return actionRequest('POST','undo',{auditId,confirmation})}
export function saveActionPermissions(permissions,expectedVersion,confirmation){return actionRequest('PUT','permissions',{permissions,expectedVersion,confirmation})}
export async function getElevenLabsVoices(){const response=await fetch(`${ELEVENLABS_WORKER}/elevenlabs-voices`,{method:'POST',headers:{'content-type':'application/json'},body:'{}'});const payload=await response.json().catch(()=>({}));if(!response.ok)throw new Error(payload.error||'Could not load your ElevenLabs voices.');return payload.voices||[]}
export async function createElevenLabsSpeech({text,voiceId,signal}){const response=await fetch(`${ELEVENLABS_WORKER}/elevenlabs-tts`,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({voiceId,text,model_id:'eleven_turbo_v2_5'}),signal});if(!response.ok){const payload=await response.json().catch(()=>({}));throw new Error(payload.error||'ElevenLabs could not read this response.')}return response.blob()}

export function prepareRepeatMeal(input){return actionRequest('POST','prepare-repeat-meal',input)}

export async function conversationRequest(action,version){
 const response=await fetch('/.netlify/functions/brevity-conversation',{method:action?'POST':'GET',credentials:'include',headers:{'content-type':'application/json'},...(action?{body:JSON.stringify({action,version})}:{})})
 const data=await response.json().catch(()=>({}))
 if(!response.ok)throw Error(data.error||'Your conversation could not be loaded.')
 return data
}
