import{useEffect,useMemo,useRef,useState}from'react'
import{askBrevityAssistant}from'./assistantApi.js'
import'./BrevityAssistant.css'
const STARTERS=['What needs my attention today?','Analyze this page','Where can we improve cash flow?','What decisions are still open?']
function MessageBody({content}){return <div className="brevity-assistant-message-body">{String(content).split('\n').map((line,index)=><p key={index} className={/^\s*[-*•]|^\s*\d+[.)]/.test(line)?'is-list-line':''}>{line||'\u00a0'}</p>)}</div>}
export default function BrevityAssistant({currentMember,activeView,activePillar,pageLabel}){
  const historyKey=useMemo(()=>`brevity_assistant_history_v1_${String(currentMember).toLowerCase().replace(/\W+/g,'-')}`,[currentMember])
  const[open,setOpen]=useState(false),[draft,setDraft]=useState(''),[busy,setBusy]=useState(false),[error,setError]=useState('')
  const[messages,setMessages]=useState(()=>{try{return JSON.parse(localStorage.getItem(historyKey)||'[]')}catch{return[]}})
  const endRef=useRef(null),inputRef=useRef(null)
  useEffect(()=>{try{localStorage.setItem(historyKey,JSON.stringify(messages.slice(-30)))}catch{}},[historyKey,messages])
  useEffect(()=>{if(open){setTimeout(()=>inputRef.current?.focus(),80);endRef.current?.scrollIntoView({block:'end'})}},[open,messages])
  useEffect(()=>{const close=event=>{if(event.key==='Escape')setOpen(false)};window.addEventListener('keydown',close);return()=>window.removeEventListener('keydown',close)},[])
  const send=async text=>{const content=String(text||draft).trim();if(!content||busy)return;const next=[...messages,{role:'user',content}];setMessages(next);setDraft('');setBusy(true);setError('');try{const result=await askBrevityAssistant({messages:next,member:currentMember,activeView,activePillar,pageLabel});setMessages(existing=>[...existing,{role:'assistant',content:result.message}])}catch(requestError){setError(requestError.message||'Brevity Assistant could not answer right now.')}finally{setBusy(false)}}
  return <><button type="button" className={`brevity-assistant-launcher${open?' is-open':''}`} aria-label={open?'Close Brevity Assistant':'Open Brevity Assistant'} aria-expanded={open} onClick={()=>setOpen(value=>!value)}><i className={`ti ${open?'ti-x':'ti-sparkles'}`} aria-hidden="true"/><span>Ask Brevity</span></button>{open&&<div className="brevity-assistant-backdrop" onClick={()=>setOpen(false)} aria-hidden="true"/>}<section className={`brevity-assistant-drawer${open?' is-open':''}`} role="dialog" aria-modal="true" aria-label="Brevity Assistant" aria-hidden={!open}><header className="brevity-assistant-header"><div><p>Brevity intelligence</p><h2>Brevity Assistant</h2><span>{currentMember} · Viewing {pageLabel}</span></div><div className="brevity-assistant-header-actions"><button type="button" title="Clear conversation" aria-label="Clear conversation" onClick={()=>{setMessages([]);setError('')}}><i className="ti ti-trash"/></button><button type="button" aria-label="Close Brevity Assistant" onClick={()=>setOpen(false)}><i className="ti ti-x"/></button></div></header><div className="brevity-assistant-transcript" aria-live="polite">{!messages.length&&<div className="brevity-assistant-welcome"><div className="brevity-assistant-mark"><i className="ti ti-sparkles"/></div><h3>How can I help with Brevity?</h3><p>I can analyze your household plans, finances, projects, calendars, and saved Seven Pillars insights. I will distinguish posted facts from forecasts and tell you when data is missing.</p><div className="brevity-assistant-starters">{STARTERS.map(starter=><button type="button" key={starter} onClick={()=>send(starter)}>{starter}</button>)}</div></div>}{messages.map((message,index)=><article key={`${message.role}-${index}`} className={`brevity-assistant-message is-${message.role}`}><div className="brevity-assistant-avatar"><i className={`ti ${message.role==='assistant'?'ti-sparkles':'ti-user'}`}/></div><div><span>{message.role==='assistant'?'Brevity Assistant':currentMember}</span><MessageBody content={message.content}/></div></article>)}{busy&&<article className="brevity-assistant-message is-assistant"><div className="brevity-assistant-avatar"><i className="ti ti-sparkles"/></div><div><span>Brevity Assistant</span><div className="brevity-assistant-thinking"><b/><b/><b/></div></div></article>}{error&&<div className="brevity-assistant-error" role="alert">{error}</div>}<div ref={endRef}/></div><footer className="brevity-assistant-composer"><textarea ref={inputRef} rows="2" value={draft} placeholder={`Ask about ${pageLabel}, household data, or next actions…`} onChange={event=>setDraft(event.target.value)} onKeyDown={event=>{if(event.key==='Enter'&&!event.shiftKey){event.preventDefault();send()}}}/><button type="button" onClick={()=>send()} disabled={busy||!draft.trim()} aria-label="Send message"><i className="ti ti-arrow-up"/></button><p>Read-only assistant · Brevity data stays behind household sign-in</p></footer></section></>
}
