import {useEffect,useState} from 'react'
import {requestAssistantConversation} from '../assistant/actionEvents.js'
import './HealthConnections.css'
async function request(action='summary',body){const response=await fetch(`/.netlify/functions/member-health?action=${action}`,{method:body?'POST':'GET',credentials:'include',headers:body?{'content-type':'application/json'}:undefined,body:body?JSON.stringify(body):undefined});const data=await response.json();if(!response.ok)throw Error(data.error||'Health connection unavailable.');return data}
const display=value=>value==null?'Unknown':Number(value).toLocaleString()
export default function HealthConnections({currentMember}){
 const [data,setData]=useState(null),[shared,setShared]=useState(null),[error,setError]=useState(''),[draft,setDraft]=useState(null),[review,setReview]=useState(false),[busy,setBusy]=useState(false)
 async function load(){setError('');try{const [own,household]=await Promise.all([request(),request('household')]);setData(own);setShared(household);setDraft(own.connection)}catch(err){setError(err.message)}}
 useEffect(()=>{let active=true;Promise.all([request(),request('household')]).then(([own,household])=>{if(active){setData(own);setShared(household);setDraft(own.connection)}}).catch(err=>active&&setError(err.message));return()=>{active=false}},[currentMember])
 async function save(){setBusy(true);setError('');try{const next=await request('settings',{...draft,expectedVersion:data.version,confirmed:true});setData(next);setDraft(next.connection);setReview(false);try{setShared(await request('household'))}catch{setShared({unavailable:true,summaries:[]})}}catch(err){setError(err.message)}finally{setBusy(false)}}
 return <section className="health-connections"><p className="health-eyebrow">Health & Nutrition</p><h1>Health Connections</h1><p>Apple Health summaries for {currentMember}. Your private health records are not automatically shared with household administrators.</p>{error&&<p role="alert">{error} <button onClick={load}>Retry</button></p>}{!data&&!error&&<p role="status">Loading your health connection…</p>}{data&&<>
 <article><h2>{data.connection?.enabled?'Apple Health connected':'Connect your iPhone'}</h2>{!data.connection?.enabled?<><p>Open the Brevity Health iPhone companion, sign in as yourself, review the data you want to sync, and approve Apple Health access.</p><p>The companion must first be installed through a signed Apple build. It cannot connect through this website alone.</p></>:<><p>{data.source} · {data.timeZone}</p><p>Last sync: {data.lastSyncAt?new Date(data.lastSyncAt).toLocaleString():'Not synced yet'}{data.stale?' · Needs a fresh sync':''}</p><p>Open the companion to sync now. Background delivery is controlled by iOS and is not continuous monitoring.</p></>}</article>
 <div className="health-metrics"><article><h2>Steps today</h2><strong>{display(data.today.steps)}</strong><p>{data.today.date} · Goal {display(data.connection?.stepGoal)}</p>{data.today.steps!=null&&data.connection?.stepGoal&&<progress aria-label="Daily step goal progress" max={data.connection.stepGoal} value={Math.min(data.today.steps,data.connection.stepGoal)}/>}</article><article><h2>Workouts today</h2><strong>{display(data.today.workoutCount)}</strong><p>{display(data.today.workoutMinutes)} workout window minutes · overlaps combined; may include pauses</p></article></div>
 <p>Unknown means no readable data was returned. It can mean no records, denied access, or no sync. Today’s totals are partial. Steps and workouts do not automatically mark planned tasks complete.</p>
 {data.connection?.enabled&&draft&&<article><h2>Your privacy choices</h2><label>Daily step goal<input type="number" min="100" max="100000" value={draft.stepGoal} onChange={e=>setDraft({...draft,stepGoal:Number(e.target.value)})}/></label>{[['steps','Sync step totals'],['workouts','Sync workout summaries'],['assistantAccess','Let Ask Brevity use these summaries'],['shareSteps','Share daily step totals and goal with the household'],['shareWorkouts','Share daily workout totals with the household']].map(([key,label])=><label className="health-check" key={key}><input type="checkbox" checked={draft[key]} onChange={e=>setDraft({...draft,[key]:e.target.checked})}/>{label}</label>)}<p>Assistant access allows these summaries to be sent to Brevity’s AI provider when you use Ask Brevity. Household sharing exposes only the selected daily totals, not raw Health records.</p><button onClick={()=>setReview(true)}>Review changes</button><button onClick={()=>{setDraft({...draft,enabled:false});setReview(true)}}>Disconnect iPhone</button></article>}
 <article><h2>Last 30 days</h2>{data.days.length?<div className="health-table"><table><thead><tr><th>Date</th><th>Steps</th><th>Workouts</th><th>Window minutes</th></tr></thead><tbody>{[...data.days].reverse().map(day=><tr key={day.date}><td>{day.date}</td><td>{display(day.steps)}</td><td>{display(day.workoutCount)}</td><td>{display(day.workoutMinutes)}</td></tr>)}</tbody></table></div>:<p>No synchronized history yet.</p>}<button onClick={()=>requestAssistantConversation('How am I doing on my steps and workouts? Use my authorized Apple Health summaries and tell me how current they are.')}>Ask Brevity about my activity</button></article>
 <article><h2>Shared household summaries</h2>{shared?.unavailable&&<p>Some household summaries could not be loaded.</p>}{shared?.summaries?.length?shared.summaries.map(row=><div key={row.member}><h3>{row.member}</h3>{'steps'in row&&<p>{display(row.steps)} steps · goal {display(row.stepGoal)}</p>}{'workoutCount'in row&&<p>{display(row.workoutCount)} workouts · {display(row.workoutMinutes)} workout window minutes</p>}<p>{row.date} · {row.lastSyncAt?new Date(row.lastSyncAt).toLocaleString():'No sync'}{row.stale?' · Needs a fresh sync':''}</p></div>):<p>No member has shared a summary yet.</p>}</article>
 <details><summary>Your connection history</summary>{data.audit.length?data.audit.slice().reverse().map((row,index)=><p key={index}>{new Date(row.at).toLocaleString()} · {row.event}</p>):<p>No connection changes yet.</p>}</details>
 </>}{review&&<div className="health-review"><section role="dialog" aria-modal="true" aria-label="Review health privacy changes"><h2>Review {currentMember}’s health connection</h2>{draft.enabled?<ul><li>Steps: {draft.steps?'sync':'off'}; workouts: {draft.workouts?'sync':'off'}</li><li>Step goal: {draft.stepGoal}</li><li>AI access: {draft.assistantAccess?'allowed':'off'}</li><li>Household: {draft.shareSteps&&draft.steps?'step totals shared':'steps private'}; {draft.shareWorkouts&&draft.workouts?'workout totals shared':'workouts private'}</li></ul>:<p>Disconnect this iPhone, stop all sharing and assistant access, and remove synchronized health summaries from Brevity. This removal cannot be undone. Apple Health originals remain on your device; reconnecting requires a new review and sync.</p>}<p>Changing consent stops an older in-flight sync from restoring the previous choices. Previously viewed or discussed information cannot be recalled.</p><button disabled={busy} onClick={()=>{setDraft(data.connection);setReview(false)}}>Cancel</button><button disabled={busy} onClick={save}>{busy?'Saving…':'Confirm health choices'}</button>{error&&<p role="alert">{error}</p>}</section></div>}</section>
}
