import {useEffect,useState} from 'react'
import {CARE_MEMBERS,CARE_TYPES,CARE_STATUSES,carePriorities} from './healthCare.js'
import {getHouseholdDateKey} from '../finance/financeTime.js'
import './HealthCare.css'
export default function HealthCare({currentMember='Larry',isAdmin=false,date=getHouseholdDateKey(new Date()),appointments=[],onOpenCalendar,compact=false,readOnly=false}){
 const [data,setData]=useState(null),[error,setError]=useState(''),[draft,setDraft]=useState(null),[busy,setBusy]=useState(false),[showCompleted,setShowCompleted]=useState(false)
 const load=()=>{setError('');fetch('/.netlify/functions/health-care',{credentials:'include',cache:'no-store'}).then(async r=>{const p=await r.json();if(!r.ok)throw Error(p.error);return p}).then(setData).catch(e=>setError(e.message))}
 useEffect(load,[currentMember])
 const edit=item=>setDraft(item||{title:'',member:currentMember,type:'Medical',status:'Needs scheduling',priority:'Normal',date:'',notes:''})
 const save=async e=>{e.preventDefault();setBusy(true);setError('');try{const r=await fetch('/.netlify/functions/health-care',{method:'POST',credentials:'include',headers:{'content-type':'application/json'},body:JSON.stringify({version:data.version,id:draft.id,item:draft})});const p=await r.json();if(!r.ok)throw Error(p.error);setData(p);setDraft(null)}catch(e){setError(e.message)}finally{setBusy(false)}}
 const items=showCompleted?data?.items||[]:carePriorities(data?.items||[],date)
 const visits=appointments.filter(x=>x.pillar==='health'||/\b(doctor|dentist|dental|orthodont|optometr|ophthalm|eye exam|medical|checkup|check-up|teeth cleaning)\b/i.test(x.title||''))
 return <section className="today-section health-care" aria-label="Health priorities" data-pillar="health"><header className="today-section-heading"><div><span>Pillar 2 · Health &amp; Nutrition</span><h2>Health</h2><p>Medical, dental and eye care · appointments, scheduling and follow-up reviews</p></div>{onOpenCalendar&&<button onClick={onOpenCalendar}>Open Family Calendar</button>}</header>
 <p className="care-note">Shared household care coordination. Private device health measurements remain in Health Connections.</p>
 {error&&<p role="alert">{error} <button onClick={load}>Refresh care</button></p>}
 {!data&&!error&&<p role="status">Loading health priorities…</p>}
 {data&&<><div className="care-toolbar">{!readOnly&&<><button onClick={()=>edit()}>Add health need</button><button onClick={()=>{edit();setDraft({title:'Teeth cleaning',member:currentMember,type:'Dental',status:'Needs scheduling',priority:'Normal',date:'',notes:''})}}>Add dental cleaning</button></>}<label><input type="checkbox" checked={showCompleted} onChange={e=>setShowCompleted(e.target.checked)}/> Show completed</label></div>
 {!items.length&&<p>No {showCompleted?'':'open '}health needs recorded. Add a dental cleaning, doctor visit, eye exam or follow-up to coordinate.</p>}
 <div className="care-list">{items.map(item=><article key={item.id}><div><strong>{item.title}</strong><p>{item.member} · {item.type} · {item.priority==='High'?'High priority · ':''}{item.status}</p><small>{item.date?`${item.date}${item.date<date&&item.status!=='Completed'?' · Past date — review needed':''}`:'Date not set'}{item.notes?` · ${item.notes}`:''}</small></div>{!readOnly&&(isAdmin||item.member===currentMember)&&<button aria-label={`Edit ${item.title} for ${item.member}`} onClick={()=>edit(item)}>Edit</button>}</article>)}</div></>}
 {visits.length>0&&<div><h3>Health appointments on this day’s calendar</h3>{visits.map(x=><p key={x.id}>{x.title} · {x.owner||x.member||currentMember} {x.time||''}</p>)}</div>}
 {draft&&<form className="care-editor" onSubmit={save}><h3>{draft.id?'Edit health need':'Add health need'}</h3><p>These details are shared with the household. Record an appointment here after booking it; use Family Calendar to create the calendar event.</p>{[['title','Health need','text'],['date',draft.status==='Scheduled'?'Appointment date':'Target / review date','date']].map(([key,label,type])=><label key={key}>{label}<input type={type} value={draft[key]} required={key==='title'||draft.status==='Scheduled'} onChange={e=>setDraft({...draft,[key]:e.target.value})}/></label>)}{[['member','Household member',isAdmin?CARE_MEMBERS:[currentMember]],['type','Care type',CARE_TYPES],['status','Status',CARE_STATUSES],['priority','Priority',['Normal','High']]].map(([key,label,options])=><label key={key}>{label}<select value={draft[key]} onChange={e=>setDraft({...draft,[key]:e.target.value})}>{options.map(x=><option key={x}>{x}</option>)}</select></label>)}<label>Coordination notes<textarea value={draft.notes} onChange={e=>setDraft({...draft,notes:e.target.value})}/></label><div className="care-toolbar"><button type="button" disabled={busy} onClick={()=>setDraft(null)}>Cancel</button><button disabled={busy||!data}>{busy?'Saving…':'Save health need'}</button></div></form>}
 </section>
}
