import { useMemo, useState } from 'react'
import { DEBT_STATUSES, DEBT_TYPES, debtSummary, matchedDebtPayments, projectDebtPayoff } from './debtModel.js'
import './DebtWorkspace.css'
import './DebtScenario.css'

const empty={creditor:'',accountName:'',debtType:'Personal loan',originalBalance:'',currentBalance:'',interestRate:'',minimumPayment:'',dueDay:'',paymentMatchText:'',status:'Active',notes:''}
const money=value=>Number(value||0).toLocaleString('en-US',{style:'currency',currency:'USD',maximumFractionDigits:2})
const payload=form=>({creditor:form.creditor.trim(),accountName:form.accountName.trim(),debtType:form.debtType,originalBalance:Number(form.originalBalance||0),currentBalance:Number(form.currentBalance||0),interestRate:Number(form.interestRate||0),minimumPayment:Number(form.minimumPayment||0),dueDay:Number(form.dueDay||0),paymentMatchText:form.paymentMatchText.trim(),status:form.status,notes:form.notes.trim()})

export default function DebtWorkspace({debts=[],transactions=[],scheduledMonthlyNet=0,readOnly=false,onReview}){
  const[editing,setEditing]=useState(null),[form,setForm]=useState(empty),[busy,setBusy]=useState(false),[error,setError]=useState('')
  const summary=useMemo(()=>debtSummary(debts),[debts])
  const[capacity,setCapacity]=useState(()=>String(Math.max(0,scheduledMonthlyNet)+summary.monthlyMinimums)),[reserve,setReserve]=useState('0'),[strategy,setStrategy]=useState('highest-rate')
  const scenario=useMemo(()=>projectDebtPayoff(debts,{monthlyCapacity:Number(capacity),reserve:Number(reserve),strategy}),[debts,capacity,reserve,strategy])
  const open=item=>{setEditing(item||{});setForm(item?Object.fromEntries(Object.entries(empty).map(([key])=>[key,String(item[key]??'')])):empty);setError('')}
  const submit=async event=>{event.preventDefault();setBusy(true);setError('');try{const next=payload(form);if(!next.creditor)throw new Error('Enter the creditor before requesting review.');await onReview?.({kind:editing?.id?'update':'create',debt:editing?.id?{...next,id:editing.id}:next});setEditing(null);setForm(empty)}catch(e){setError(e.message||'This debt change could not be prepared.')}finally{setBusy(false)}}
  return <section className="debt-workspace">
    <header className="debt-hero"><div><p>Finance · Liabilities</p><h1>Debt</h1><span>Track confirmed balances, minimums, payoff progress, and posted payments without confusing a payment with principal reduction.</span></div>{!readOnly&&<button onClick={()=>open(null)}><i className="ti ti-plus"/> Add debt</button>}</header>
    <div className="debt-metrics"><article><span>Total debt</span><strong>{money(summary.totalDebt)}</strong><small>{summary.count} active account{summary.count===1?'':'s'}</small></article><article><span>Paid down</span><strong>{money(summary.paidDown)}</strong><small>From entered original balances</small></article><article><span>Monthly minimums</span><strong>{money(summary.monthlyMinimums)}</strong><small>Required payments entered</small></article><article><span>Weighted APR</span><strong>{summary.weightedApr.toFixed(2)}%</strong><small>Across active balances</small></article></div>
    <section className="debt-scenario"><header><div><p>Payoff scenario</p><h2>Model the path without moving money</h2></div><strong>{scenario.months==null?'Not payable in range':`${scenario.months} month${scenario.months===1?'':'s'}`}</strong></header><div className="debt-scenario-inputs"><label><span>Monthly cash available after obligations</span><input type="number" min="0" step="100" value={capacity} onChange={e=>setCapacity(e.target.value)}/><small>Starts from projected monthly net: {money(scheduledMonthlyNet)}</small></label><label><span>Monthly cash reserve</span><input type="number" min="0" step="100" value={reserve} onChange={e=>setReserve(e.target.value)}/></label><label><span>Payoff order</span><select value={strategy} onChange={e=>setStrategy(e.target.value)}><option value="highest-rate">Highest APR first</option><option value="lowest-balance">Lowest balance first</option></select></label></div><div className="debt-scenario-results"><span><b>{money(scenario.available)}</b> monthly debt capacity</span><span><b>{money(scenario.totalInterest)}</b> projected interest</span><span><b>{money(summary.monthlyMinimums)}</b> monthly cash flow freed after payoff</span></div>{scenario.completed.length>0&&<p className="debt-scenario-note">First projected payoff: {scenario.completed[0].creditor} in month {scenario.completed[0].month}, freeing {money(scenario.completed[0].freedMinimum)} per month. That payment is rolled into the next debt during the scenario.</p>}<small>Projection uses entered balances and APRs. Upcoming scheduled income and obligations establish the starting net, but timing, variable rates, fees, and new charges can change the result.</small></section>
    {editing&&<form className="debt-form" onSubmit={submit}><h2>{editing.id?'Update debt':'Add debt for review'}</h2>{error&&<p className="debt-error" role="alert">{error}</p>}<label><span>Creditor</span><input required value={form.creditor} onChange={e=>setForm({...form,creditor:e.target.value})} placeholder="Prosper"/></label><label><span>Account label</span><input value={form.accountName} onChange={e=>setForm({...form,accountName:e.target.value})} placeholder="Personal loan"/></label><label><span>Debt type</span><select value={form.debtType} onChange={e=>setForm({...form,debtType:e.target.value})}>{DEBT_TYPES.map(v=><option key={v}>{v}</option>)}</select></label><label><span>Status</span><select value={form.status} onChange={e=>setForm({...form,status:e.target.value})}>{DEBT_STATUSES.map(v=><option key={v}>{v}</option>)}</select></label><label><span>Original balance</span><input type="number" min="0" step="0.01" value={form.originalBalance} onChange={e=>setForm({...form,originalBalance:e.target.value})}/></label><label><span>Current confirmed balance</span><input required type="number" min="0" step="0.01" value={form.currentBalance} onChange={e=>setForm({...form,currentBalance:e.target.value})}/></label><label><span>Interest rate (APR %)</span><input type="number" min="0" max="100" step="0.01" value={form.interestRate} onChange={e=>setForm({...form,interestRate:e.target.value})}/></label><label><span>Minimum payment</span><input type="number" min="0" step="0.01" value={form.minimumPayment} onChange={e=>setForm({...form,minimumPayment:e.target.value})}/></label><label><span>Due day</span><input type="number" min="1" max="31" value={form.dueDay} onChange={e=>setForm({...form,dueDay:e.target.value})}/></label><label><span>Payment statement match</span><input value={form.paymentMatchText} onChange={e=>setForm({...form,paymentMatchText:e.target.value})} placeholder="PROSPER"/></label><label className="wide"><span>Notes</span><textarea value={form.notes} onChange={e=>setForm({...form,notes:e.target.value})}/></label><div className="wide debt-form-actions"><button type="button" onClick={()=>setEditing(null)}>Cancel</button><button type="submit" disabled={busy}>{busy?'Preparing review…':'Review in Action Mode'}</button></div></form>}
    <div className="debt-list">{!debts.length&&<div className="debt-empty"><i className="ti ti-receipt-2"/><h2>No debts have been entered</h2><p>Add Prosper, credit cards, student loans, and other liabilities. Nothing is inferred from ordinary expenses.</p></div>}{debts.map(debt=>{const payments=matchedDebtPayments(debt,transactions),paid=Math.max(0,debt.originalBalance-debt.currentBalance),progress=debt.originalBalance?Math.min(100,paid/debt.originalBalance*100):0;return <article className="debt-card" key={debt.id}><header><div><span>{debt.debtType} · {debt.status}</span><h2>{debt.creditor}</h2><p>{debt.accountName||'Debt account'}{debt.dueDay?` · due day ${debt.dueDay}`:''}</p></div><strong>{money(debt.currentBalance)}</strong></header><div className="debt-progress"><i style={{width:`${progress}%`}}/></div><div className="debt-facts"><span><b>{debt.interestRate.toFixed(2)}%</b> APR</span><span><b>{money(debt.minimumPayment)}</b> minimum</span><span><b>{progress.toFixed(1)}%</b> paid down</span></div><section className="debt-payments"><h3>Matched posted payments <em>{payments.length}</em></h3>{payments.slice(0,4).map(tx=><p key={tx.id||`${tx.date}-${tx.name}`}><span>{tx.date} · {tx.name||tx.originalStatement}</span><b>{money(Math.abs(tx.amount))}</b></p>)}{!debt.paymentMatchText&&<small>Add statement match text to connect posted transactions.</small>}{debt.paymentMatchText&&!payments.length&&<small>No posted payment matches “{debt.paymentMatchText}” yet.</small>}<small>Payment totals may include interest and fees; update the confirmed balance from the creditor statement.</small></section>{!readOnly&&<footer><button onClick={()=>open(debt)}>Edit / record balance</button><button className="danger" onClick={()=>onReview?.({kind:'delete',debt})}>Remove</button></footer>}</article>})}</div>
  </section>
}
