import {createPortal} from 'react-dom'
import {useEffect,useMemo,useState,useRef} from 'react'
import {useVendorDirectory,reviewVendor,vendorRequest} from './vendorApi.js'
import {vendorActivity} from './vendorModel.js'
import {fmtMoney} from './projection.js'
import './VendorWorkspace.css'
function VendorDialog({label,onClose,children}){const ref=useRef(null);useEffect(()=>{ref.current.showModal();return()=>ref.current?.close()},[]);return createPortal(<dialog ref={ref} className="vendor-workspace vendor-dialog" aria-label={label} onCancel={e=>{e.preventDefault();onClose()}}>{children}</dialog>,document.body)}
const members=['Larry','Lorenzo','Terica','Nyla','Javin','Isaiah']
const blank=()=>({name:'',address:'',phone:'',email:'',website:'',paymentUrl:'',notes:'',accessMembers:[]})
const details=['name','address','phone','email','website','paymentUrl','notes']
const labels={name:'Vendor name',address:'Address',phone:'Phone',email:'Email',website:'Website',paymentUrl:'Bill payment website',notes:'Notes'}
export default function VendorWorkspace({actuals=[],planned=[],readOnly=false,currentMember,financeVersion,initialVendorId='',vendorOrder=''}){
 const {directory,error:loadError,reload}=useVendorDirectory()
 const [selected,setSelected]=useState(initialVendorId),[form,setForm]=useState(null),[editing,setEditing]=useState(''),[search,setSearch]=useState(''),[error,setError]=useState(''),[message,setMessage]=useState(''),[busy,setBusy]=useState(false)
 const [from,setFrom]=useState(''),[to,setTo]=useState(''),[expenseFilter,setExpenseFilter]=useState('unassigned'),[assignments,setAssignments]=useState({})
 const [loginForm,setLoginForm]=useState(null),[unlocking,setUnlocking]=useState(false),[currentPassword,setCurrentPassword]=useState(''),[revealed,setRevealed]=useState(null)
 useEffect(()=>{if(initialVendorId)setSelected(initialVendorId)},[initialVendorId])
 const vendor=directory?.vendors?.find(v=>v.id===selected)
 const activity=useMemo(()=>vendorActivity(directory,actuals,planned,{dateFrom:from,dateTo:to}),[directory,actuals,planned,from,to])
 const vendors=(directory?.vendors||[]).filter(v=>!v.archived&&`${v.name} ${v.address}`.toLowerCase().includes(search.toLowerCase())).sort((a,b)=>a.name.localeCompare(b.name)*(vendorOrder==='desc'?-1:1))
 const sourceRows=expenseFilter==='unassigned'?activity.unassigned:expenseFilter==='planned'?activity.planned:activity.rows
 const vendorName=id=>directory?.vendors?.find(v=>v.id===id)?.name||'Unassigned'
 const rows=vendorOrder?[...sourceRows].sort((a,b)=>vendorName(a.vendorId).localeCompare(vendorName(b.vendorId))*(vendorOrder==='desc'?-1:1)):sourceRows
 useEffect(()=>{setRevealed(null);setLoginForm(null);setUnlocking(false);setCurrentPassword('')},[selected,currentMember])
 useEffect(()=>{if(!revealed)return;const hide=()=>setRevealed(null),timer=setTimeout(hide,60000),visibility=()=>{if(document.hidden)hide()};window.addEventListener('blur',hide);document.addEventListener('visibilitychange',visibility);return()=>{clearTimeout(timer);window.removeEventListener('blur',hide);document.removeEventListener('visibilitychange',visibility)}},[revealed])
 async function run(work){setBusy(true);setError('');setMessage('');try{await work()}catch(err){setError(err.message)}finally{setBusy(false)}}
 async function review(operation,summary){await reviewVendor(directory,operation,summary,operation.type.startsWith('recurring.')?financeVersion:directory.version);setMessage('Review and confirm this change in Action Mode. Undo is available in Action History after it is applied.')}
 async function saveVendor(){await review({type:editing?'vendor.update':'vendor.create',targetId:editing,payload:form},`${editing?'Update':'Create'} vendor ${form.name}; authorized members: ${form.accessMembers.join(', ')||'administrator only'}`);setForm(null)}
 async function saveLogin(){const {upload}=await vendorRequest('stage-login',{vendorId:vendor.id,...loginForm});setLoginForm(null);await review({type:'vendor.login.attach',targetId:vendor.id,payload:{blobId:upload.blobId}},`Replace protected login/account details for ${vendor.name}. Existing authorized members can access them.`)}
 async function uploadFile(file){if(!file)return;if(file.size>3*1024*1024)throw Error('Choose a file up to 3 MB.');const base64=await new Promise((resolve,reject)=>{const reader=new FileReader();reader.onload=()=>resolve(String(reader.result).split(',')[1]);reader.onerror=()=>reject(Error('File could not be read.'));reader.readAsDataURL(file)});const {upload}=await vendorRequest('stage-document',{vendorId:vendor.id,fileName:file.name,base64});await review({type:'vendor.document.attach',targetId:vendor.id,payload:upload},`Attach ${file.name} to ${vendor.name}`)}
 async function unlock(){const password=currentPassword;setCurrentPassword('');const result=await vendorRequest('unlock',{vendorId:vendor.id,currentPassword:password});setRevealed(result.login);setUnlocking(false)}
 async function copy(value){try{await navigator.clipboard.writeText(value);setMessage('Copied. Paste on the vendor’s website.')}catch{setError('Clipboard access was unavailable. Select and copy the revealed value manually.')}}
 return <section className="vendor-workspace"><header><p className="vendor-eyebrow">Finance</p><h1>Vendors</h1><p>Contacts, payment access, expenses and documents in one place. Payments are completed on the vendor’s website.</p></header>
 {(error||loadError)&&<p role="alert">{error||loadError} <button onClick={reload}>Refresh vendors</button></p>}{message&&<p role="status">{message}</p>}
 {!directory&&!loadError?<p>Loading vendors…</p>:<>
 <div className="vendor-toolbar"><label>Find vendor<input type="search" value={search} onChange={e=>setSearch(e.target.value)}/></label>{!readOnly&&<button onClick={()=>{setEditing('');setForm(blank())}}>Add vendor</button>}</div>
 <div className="vendor-columns"><nav aria-label="Vendor directory">{vendors.length?vendors.map(v=><button key={v.id} aria-pressed={selected===v.id} onClick={()=>setSelected(v.id)}><strong>{v.name}</strong><span>{fmtMoney(activity.totals[v.id]?.net||0)} net posted spending</span></button>):<p>No vendors available. {readOnly?'Ask the administrator to grant access.':'Add a vendor to begin assigning expenses.'}</p>}</nav>
 <div>{vendor&&!vendor.archived?<article><div className="vendor-heading"><h2>{vendor.name}</h2>{!readOnly&&<button onClick={()=>{setEditing(vendor.id);setForm({...blank(),...Object.fromEntries([...details,'accessMembers'].map(key=>[key,vendor[key]??blank()[key]]))})}}>Edit vendor</button>}</div>
 <dl>{['address','phone','email'].map(key=><div key={key}><dt>{labels[key]}</dt><dd>{vendor[key]||'Not provided'}</dd></div>)}</dl>
 {vendor.website&&<a href={vendor.website} target="_blank" rel="noopener noreferrer">Vendor website ↗</a>}{vendor.paymentUrl&&<a className="vendor-payment" href={vendor.paymentUrl} target="_blank" rel="noopener noreferrer">Open bill payment website ↗</a>}{vendor.notes&&<p className="vendor-notes">{vendor.notes}</p>}
 <h3>Spending</h3><div className="vendor-totals">{[['Posted charges','charges'],['Assigned credits / refunds','credits'],['Net posted spending','net'],['Pending charges / credits','pending']].map(([label,key])=><div key={key}><span>{label}</span><strong>{fmtMoney(activity.totals[vendor.id]?.[key]||0)}</strong></div>)}</div><p>Based on available synced bank history and the dates below. Planned expenses and transfers are excluded. Credits reduce spending only when explicitly assigned to this vendor.</p>
 <h3>Login and account numbers</h3><p>Protected details are encrypted separately, excluded from assistant context, and hidden until you unlock them.</p>
 {vendor.loginBlobId?<button onClick={()=>setUnlocking(true)}>Unlock saved login</button>:<p>No login or account details saved.</p>}{!readOnly&&<button onClick={()=>setLoginForm({username:'',password:'',accountNumbers:''})}>{vendor.loginBlobId?'Replace login / accounts':'Add login / accounts'}</button>}
 {unlocking&&<form onSubmit={e=>{e.preventDefault();run(unlock)}}><label>Your Brevity password<input type="password" autoComplete="current-password" value={currentPassword} onChange={e=>setCurrentPassword(e.target.value)}/></label><button disabled={busy||!currentPassword}>Unlock for 60 seconds</button><button type="button" onClick={()=>{setUnlocking(false);setCurrentPassword('')}}>Cancel</button></form>}
 {revealed&&<div className="vendor-revealed">{[['username','Username'],['password','Password'],['accountNumbers','Account numbers / labels']].map(([key,label])=><div key={key}><label>{label}<input readOnly value={revealed[key]||''}/></label><button onClick={()=>copy(revealed[key]||'')}>Copy {label.toLowerCase()}</button></div>)}<button onClick={()=>setRevealed(null)}>Hide now</button><p>Hidden after 60 seconds or when this window loses focus. Copied values remain on your device clipboard until replaced.</p></div>}
 <h3>Documents and images</h3><p>Insurance policies, statements and supporting images. PDF, JPEG, PNG, GIF or WebP; up to 3 MB each.</p>
 {(vendor.documents||[]).map(doc=><div className="vendor-document" key={doc.blobId}><a href={`/.netlify/functions/finance-vendors?action=download&vendorId=${encodeURIComponent(vendor.id)}&blobId=${encodeURIComponent(doc.blobId)}`}>{doc.fileName}</a><small>{Math.ceil(doc.size/1024)} KB</small>{!readOnly&&<button disabled={busy} onClick={()=>run(()=>review({type:'vendor.document.remove',targetId:vendor.id,payload:{blobId:doc.blobId}},`Remove ${doc.fileName} from ${vendor.name}`))}>Review removal</button>}</div>)}
 {!readOnly&&<label>Attach document or image<input disabled={busy} type="file" accept="application/pdf,image/png,image/jpeg,image/gif,image/webp" onChange={e=>{const file=e.target.files?.[0];e.target.value='';run(()=>uploadFile(file))}}/></label>}
 <h3>Access</h3><p>Administrator{vendor.accessMembers?.length?` and ${vendor.accessMembers.join(', ')}`:' only'}. Access includes vendor details, protected login/account information and files.</p>
 {!readOnly&&<button disabled={busy} onClick={()=>run(()=>review({type:'vendor.archive',targetId:vendor.id,payload:{}},`Archive ${vendor.name}. Existing expense links remain in history; use Undo to restore access.`))}>Review archive</button>}
 </article>:<article><h2>Select a vendor</h2><p>Open a vendor to see its contact information, payment links, spending and files.</p></article>}</div></div>
 <article><h2>Expense assignments</h2><div className="vendor-toolbar"><label>Posted from<input type="date" value={from} onChange={e=>setFrom(e.target.value)}/></label><label>Posted through<input type="date" value={to} onChange={e=>setTo(e.target.value)}/></label><label>Show<select value={expenseFilter} onChange={e=>setExpenseFilter(e.target.value)}><option value="unassigned">Unassigned expenses ({activity.unassigned.length})</option><option value="posted">Posted / pending bank activity and credits</option><option value="planned">Planned expenses</option></select></label></div><p>Each expense can be linked to one vendor. Assign vendor refunds explicitly; do not assign salary or unrelated incoming funds. Scheduled amounts are per occurrence and are not counted as paid.</p>
 <div className="vendor-table"><table><thead><tr><th>Expense</th><th>Date / frequency</th><th>Amount</th><th>Vendor</th>{!readOnly&&<th>Review</th>}</tr></thead><tbody>{rows.slice(0,200).map(row=>{const key=`${row.expenseKind}:${row.id}`,chosen=assignments[key]??row.vendorId;return<tr key={key}><td>{row.name||row.merchant_name||'Bank activity'}<small>{row.expenseKind==='planned'?'Planned':row.pending?'Pending':'Posted'}</small></td><td>{row.date||row.start}<small>{row.freq||''}</small></td><td>{fmtMoney(row.amount)}</td><td>{readOnly?directory.vendors.find(v=>v.id===row.vendorId)?.name||'Unassigned':<select aria-label={`Vendor for ${row.name||row.id}`} value={chosen} onChange={e=>setAssignments({...assignments,[key]:e.target.value})}><option value="">Unassigned</option>{directory.vendors.filter(v=>!v.archived).map(v=><option key={v.id} value={v.id}>{v.name}</option>)}</select>}</td>{!readOnly&&<td><button disabled={busy||!chosen||chosen===row.vendorId} onClick={()=>run(()=>review(row.expenseKind==='planned'?{type:'recurring.update',targetId:row.id,targetDate:row.start,payload:{vendorId:chosen},allowedScopes:[row.freq==='once'?'this-item':'this-and-future'],defaultScope:row.freq==='once'?'this-item':'this-and-future'}:{type:'vendor.expense.link',targetId:chosen,payload:{expenseKind:'posted',expenseId:row.id,vendorId:chosen}},`Link ${row.name||'expense'} to ${directory.vendors.find(v=>v.id===chosen)?.name}`))}>Review link</button></td>}</tr>})}</tbody></table></div>{!rows.length&&<p>No matching expenses in the available history.</p>}{rows.length>200&&<p>Showing 200 records. Narrow the date range to review more.</p>}</article>
 </>}
 {form&&<VendorDialog label="Vendor details" onClose={()=>setForm(null)}><h2>{editing?'Edit vendor':'Add vendor'}</h2><form onSubmit={e=>{e.preventDefault();run(saveVendor)}}>{details.map(key=><label key={key}>{labels[key]}{['address','notes'].includes(key)?<textarea value={form[key]} maxLength={key==='notes'?3000:1500} onChange={e=>setForm({...form,[key]:e.target.value})}/>:<input required={key==='name'} type={key==='email'?'email':['website','paymentUrl'].includes(key)?'url':'text'} value={form[key]} onChange={e=>setForm({...form,[key]:e.target.value})}/>}</label>)}<p>Store passwords and account numbers in the protected login area, not Notes.</p><fieldset><legend>Who may access this vendor’s details, login and files?</legend><p>The administrator always has access.</p>{members.map(member=><label className="vendor-check" key={member}><input type="checkbox" checked={form.accessMembers.includes(member)} onChange={e=>setForm({...form,accessMembers:e.target.checked?[...form.accessMembers,member]:form.accessMembers.filter(m=>m!==member)})}/>{member}</label>)}</fieldset><button disabled={busy}>Review vendor changes</button><button type="button" onClick={()=>setForm(null)}>Cancel</button>{error&&<p role="alert">{error}</p>}</form></VendorDialog>}
 {loginForm&&vendor&&<VendorDialog label="Protected vendor login" onClose={()=>setLoginForm(null)}><h2>Protected login for {vendor.name}</h2><p>This replaces all saved login/account details after review. Leave fields blank only if you intend to clear them. Authorized vendor members will be able to unlock these details.</p><form autoComplete="off" onSubmit={e=>{e.preventDefault();run(saveLogin)}}>{[['username','Username'],['password','Password'],['accountNumbers','Account numbers and labels']].map(([key,label])=><label key={key}>{label}<input type={key==='password'?'password':'text'} autoComplete="off" value={loginForm[key]} onChange={e=>setLoginForm({...loginForm,[key]:e.target.value})}/></label>)}<button disabled={busy}>Encrypt and review</button><button type="button" onClick={()=>setLoginForm(null)}>Cancel</button>{error&&<p role="alert">{error}</p>}</form></VendorDialog>}
 </section>
}
