import test from 'node:test'
import assert from 'node:assert/strict'
import {randomBytes} from 'node:crypto'
import {sealVendorBytes,openVendorBytes,createVendorVault,detectVendorFile} from '../../netlify/lib/vendor-vault.mjs'
import {createVendorHandler} from '../../netlify/functions/finance-vendors.mjs'
function memoryStore(){let sequence=0;const map=new Map();return{map,get:async key=>map.get(key)?.data||null,getWithMetadata:async key=>map.get(key)||null,setJSON:async(key,data,options={})=>{const old=map.get(key);if(options.onlyIfNew&&old||options.onlyIfMatch&&old?.etag!==options.onlyIfMatch)return{modified:false};const etag=String(++sequence);map.set(key,{data:structuredClone(data),etag});return{modified:true,etag}}}}
test('vendor secrets are authenticated ciphertext and cannot move between vendor contexts',()=>{const key=randomBytes(32),bytes=Buffer.from('fixture-only-login-secret'),sealed=sealVendorBytes(bytes,key,'vendor-1/blob-1/login');assert.equal(JSON.stringify(sealed).includes(bytes.toString()),false);assert.deepEqual(openVendorBytes(sealed,key,'vendor-1/blob-1/login'),bytes);assert.throws(()=>openVendorBytes(sealed,key,'vendor-2/blob-1/login'));assert.throws(()=>openVendorBytes({...sealed,data:Buffer.from('tampered').toString('base64')},key,'vendor-1/blob-1/login'))})
test('protected staging stores no plaintext credentials and limits unlock attempts',async()=>{const store=memoryStore(),keys=memoryStore(),vault=createVendorVault({store,keys,createId:()=> 'blob-1'}),secret='fixture-only-password';await vault.stage('vendor-1','login',Buffer.from(JSON.stringify({password:secret})),{},'Larry');assert.equal(JSON.stringify([...store.map.values()]).includes(secret),false);assert.equal([...keys.map.values()].length,1);assert.equal(JSON.parse((await vault.read('vendor-1','blob-1','login')).toString()).password,secret);for(let i=0;i<5;i++)await vault.consumeUnlockAttempt('Larry');await assert.rejects(()=>vault.consumeUnlockAttempt('Larry'),error=>error.status===429)})
test('document type comes from bytes and rejects disguised web content',()=>{assert.equal(detectVendorFile(Buffer.from('%PDF-1.4\nfixture')),'application/pdf');assert.throws(()=>detectVendorFile(Buffer.from('<html>not a pdf</html>')));assert.equal(detectVendorFile(Buffer.from([255,216,255,0])),'image/jpeg')})
const vendor={id:'vendor-1',name:'Insurance',accessMembers:['Terica'],loginBlobId:'login-1',documents:[{blobId:'doc-1',fileName:'policy.pdf',mimeType:'application/pdf',size:14}]}
const event=(action,body)=>({httpMethod:body?'POST':'GET',headers:{'content-type':'application/json'},queryStringParameters:{action},body:body?JSON.stringify(body):undefined})
test('vendor API filters member access and rejects guessed document references',async()=>{const repositoryFactory=()=>({read:async()=>({version:1,value:{vendors:[vendor],links:{'posted:tx':'vendor-1'}}})});const handler=createVendorHandler({authenticate:async()=>({member:'Javin',role:'member'}),repositoryFactory});const list=JSON.parse((await handler(event('list'))).body);assert.deepEqual(list.vendors,[]);assert.deepEqual(list.links,{});const download=event('download');download.queryStringParameters={action:'download',vendorId:'vendor-1',blobId:'doc-1'};assert.equal((await handler(download)).statusCode,403)})
test('unlock requires the current member password and audits before returning data; readers cannot upload',async()=>{let checks=[],audit=[],reads=0;const vault={consumeUnlockAttempt:async member=>checks.push(member),read:async()=>{reads++;return Buffer.from(JSON.stringify({username:'fixture',password:'fixture-secret',accountNumbers:'test'}))},audit:async(...args)=>audit.push(args)};const handler=createVendorHandler({authenticate:async()=>({member:'Terica',role:'member'}),verifyPassword:async(member,password)=>member==='Terica'&&password==='fixture-auth',repositoryFactory:()=>({read:async()=>({version:1,value:{vendors:[vendor],links:{}}})}),vaultFactory:()=>vault});const rejected=await handler(event('unlock',{vendorId:'vendor-1',currentPassword:'wrong'}));assert.equal(rejected.statusCode,403);assert.equal(reads,0);const response=await handler(event('unlock',{vendorId:'vendor-1',currentPassword:'fixture-auth'}));assert.equal(response.statusCode,200);assert.equal(JSON.parse(response.body).expiresInSeconds,60);assert.deepEqual(audit,[['Terica','vendor-1','login-revealed']]);assert.equal((await handler(event('stage-login',{vendorId:'vendor-1',username:'x',password:'y',accountNumbers:''}))).statusCode,403)})
test('vendor API rejects missing sessions, form posts and oversized uploads',async()=>{assert.equal((await createVendorHandler({authenticate:async()=>null})(event('list'))).statusCode,401);const handler=createVendorHandler({authenticate:async()=>({member:'Larry',role:'admin'}),repositoryFactory:()=>({read:async()=>({version:0,value:{vendors:[vendor],links:{}}})})});const form=event('stage-login',{});form.headers={};assert.equal((await handler(form)).statusCode,415);const oversized=event('stage-document',{});oversized.body='x'.repeat(5*1024*1024);assert.equal((await handler(oversized)).statusCode,413)})
test('revoking vendor access during password verification prevents reveal',async()=>{
 let revoked=false,reads=0
 const handler=createVendorHandler({authenticate:async()=>({member:'Terica',role:'member'}),verifyPassword:async()=>{revoked=true;return true},repositoryFactory:()=>({read:async()=>({version:1,value:{vendors:[{...vendor,accessMembers:revoked?[]:['Terica']}],links:{}}})}),vaultFactory:()=>({consumeUnlockAttempt:async()=>{},read:async()=>{reads++;return Buffer.from('{}')},audit:async()=>{}})})
 assert.equal((await handler(event('unlock',{vendorId:'vendor-1',currentPassword:'fixture'}))).statusCode,403);assert.equal(reads,0)
})
