import { test, expect } from '@playwright/test'

const dateKey=()=>new Date().toISOString().slice(0,10)
const plan=()=>({id:`daily-plan-${dateKey()}`,date:dateKey(),theme:'Steady stewardship',dayObjective:'Execute today well.',governingPrinciple:'Do the known work.',successStandard:'Critical commitments complete.',topPriorities:[{id:'p1',title:'Protect the household rhythm',owner:'Family',status:'pending',priority:'high',participants:[]},{id:'p2',title:'Complete today’s essential commitments',owner:'Larry',status:'pending',priority:'high',participants:[]},{id:'p3',title:'Prepare tomorrow before closeout',owner:'Family',status:'pending',priority:'normal',participants:[]}],spiritual:{owner:'Family',scope:'household',scripture:['Psalm 1:3'],devotionFocus:'Shared household devotion',prayerFocus:['Wisdom'],discussionPrompts:[],obedienceAction:'Practice the teaching.'},health:{owner:'Terica',breakfast:'Eggs',lunch:'Chicken and vegetables',dinner:'Fish and vegetables',snacks:'Fruit',hydration:'Water',groceries:[],nextDayPrep:''},fitness:{owner:'Larry',location:'Lifetime Gym',participants:[],workout:'Strength',objective:'Train',departureTime:'',returnTime:'',stepGoal:10000,recovery:'',requiresDecision:false},household:{owner:'Larry',appointments:[],priorities:[],errands:[],openItems:[]},education:{owner:'Larry',thinkTankTopic:'',thinkTankDeliverable:'',isaiah:{owner:'Family',readingMinutes:20,sightWordsMinutes:10,comprehensionMinutes:10,mathMinutes:10,notes:''}},finance:{owner:'Larry',bills:[],purchases:[],transfers:[],accountsToFund:[],incomePipeline:[],decisionRule:''},ministry:{owners:['Larry','Lorenzo'],meetings:[],contentFocus:'',fellowshipFollowUps:[],prayerNeeds:[]},assignments:[],decisions:[],dayparts:[],recap:{wins:[],carryovers:[],lessons:[],tomorrowPrep:[],completedAt:''},version:1})
async function mockBackend(page){await page.route('**/.netlify/functions/**',async route=>{const url=new URL(route.request().url()),path=url.pathname,action=url.searchParams.get('action');let body={};if(path.endsWith('/household-auth')&&action==='session')body={authenticated:true,member:'Larry',role:'admin',bootstrapRequired:false};else if(path.endsWith('/household-auth')&&action==='members')body={members:[]};else if(path.endsWith('/household-state')){if(route.request().method()==='PUT'){const payload=route.request().postDataJSON();body={conflict:false,record:{...payload,version:Number(payload.expectedVersion||0)+1,updatedAt:new Date().toISOString(),updatedBy:'Larry'}}}else body={records:{},serverTime:new Date().toISOString()}}else if(path.endsWith('/household-data'))body={householdId:'lslj-family',plan:plan()};else if(path.endsWith('/icloud-calendar'))body={events:[],connected:true,syncedAt:new Date().toISOString()};else if(path.endsWith('/plaid-accounts'))body={connected:false,accounts:[],errors:[],syncedAt:new Date().toISOString()};else if(path.endsWith('/plaid-transactions'))body={transactions:[],errors:[]};else if(path.endsWith('/health-alerts'))body={alerts:[]};else if(path.endsWith('/onedrive-status'))body={configured:true,connected:true,changeRequired:false,connection:{account:'test'}};else if(path.endsWith('/sermon-device-rescue'))body={sermons:[],imports:[]};await route.fulfill({status:200,contentType:'application/json',body:JSON.stringify(body)})})}
async function openMenuIfMobile(page,testInfo){if(testInfo.project.name==='iphone'){const drawer=page.locator('#primary-navigation-drawer');if(!(await drawer.getAttribute('class')||'').includes('is-expanded'))await page.getByRole('button',{name:'Menu'}).click();await expect(drawer).toHaveClass(/is-expanded/)}}

test.beforeEach(async({page})=>{await mockBackend(page);await page.goto('/');await expect(page.locator('.app-shell')).toBeVisible()})

test('Today surfaces populated Daily Outcomes from the daily plan',async({page})=>{for(const outcome of ['Protect the household rhythm','Complete today’s essential commitments','Prepare tomorrow before closeout'])await expect(page.getByText(outcome)).toBeVisible();await expect(page.locator('body')).not.toContainText('Outcome not set')})

test('Household Operations exposes Schedule, Routines, Operations and Inventory without crashing',async({page},testInfo)=>{await openMenuIfMobile(page,testInfo);await page.getByRole('button',{name:'Household Management'}).click();await page.getByRole('button',{name:'Household Operations'}).click();for(const label of ['Schedule','Routines','Operations','Supplies & Inventory'])await expect(page.getByRole('button',{name:label,exact:true})).toBeVisible();await expect(page.locator('body')).not.toContainText('Something went wrong')})

test('Finance primary workspaces open without a fatal error',async({page},testInfo)=>{await openMenuIfMobile(page,testInfo);await page.getByRole('button',{name:'Finance',exact:true}).click();for(const label of ['Dashboard','Meetings','Transactions','Cash Forecast','Accounts','Budget','Recurring','Reporting']){await openMenuIfMobile(page,testInfo);await page.getByRole('button',{name:label,exact:true}).click();await expect(page.locator('body')).not.toContainText('Something went wrong');await expect(page.locator('body')).not.toContainText('Application error')}})

test('Family Calendar opens as the single shared calendar surface',async({page},testInfo)=>{await openMenuIfMobile(page,testInfo);await page.getByRole('button',{name:'Household Management'}).click();await page.getByRole('button',{name:'Family Calendar'}).click();await expect(page.locator('body')).not.toContainText('My Planner');await expect(page.locator('body')).not.toContainText('Something went wrong')})

test('Settings remains operational when optional integration payloads are empty',async({page},testInfo)=>{await openMenuIfMobile(page,testInfo);await page.getByRole('button',{name:'Settings'}).click();await expect(page.getByRole('heading',{name:'Settings',exact:true})).toBeVisible();await expect(page.locator('body')).not.toContainText('Recovery Mode');await expect(page.locator('body')).not.toContainText('Cannot read properties of undefined')})

test('iPhone alignment keeps Next Pillar above fixed bottom navigation',async({page},testInfo)=>{test.skip(testInfo.project.name!=='iphone','iPhone layout contract');await page.getByRole('button',{name:/Start Today’s Alignment/}).click();const next=page.getByRole('button',{name:'Next Pillar'}),bottomNav=page.locator('.mobile-app-nav'),main=page.locator('.app-main');await expect(next).toBeVisible();await expect(bottomNav).toBeVisible();await main.evaluate(element=>{element.scrollTop=element.scrollHeight});await expect.poll(async()=>{const nextBox=await next.boundingBox(),navBox=await bottomNav.boundingBox();return nextBox&&navBox?Math.round(navBox.y-(nextBox.y+nextBox.height)):-999},{timeout:5000}).toBeGreaterThanOrEqual(0)})
