import {useState} from 'react'
import {MEAL_TYPES} from './mealLibrary.js'
import {MEAL_POLICY_NOTICE,mealPlanWarnings} from './householdMealPlanning.js'
import './MealCalendar.css'
const label=slot=>({breakfast:'Breakfast',lunch:'Lunch',dinner:'Dinner',snack1:'Snack 1',snack2:'Snack 2'}[slot])
export default function MealCalendar({days,monthly,onEdit,onReview,onOpenMeal,canEdit,busy}){
 const [source,setSource]=useState(null),[date,setDate]=useState(days[0]?.date||''),[destination,setDestination]=useState(''),[offset,setOffset]=useState(1)
 const warnings=mealPlanWarnings(days)
 const move=(toDate,toSlot)=>{if(!source)return;onReview({kind:'move',date:source.date,slot:source.slot,toDate,toSlot});setSource(null)}
 return <section className="meal-calendar-workspace" aria-label="Meal calendar"><p>{MEAL_POLICY_NOTICE} Seasonings such as garlic and herbs are not counted as vegetable sides. Snacks remain available.</p>
 <div className="meal-calendar-tools"><button disabled={!canEdit||busy} onClick={()=>onReview({kind:'generate',date:days[0].date,count:days.length})}>Auto-schedule {monthly?'month':'week'}</button><label>Starting day<input type="date" value={date} onChange={e=>setDate(e.target.value)}/></label><label>Destination day<input type="date" value={destination} onChange={e=>setDestination(e.target.value)}/></label><button disabled={!canEdit||busy||!destination} onClick={()=>onReview({kind:'swap-day',date,toDate:destination})}>Swap days</button><button disabled={!canEdit||busy||!destination} onClick={()=>onReview({kind:'move-day',date,toDate:destination})}>Move day</button><label>Shift seven days<select value={offset} onChange={e=>setOffset(Number(e.target.value))}>{[-3,-2,-1,1,2,3].map(n=><option key={n} value={n}>{n>0?'+':''}{n} {Math.abs(n)===1?'day':'days'}</option>)}</select></label><button disabled={!canEdit||busy||!date} onClick={()=>onReview({kind:'shift-week',date,offset})}>Shift week</button></div>
 <p>Six people per meal by default. Customize portions for any date. Drag a meal onto another slot to swap, or select “Move” then a destination. Day moves and week shifts replace destination menus after review.</p>
 {source&&<p role="status">Moving {label(source.slot)} on {source.date}. Choose a destination below. <button onClick={()=>setSource(null)}>Cancel move</button></p>}
 {warnings.length>0&&<details className="meal-calendar-warnings"><summary>{warnings.length} meal preferences to review</summary>{warnings.map(w=><p key={w}>{w}</p>)}</details>}
 {!monthly&&<p className="meal-week-scroll-hint">Swipe across each day to see breakfast, lunch, and dinner.</p>}
 <div className={`meal-calendar-grid${monthly?' is-month':''}`}>
 {monthly&&['Sun','Mon','Tue','Wed','Thu','Fri','Sat'].map(day=><strong className="meal-calendar-weekday" key={day}>{day}</strong>)}
 {monthly&&Array.from({length:new Date(`${days[0].date}T12:00:00Z`).getUTCDay()},(_,i)=><div className="meal-calendar-spacer" key={`blank-${i}`}/>)}
 {days.map(day=><article className="meal-calendar-day" key={day.date}><h3><time dateTime={day.date}>{new Date(`${day.date}T12:00:00Z`).toLocaleDateString('en-US',{month:'short',day:'numeric',weekday:'short',timeZone:'UTC'})}</time></h3><div className="meal-calendar-day-meals" tabIndex={monthly?undefined:0} role={monthly?undefined:'region'} aria-label={monthly?undefined:`Meals for ${day.date}`}>{MEAL_TYPES.map(slot=>{const meal=day.resolvedMeals?.[slot];return <section className="meal-calendar-slot" key={slot} onDragOver={e=>{if(canEdit)e.preventDefault()}} onDrop={e=>{e.preventDefault();if(canEdit)move(day.date,slot)}}><div draggable={canEdit&&Boolean(meal)} onDragStart={()=>setSource({date:day.date,slot})}>{!monthly&&meal?.image&&<img className="meal-calendar-photo" src={meal.image} alt={meal.name} loading="lazy"/>}<small>{label(slot)} · {day.servings?.[slot]??6} people</small><strong>{meal?.name||'No meal scheduled'}</strong></div><div className="meal-calendar-slot-actions">{meal&&<button aria-label={`View ${meal.name} details`} onClick={()=>onOpenMeal({...meal,_plannedSelection:{day,slot},plannedServings:day.servings?.[slot]??6})}>Recipe</button>}<button disabled={!canEdit||busy} onClick={()=>onEdit({day,slot})}>{meal?'Customize':'Build meal'}</button>{source?<button disabled={!canEdit||busy||source.date===day.date&&source.slot===slot} onClick={()=>move(day.date,slot)}>Place here</button>:meal&&<button disabled={!canEdit||busy} onClick={()=>setSource({date:day.date,slot})}>Move</button>}</div></section>})}</div></article>)}
 </div></section>
}
