import {useState} from 'react'
import {previewPlanToEatImport} from './planToEatImport.js'
import {libraryCategoryLabel,mealReadyForPlanning} from './mealCategories.js'
import {importPlanToEatCsv} from './mealPlanApi.js'
export default function RecipeCsvImport({library,onClose,onSaved}){
 const [csv,setCsv]=useState(''),[preview,setPreview]=useState(null),[busy,setBusy]=useState(false),[error,setError]=useState('')
 const read=async event=>{const file=event.target.files?.[0];if(!file)return;setError('');setPreview(null);try{if(file.size>4_000_000)throw Error('Choose a CSV smaller than 4 MB.');const text=await file.text();setPreview(previewPlanToEatImport(text,library));setCsv(text)}catch(cause){setError(cause.message)}}
 const save=async()=>{setBusy(true);setError('');try{const result=await importPlanToEatCsv(csv);await onSaved(result);onClose()}catch(cause){setError(cause.message)}finally{setBusy(false)}}
 return <div className="meal-dialog-backdrop"><section className="meal-dialog meal-swap-dialog" role="dialog" aria-modal="true" aria-labelledby="csv-import-title"><header><div><h2 id="csv-import-title">Import Plan to Eat recipes</h2><p>Recipes, sides and individual foods enter one shared library. Calendar meal slots are separate.</p></div><button disabled={busy} onClick={onClose} aria-label="Close CSV import">×</button></header><div className="meal-swap-library"><label>Plan to Eat CSV<input type="file" accept=".csv,text/csv" onChange={read} disabled={busy}/></label>{error&&<p role="alert">{error}</p>}{preview&&<><p role="status">{preview.total} recipes found · {preview.meals.length} new · {preview.skipped.length} duplicates skipped · {preview.needsReview} need recipe or nutrition review</p><p>Original batch yields and supplied nutrition are preserved. Missing nutrition stays unknown. Incomplete recipes remain in the library for editing and are excluded from planning until reviewed.</p><details><summary>Review imported recipes</summary><ul>{preview.meals.map(meal=><li key={meal.id}>{meal.name} — {libraryCategoryLabel(meal)}{mealReadyForPlanning(meal)?'':' — Needs review'}{meal.nutritionWarnings.length>0&&<ul>{meal.nutritionWarnings.map(w=><li key={w}>{w}</li>)}</ul>}</li>)}</ul></details>{preview.skipped.length>0&&<details><summary>Skipped existing recipes</summary><ul>{preview.skipped.map((name,i)=><li key={i}>{name}</li>)}</ul></details>}</>}</div><footer><button disabled={busy} onClick={onClose}>Cancel</button><button disabled={busy||!preview?.meals.length} onClick={save}>{busy?'Importing…':`Import ${preview?.meals.length||0} recipes`}</button></footer></section></div>
}
