import {useState} from 'react'
import {calculateMealNutrition} from './mealPlanApi.js'
import {scaleIngredient,householdIngredients,containsSeafood} from './householdMealPlanning.js'
const components=[['Chicken breast','ounces','cooked chicken breast',6],['Chicken thigh','ounces','cooked boneless chicken thigh',6],['Steak','ounces','cooked beef sirloin steak',6],['Ground beef','ounces','cooked ground beef',6],['Pork tenderloin','ounces','cooked pork tenderloin',6],['Broccoli','cups','cooked broccoli',1],['Green beans','cups','cooked green beans',1],['Asparagus','spears','cooked asparagus',10],['Sweet potato','ounces','cooked sweet potato',6],['Carrots','cups','cooked carrots',1],['Spinach','cups','cooked spinach',1],['Rice','cups','cooked brown rice',0.5],['Potato','ounces','cooked potato',6]]
export default function ScheduledMealEditor({selection,library,onClose,onReview,busy}){
 const {day,slot}=selection,initial=day.resolvedMeals?.[slot]
 const [mealId,setMealId]=useState(day.meals?.[slot]||''),[name,setName]=useState(initial?.name||'À la carte meal'),[people,setPeople]=useState(day.servings?.[slot]??6)
 const [ingredients,setIngredients]=useState(()=>(initial?.ingredients||[]).map(line=>scaleIngredient(line,1/(Number(initial?.yieldQuantity)||1))))
 const [instructions,setInstructions]=useState(initial?.instructions?.join('\n')||'Cook each component fully using its appropriate preparation method, then divide into the specified portions.')
 const [macros,setMacros]=useState(initial?.macros||null),[custom,setCustom]=useState(Boolean(day.recipes?.[slot])),[dirty,setDirty]=useState(false),[error,setError]=useState(''),[calculating,setCalculating]=useState(false)
 const [component,setComponent]=useState(0),[amount,setAmount]=useState(6),[replaceIndex,setReplaceIndex]=useState('add')
 const changeIngredients=next=>{setIngredients(next);setCustom(true);setDirty(true)}
 const chooseRecipe=id=>{const meal=library.find(m=>m.id===id);if(!meal)return;setMealId(id);setName(meal.name);setIngredients((meal.ingredients||[]).map(line=>scaleIngredient(line,1/(Number(meal.yieldQuantity)||1))));setInstructions(meal.instructions?.join('\n')||'');setMacros(meal.macros);setCustom(false);setDirty(false)}
 const addComponent=()=>{if(!Number.isFinite(Number(amount))||Number(amount)<=0)return;const c=components[component],line=`${Number(amount)} ${c[1]==='spears'?'asparagus spears, cooked':`${c[1]} ${c[2]}`}`;changeIngredients(replaceIndex==='add'?[...ingredients,line]:ingredients.map((old,i)=>i===Number(replaceIndex)?line:old));setReplaceIndex('add')}
 const calculate=async()=>{setCalculating(true);setError('');try{const {nutrition}=await calculateMealNutrition(ingredients,1,'person');if(nutrition.clarifications?.length||!nutrition.perServingMacros)throw Error('Clarify ingredient amounts and preparation before calculating nutrition.');setMacros(nutrition.perServingMacros);setDirty(false)}catch(cause){setError(cause.message)}finally{setCalculating(false)}}
 const submit=async e=>{e.preventDefault();setError('');if(dirty||!macros){setError('Calculate nutrition after changing ingredients.');return}try{await onReview({kind:'set',date:day.date,slot,servings:Number(people),...(mealId?{mealId}:{}),...(custom||!mealId?{recipe:{name,ingredients,instructions:instructions.split('\n').filter(Boolean),macros}}:{})});onClose()}catch(cause){setError(cause.message)}}
 const working=busy||calculating
 return <div className="meal-dialog-backdrop"><section className="meal-dialog meal-edit-dialog scheduled-meal-editor" role="dialog" aria-modal="true" aria-labelledby="scheduled-meal-title"><header><div><span>{day.date} · {slot}</span><h2 id="scheduled-meal-title">Customize this meal</h2><p>Changes apply only to this date. Nutrition and portions are per person; groceries scale to the people eating.</p></div><button disabled={working} onClick={onClose} aria-label="Close scheduled meal editor">×</button></header><form onSubmit={submit}><div className="meal-edit-scroll" tabIndex="0" role="region" aria-label="Scheduled meal fields"><fieldset className="meal-edit-fields" disabled={working}>
 <label>People eating<input required type="number" min="1" max="100" step="1" value={people} onChange={e=>setPeople(e.target.value)}/></label>
 <label>Use a library meal<select value={mealId} onChange={e=>chooseRecipe(e.target.value)}><option value="">Choose a meal</option>{library.map(meal=><option key={meal.id} value={meal.id}>{meal.name}{containsSeafood(meal)?' — Seafood':''}</option>)}</select></label>
 <button type="button" onClick={()=>{setMealId('');setName('À la carte meal');changeIngredients([]);setMacros(null);setInstructions('Cook each component fully using its appropriate preparation method, then divide into the specified portions.')}}>Build à la carte</button>
 <label>Meal name<input required maxLength="200" value={name} onChange={e=>{setName(e.target.value);setCustom(true)}}/></label>
 <h3>Ingredients for one person</h3><div className="scheduled-meal-ingredients">{ingredients.map((line,i)=><div className="scheduled-meal-ingredient" key={i}><input aria-label={`Ingredient ${i+1} per person`} required value={line} onChange={e=>changeIngredients(ingredients.map((old,j)=>i===j?e.target.value:old))}/><button type="button" onClick={()=>changeIngredients(ingredients.filter((_,j)=>i!==j))}>Remove</button></div>)}</div>
 <div className="meal-component-builder"><label>Component<select value={component} onChange={e=>{setComponent(Number(e.target.value));setAmount(components[Number(e.target.value)][3])}}>{components.map((c,i)=><option key={c[0]} value={i}>{c[0]}</option>)}</select></label><label>{components[component][1]} per person<input type="number" min="0.01" step="any" value={amount} onChange={e=>setAmount(e.target.value)}/></label><label>Add or replace<select value={replaceIndex} onChange={e=>setReplaceIndex(e.target.value)}><option value="add">Add component</option>{ingredients.map((line,i)=><option key={i} value={i}>Replace: {line}</option>)}</select></label><button type="button" onClick={addComponent}>Use component</button></div><button type="button" onClick={()=>changeIngredients([...ingredients,''])}>Add another ingredient</button>
 <label>Cooking instructions<textarea required rows="4" value={instructions} onChange={e=>{setInstructions(e.target.value);setCustom(true)}}/></label><p>When swapping ingredients, update the cooking steps to match. Component weights above are cooked edible portions; grocery quantities retain that basis and do not guess raw purchasing weights.</p>
 {containsSeafood({name,ingredients})&&<p role="alert">This meal contains seafood. It is excluded from automatic plans because of household allergies. Only continue if this is a deliberate selection.</p>}
 <button type="button" disabled={!ingredients.length||ingredients.some(line=>!line.trim())} onClick={calculate}>{calculating?'Calculating…':'Calculate nutrition'}</button>
 {macros&&<p>{dirty?'Needs recalculation · ':''}Per person: {macros.calories} cal · {macros.proteinGrams}g protein · {macros.carbohydrateGrams}g carbs · {macros.fatGrams}g fat</p>}
 <h3>Prepare for {people||6} people</h3><ul>{householdIngredients({ingredients,yieldQuantity:1},Number(people)||6).map((line,i)=><li key={i}>{line}</li>)}</ul>
 </fieldset>{error&&<p role="alert">{error}</p>}</div><footer><button type="button" disabled={working} onClick={onClose}>Cancel</button><button className="is-primary" disabled={working||dirty||!macros||!ingredients.length} type="submit">Review changes</button></footer></form></section></div>
}
