import test from 'node:test'
import assert from 'node:assert/strict'
import { buildFitnessImagePrompt, familyFitnessReference, generateFitnessImage } from '../../netlify/lib/fitness-image.mjs'
import { createFitnessImageHandler } from '../../netlify/functions/fitness-image-generate.mjs'

const exercise={id:'lat-pulldown',name:'Wide-neutral lat pulldown',cue:'Drive elbows toward the hips.'}
test('fitness image prompt requires identity preservation and a complete instructional frame',()=>{const prompt=buildFitnessImagePrompt(exercise,'Larry');assert.match(prompt,/identity reference/i);assert.match(prompt,/complete body/i);assert.match(prompt,/do not crop/i);assert.match(prompt,/Landscape 4:3/i)})
test('each named family member resolves to a bundled identity reference',()=>{for(const member of ['Larry','Lorenzo','Isaiah','Nyla','Javin','Terica'])assert.equal(familyFitnessReference(member)?.member,member);assert.equal(familyFitnessReference('Unknown'),null)})
test('generated fitness image is stored and returned through the authenticated image route',async()=>{let saved;const png=Buffer.from([0x89,0x50,0x4e,0x47,0x0d,0x0a,0x1a,0x0a]);const fetcher=async()=>({ok:true,json:async()=>({data:[{b64_json:png.toString('base64')} ]})});const image=await generateFitnessImage({exercise,member:'Larry',assetId:'asset-1',householdId:'house',store:{set:async(key,value)=>{saved={key,value}}},fetcher});assert.equal(image,'/.netlify/functions/fitness-images?id=asset-1');assert.match(saved.key,/house\/fitness\/asset-1\.png$/);assert.deepEqual(saved.value,png)})
test('fitness image generation records a durable background job',async()=>{const writes=[];const handler=createFitnessImageHandler({readSessionFn:async()=>({member:'Larry'}),jobStore:{setJSON:async(key,value)=>writes.push({key,value})},imageStore:{},generateImage:async()=>'/generated.png',now:()=>new Date('2026-09-20T12:00:00Z')});const response=await handler(new Request('https://example.test/.netlify/functions/fitness-image-generate',{method:'POST',headers:{cookie:'session=1','content-type':'application/json'},body:JSON.stringify({jobId:'job-1',exerciseId:'lat-pulldown',member:'Larry'})}));assert.equal(response.status,202);assert.equal(writes[0].value.state,'generating');assert.equal(writes.at(-1).value.state,'ready');assert.equal(writes.at(-1).value.image,'/generated.png')})
