import crypto from 'node:crypto'
import { getStore } from '@netlify/blobs'

const HOUSEHOLD_ID=process.env.BREVITY_HOUSEHOLD_ID||'lslj-family'
const STORE_NAME='brevity-household'
const CONNECTION_KEY=`${HOUSEHOLD_ID}/integrations/onedrive`
const stateKey=state=>`${HOUSEHOLD_ID}/integrations/onedrive-states/${state}`
export const REDIRECT_URI='https://brevityoflife.netlify.app/.netlify/functions/onedrive-oauth-callback'
const store=()=>getStore({name:STORE_NAME,consistency:'strong',siteID:process.env.NETLIFY_SITE_ID,token:process.env.NETLIFY_TOKEN})
const config=()=>({clientId:process.env.MICROSOFT_CLIENT_ID||'',clientSecret:process.env.MICROSOFT_CLIENT_SECRET||'',folderUrl:process.env.ONEDRIVE_FOLDER_SHARE_URL||''})
const graph=async(path,accessToken,options={})=>{const response=await fetch(`https://graph.microsoft.com/v1.0${path}`,{...options,headers:{authorization:`Bearer ${accessToken}`,...options.headers}});const payload=await response.json().catch(()=>({}));if(!response.ok){const error=new Error(payload.error?.message||`Microsoft Graph returned ${response.status}.`);error.code=payload.error?.code||String(response.status);error.graphPath=path;error.requestId=response.headers.get('request-id')||payload.error?.innerError?.['request-id']||'';throw error}return payload}
const tokenRequest=async params=>{const {clientId,clientSecret}=config();const response=await fetch('https://login.microsoftonline.com/common/oauth2/v2.0/token',{method:'POST',headers:{'content-type':'application/x-www-form-urlencoded'},body:new URLSearchParams({client_id:clientId,client_secret:clientSecret,redirect_uri:REDIRECT_URI,...params})});const payload=await response.json().catch(()=>({}));if(!response.ok)throw new Error(payload.error_description||'Microsoft authorization failed.');return payload}
const shareId=url=>`u!${Buffer.from(url).toString('base64url')}`

export function oneDriveConfigured(){const value=config();return Boolean(value.clientId&&value.clientSecret&&value.folderUrl)}
export async function createOneDriveAuthorization(){if(!oneDriveConfigured())throw new Error('OneDrive publishing is not configured.');const state=crypto.randomUUID();await store().setJSON(stateKey(state),{createdAt:Date.now()});const {clientId}=config();const query=new URLSearchParams({client_id:clientId,response_type:'code',redirect_uri:REDIRECT_URI,response_mode:'query',scope:'offline_access Files.ReadWrite User.Read',state,prompt:'select_account'});return `https://login.microsoftonline.com/common/oauth2/v2.0/authorize?${query}`}
export async function completeOneDriveAuthorization({code,state}){const dataStore=store();const pending=await dataStore.get(stateKey(state),{type:'json'}).catch(()=>null);if(!pending||Date.now()-Number(pending.createdAt)>15*60*1000)throw new Error('The OneDrive connection request expired. Start the connection again.');await dataStore.delete(stateKey(state)).catch(()=>{});const tokens=await tokenRequest({grant_type:'authorization_code',code});if(!tokens.refresh_token)throw new Error('Microsoft did not return an offline authorization.');const {folderUrl}=config();const [user,item]=await Promise.all([graph('/me?$select=displayName,userPrincipalName',tokens.access_token),graph(`/shares/${shareId(folderUrl)}/driveItem?$select=id,name,webUrl,parentReference`,tokens.access_token,{headers:{Prefer:'redeemSharingLinkIfNecessary'}})]);const driveId=item.parentReference?.driveId;if(!driveId||!item.id)throw new Error('Microsoft could not resolve the Church Triumphant OneDrive folder.');const connection={refreshToken:tokens.refresh_token,driveId,folderItemId:item.id,folderName:item.name||'Sermon Notes',folderWebUrl:item.webUrl||folderUrl,account:user.userPrincipalName||user.displayName||'Microsoft account',connectedAt:new Date().toISOString()};await dataStore.setJSON(CONNECTION_KEY,connection);return connection}
export async function getOneDriveConnection(){return store().get(CONNECTION_KEY,{type:'json'}).catch(()=>null)}
async function accessToken(){const dataStore=store();const connection=await dataStore.get(CONNECTION_KEY,{type:'json'}).catch(()=>null);if(!connection?.refreshToken)throw new Error('Church Triumphant OneDrive is not connected.');const tokens=await tokenRequest({grant_type:'refresh_token',refresh_token:connection.refreshToken,scope:'offline_access Files.ReadWrite User.Read'});if(tokens.refresh_token&&tokens.refresh_token!==connection.refreshToken)await dataStore.setJSON(CONNECTION_KEY,{...connection,refreshToken:tokens.refresh_token,refreshedAt:new Date().toISOString()});return {token:tokens.access_token,connection}}
const DESTINATIONS={pdf:'Sermon Notes',word:'Sermon Notes - Word Documents',devotions:'Devotions'}
const sameName=(left,right)=>String(left||'').trim().toLowerCase()===String(right||'').trim().toLowerCase()
const createFolder=async({token,driveId,parentId,name})=>{const response=await fetch(`https://graph.microsoft.com/v1.0/drives/${encodeURIComponent(driveId)}/items/${encodeURIComponent(parentId)}/children`,{method:'POST',headers:{authorization:`Bearer ${token}`,'content-type':'application/json'},body:JSON.stringify({name,folder:{},'@microsoft.graph.conflictBehavior':'fail'})});const payload=await response.json().catch(()=>({}));if(response.ok)return payload;if(response.status!==409)throw new Error(payload.error?.message||`OneDrive folder creation returned ${response.status}.`);const children=await graph(`/drives/${encodeURIComponent(driveId)}/items/${encodeURIComponent(parentId)}/children?$select=id,name,webUrl,folder`,token);const existing=(children.value||[]).find(item=>item.folder&&sameName(item.name,name));if(!existing)throw new Error(`OneDrive could not locate the ${name} folder.`);return existing}
async function publishingFolders(token,connection){const linked=await graph(`/drives/${encodeURIComponent(connection.driveId)}/items/${encodeURIComponent(connection.folderItemId)}?$select=id,name,webUrl,parentReference`,token);const linkedIsPdfFolder=sameName(linked.name,DESTINATIONS.pdf);const rootId=linkedIsPdfFolder?linked.parentReference?.id:linked.id;if(!rootId)throw new Error('OneDrive could not locate the Church Triumphant parent folder.');const pdf=linkedIsPdfFolder?linked:await createFolder({token,driveId:connection.driveId,parentId:rootId,name:DESTINATIONS.pdf});const [word,devotions]=await Promise.all([createFolder({token,driveId:connection.driveId,parentId:rootId,name:DESTINATIONS.word}),createFolder({token,driveId:connection.driveId,parentId:rootId,name:DESTINATIONS.devotions})]);return {pdf,word,devotions}}
const safeFileName=name=>String(name||'Brevity document').replace(/["*:<>?\\/|]/g,'-').replace(/[. ]+$/g,'').replace(/\s+/g,' ').slice(0,180)
const folderRelativePath=folder=>{const parentPath=String(folder.parentReference?.path||'');const marker='/root:';const index=parentPath.indexOf(marker);if(index<0)return '';return `${parentPath.slice(index+marker.length)}/${folder.name}`.split('/').filter(Boolean).map(encodeURIComponent).join('/')}
const uploadToFolder=async({token,connection,folder,bytes,name})=>{const fileName=safeFileName(name);const relativeFolder=folderRelativePath(folder);const target=relativeFolder?`/drives/${encodeURIComponent(connection.driveId)}/root:/${relativeFolder}/${encodeURIComponent(fileName)}:/createUploadSession`:`/drives/${encodeURIComponent(connection.driveId)}/items/${encodeURIComponent(folder.id)}:/${encodeURIComponent(fileName)}:/createUploadSession`;let session;try{session=await graph(target,token,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({item:{'@microsoft.graph.conflictBehavior':'replace'}})})}catch(error){console.error('[onedrive upload session]',JSON.stringify({stage:'create-upload-session',code:error.code,message:error.message,requestId:error.requestId,folderId:folder.id,folderName:folder.name,fileName,route:relativeFolder?'root-path':'item-path'}));throw new Error(`OneDrive could not prepare ${fileName}: ${error.message}`)}if(!session.uploadUrl)throw new Error('Microsoft did not provide a OneDrive upload session.');const content=Buffer.from(bytes);const response=await fetch(session.uploadUrl,{method:'PUT',headers:{'content-type':'application/octet-stream','content-length':String(content.length),'content-range':`bytes 0-${content.length-1}/${content.length}`},body:content});const payload=await response.json().catch(()=>({}));if(!response.ok){console.error('[onedrive upload bytes]',JSON.stringify({stage:'upload-bytes',status:response.status,message:payload.error?.message,folderName:folder.name,fileName}));throw new Error(payload.error?.message||`OneDrive upload returned ${response.status}.`)}return {id:payload.id,name:payload.name,webUrl:payload.webUrl,folderName:folder.name,folderWebUrl:folder.webUrl}}
export async function publishSermonDocuments({docx,pdf,baseName}){const {token,connection}=await accessToken();const folders=await publishingFolders(token,connection);const [word,pdfFile]=await Promise.all([uploadToFolder({token,connection,folder:folders.word,bytes:docx,name:`${baseName}.docx`,type:'application/vnd.openxmlformats-officedocument.wordprocessingml.document'}),uploadToFolder({token,connection,folder:folders.pdf,bytes:pdf,name:`${baseName}.pdf`,type:'application/pdf'})]);return {state:'published',folderName:'Church Triumphant',folderWebUrl:folders.pdf.webUrl||connection.folderWebUrl,account:connection.account,publishedAt:new Date().toISOString(),folders:{pdf:{name:folders.pdf.name,webUrl:folders.pdf.webUrl},word:{name:folders.word.name,webUrl:folders.word.webUrl}},files:{docx:word,pdf:pdfFile}}}
export async function publishDailyDevotion({pdf,baseName}){const {token,connection}=await accessToken();const folders=await publishingFolders(token,connection);const file=await uploadToFolder({token,connection,folder:folders.devotions,bytes:pdf,name:`${baseName}.pdf`,type:'application/pdf'});return {state:'published',folderName:folders.devotions.name,folderWebUrl:folders.devotions.webUrl,account:connection.account,publishedAt:new Date().toISOString(),file}}
