import pptxgen from 'pptxgenjs'
import { buildSermonSlideSpecs, sermonSlidesFileName } from './sermon-slide-model.mjs'
export { buildSermonSlideSpecs, sermonSlidesFileName }
const clean=value=>String(value||'').replace(/\s+/g,' ').trim(),values=value=>Array.isArray(value)?value.filter(Boolean):value?[value]:[]
const PREMIUM='Ultra-photorealistic editorial magazine photography, cinematic lighting, luxury commercial color grading, natural skin tones and authentic textures, high-end documentary photography, sophisticated composition, subtle depth of field, 8K-quality realism, theologically respectful Christian visual storytelling, no text, no lettering, no logos, wide 16:9 composition.'
async function generateImage(prompt){const response=await fetch('https://api.openai.com/v1/images/generations',{method:'POST',headers:{authorization:`Bearer ${process.env.OPENAI_API_KEY}`,'content-type':'application/json'},body:JSON.stringify({model:process.env.BREVITY_IMAGE_MODEL||'gpt-image-2',prompt,size:'1536x1024',quality:'medium',output_format:'png'})}),payload=await response.json().catch(()=>({}));if(!response.ok)throw new Error(payload.error?.message||`Image generation returned ${response.status}.`);const base64=payload.data?.[0]?.b64_json;if(!base64)throw new Error('Image generation returned no image.');return{data:`data:image/png;base64,${base64}`,buffer:Buffer.from(base64,'base64')}}
async function mapLimited(items,limit,worker){const results=new Array(items.length);let cursor=0;await Promise.all(Array.from({length:Math.min(limit,items.length)},async()=>{while(cursor<items.length){const index=cursor++;results[index]=await worker(items[index],index)}}));return results}
function devotionSpecs(notes={}){return values(notes.sevenDayFormationPlan).slice(0,7).map((day,index)=>{const paragraphs=[...values(day?.paragraphs),...values(day?.description)].map(clean).filter(Boolean),steps=values(day?.steps).map(clean).filter(Boolean),title=clean(day?.title)||`Day ${index+1}`,scripture=clean(day?.scripture||day?.reference);return{index:index+1,title,visual:`Create the coordinated devotional image for ${title} from the sermon “${clean(notes.documentTitle||notes.title)}”. Scripture focus: ${scripture||'use the sermon Scripture foundation'}. Devotional emphasis: ${paragraphs.join(' ')} Practice: ${steps.join(' ')}. Create one concrete, believable theological visual metaphor that reinforces this exact day of formation. Leave calm negative space through the center-left so translucent devotional text can sit over the photograph. ${PREMIUM}`}})}
export async function buildSermonSlides(notes,source,onProgress=()=>{}){
 const specs=buildSermonSlideSpecs(notes,source),dSpecs=devotionSpecs(notes),total=specs.length+dSpecs.length;let completed=0
 const generated=await mapLimited(specs,3,async(spec,index)=>{const image=await generateImage(spec.visual);completed++;await onProgress({completed,total});return{...image,index:index+1,title:clean(spec.title)||`Section ${index+1}`,kind:spec.kind,visual:spec.visual}})
 const devotionAssets=await mapLimited(dSpecs,3,async(spec,index)=>{const image=await generateImage(spec.visual);completed++;await onProgress({completed,total});return{...image,index:index+1,title:`Devotion ${index+1} - ${spec.title}`,kind:'devotion',visual:spec.visual}})
 const pptx=new pptxgen();pptx.layout='LAYOUT_WIDE';pptx.author='Church Triumphant';pptx.subject='Sermon Teaching Slides';pptx.title=clean(notes.documentTitle||source.title||'Sermon Teaching Slides');pptx.company='Church Triumphant';pptx.lang='en-US';pptx.theme={headFontFace:'Times New Roman',bodyFontFace:'Times New Roman',lang:'en-US'}
 specs.forEach((spec,index)=>{const slide=pptx.addSlide();slide.background={color:'080706'};slide.addImage({data:generated[index].data,x:0,y:0,w:13.333,h:7.5});slide.addShape(pptx.ShapeType.rect,{x:0,y:0,w:13.333,h:7.5,line:{color:'080706',transparency:100},fill:{color:'080706',transparency:spec.kind==='title'?34:28}});slide.addShape(pptx.ShapeType.rect,{x:0,y:0,w:6.9,h:7.5,line:{color:'080706',transparency:100},fill:{color:'080706',transparency:18}});if(spec.eyebrow)slide.addText(spec.eyebrow,{x:.72,y:.68,w:5.8,h:.3,fontFace:'Times New Roman',fontSize:12,bold:true,color:'D6B775',charSpacing:2.2,margin:0,fit:'shrink'});slide.addText(spec.title,{x:.72,y:spec.kind==='title'?3.65:2.35,w:6.1,h:spec.kind==='title'?1.55:1.7,fontFace:'Times New Roman',fontSize:spec.kind==='title'?34:29,bold:true,color:'FFFFFF',margin:0,fit:'shrink',valign:'mid'});if(spec.body)slide.addText(spec.body,{x:.75,y:spec.kind==='title'?5.35:4.25,w:5.75,h:1.2,fontFace:'Times New Roman',fontSize:17,color:'F1EDE4',margin:0,fit:'shrink'});slide.addShape(pptx.ShapeType.line,{x:.73,y:7.05,w:2,h:0,line:{color:'C5A46D',width:1.2}});slide.addText('CHURCH TRIUMPHANT',{x:.73,y:7.12,w:3.5,h:.18,fontFace:'Times New Roman',fontSize:8,bold:true,color:'C5A46D',charSpacing:1.8,margin:0});if(typeof slide.addNotes==='function')slide.addNotes([spec.notes||spec.body||spec.title])})
 return{buffer:await pptx.write({outputType:'nodebuffer'}),slideCount:specs.length,assets:generated.map(({data,...asset})=>asset),devotionAssets:devotionAssets.map(({data,...asset})=>asset)}
}
