import { readFile } from 'node:fs/promises'
import pptxgen from 'pptxgenjs'
import { buildSermonSlideSpecs, sermonSlidesFileName } from './sermon-slide-model.mjs'
import { SERMON_CHARACTER_IDENTITY_PROMPT, sermonCharacterReferenceFor } from './sermon-character-references.mjs'
export { buildSermonSlideSpecs, sermonSlidesFileName }
const clean=value=>String(value||'').replace(/\s+/g,' ').trim(),values=value=>Array.isArray(value)?value.filter(Boolean):value?[value]:[]
const PREMIUM='Church Triumphant luxury sermon-series visual language: ultra-photorealistic cinematic editorial photography, dramatic black and deep-navy shadow structure, warm antique-gold and ivory highlights, golden-hour or motivated theatrical light, rich authentic textures, sophisticated high-contrast composition, premium ministry campaign art direction, symbolic imagery drawn directly from the sermon metaphor, 8K-quality realism, theologically respectful Christian visual storytelling, no generic stock-photo feeling, no words, no lettering, no logos, wide 16:9 composition with intentional negative space for elegant serif teaching typography.'
function assertGeneratedPng(buffer){const bytes=Buffer.from(buffer||[]);const signature=[0x89,0x50,0x4e,0x47,0x0d,0x0a,0x1a,0x0a];if(bytes.length<signature.length||!signature.every((value,index)=>bytes[index]===value))throw new Error('Sermon visual generation returned an unsupported image format. Brevity accepts generated PNG assets only.');return bytes}
async function imageResponse(response){const payload=await response.json().catch(()=>({}));if(!response.ok)throw new Error(payload.error?.message||`Image generation returned ${response.status}.`);const base64=payload.data?.[0]?.b64_json;if(!base64)throw new Error('Image generation returned no image.');const buffer=assertGeneratedPng(Buffer.from(base64,'base64'));return{data:`data:image/png;base64,${buffer.toString('base64')}`,buffer}}
async function generateImage(prompt,reference=null){
 const model=process.env.BREVITY_IMAGE_MODEL||'gpt-image-2'
 if(reference){
  const bytes=await readFile(reference.url)
  const form=new FormData()
  form.append('model',model)
  form.append('image[]',new Blob([bytes],{type:reference.mimeType}),reference.fileName)
  form.append('prompt',`${prompt} ${SERMON_CHARACTER_IDENTITY_PROMPT}`)
  form.append('size','1536x1024')
  form.append('quality','medium')
  form.append('output_format','png')
  const response=await fetch('https://api.openai.com/v1/images/edits',{method:'POST',headers:{authorization:`Bearer ${process.env.OPENAI_API_KEY}`},body:form})
  return imageResponse(response)
 }
 const response=await fetch('https://api.openai.com/v1/images/generations',{method:'POST',headers:{authorization:`Bearer ${process.env.OPENAI_API_KEY}`,'content-type':'application/json'},body:JSON.stringify({model,prompt,size:'1536x1024',quality:'medium',output_format:'png'})})
 return imageResponse(response)
}
async function mapLimited(items,limit,worker){const results=new Array(items.length);let cursor=0;await Promise.all(Array.from({length:Math.min(limit,items.length)},async()=>{while(cursor<items.length){const index=cursor++;results[index]=await worker(items[index],index)}}));return results}
function devotionSpecs(notes={}){return values(notes.sevenDayFormationPlan).slice(0,7).map((day,index)=>{const paragraphs=[...values(day?.paragraphs),...values(day?.description)].map(clean).filter(Boolean),steps=values(day?.steps).map(clean).filter(Boolean),title=clean(day?.title)||`Day ${index+1}`,scripture=clean(day?.scripture||day?.reference);return{index:index+1,title,visual:`Create the coordinated Day ${index+1} devotional hero image for “${title}” from the sermon “${clean(notes.documentTitle||notes.title)}”. Scripture focus: ${scripture||'use the sermon Scripture foundation'}. Devotional emphasis: ${paragraphs.join(' ')} Practice: ${steps.join(' ')}. Make one specific visual metaphor that a household can recognize instantly as today’s formation assignment. It must feel like the same premium visual campaign as the sermon slide deck while remaining distinct for this day. Leave calm negative space for the app to display the devotion title and Scripture. ${PREMIUM}`}})}
export async function buildSermonSlides(notes,source,onProgress=()=>{}){
 const specs=buildSermonSlideSpecs(notes,source),dSpecs=devotionSpecs(notes),total=specs.length+dSpecs.length;let completed=0
 const identitySeed=source.sourceHash||`${clean(source.sermonDate)}:${clean(notes.documentTitle||notes.title||source.title)}`
 const generated=await mapLimited(specs,3,async(spec,index)=>{const reference=sermonCharacterReferenceFor(identitySeed,index);const image=await generateImage(`${spec.visual} ${PREMIUM}`,reference);completed++;await onProgress({completed,total});return{...image,index:index+1,title:clean(spec.title)||`Section ${index+1}`,kind:spec.kind,visual:spec.visual,characterReferenceId:reference?.id||''}})
 const devotionAssets=await mapLimited(dSpecs,3,async(spec,index)=>{const reference=sermonCharacterReferenceFor(identitySeed,specs.length+index);const image=await generateImage(spec.visual,reference);completed++;await onProgress({completed,total});return{...image,index:index+1,title:`Devotion ${index+1} - ${spec.title}`,kind:'devotion',visual:spec.visual,characterReferenceId:reference?.id||''}})
 const pptx=new pptxgen();pptx.layout='LAYOUT_WIDE';pptx.author='Church Triumphant';pptx.subject='Sermon Teaching Slides';pptx.title=clean(notes.documentTitle||source.title||'Sermon Teaching Slides');pptx.company='Church Triumphant';pptx.lang='en-US';pptx.theme={headFontFace:'Times New Roman',bodyFontFace:'Times New Roman',lang:'en-US'}
 specs.forEach((spec,index)=>{const slide=pptx.addSlide();slide.background={color:'050505'};slide.addImage({data:generated[index].data,x:0,y:0,w:13.333,h:7.5});slide.addShape(pptx.ShapeType.rect,{x:0,y:0,w:13.333,h:7.5,line:{color:'050505',transparency:100},fill:{color:'050505',transparency:spec.kind==='title'?52:62}});slide.addShape(pptx.ShapeType.rect,{x:.48,y:.48,w:7.25,h:6.55,line:{color:'C5A46D',transparency:70,width:1},fill:{color:'050505',transparency:24},radius:.08});if(spec.eyebrow)slide.addText(spec.eyebrow,{x:.76,y:.82,w:6.3,h:.35,fontFace:'Times New Roman',fontSize:12,bold:true,color:'D9BD8B',charSpacing:2.4,margin:0,fit:'shrink'});slide.addText(spec.title,{x:.76,y:spec.kind==='title'?2.25:1.72,w:6.25,h:spec.kind==='title'?2.25:2.15,fontFace:'Times New Roman',fontSize:spec.kind==='title'?38:30,bold:true,color:spec.kind==='title'?'E6C47D':'F7F6F2',margin:0,fit:'shrink',valign:'mid'});if(spec.body)slide.addText(spec.body,{x:.8,y:spec.kind==='title'?4.72:4.22,w:5.95,h:1.45,fontFace:'Times New Roman',fontSize:16.5,color:'F1EDE4',margin:0,fit:'shrink'});slide.addShape(pptx.ShapeType.line,{x:.78,y:6.62,w:2.2,h:0,line:{color:'C5A46D',width:1.3}});slide.addText('CHURCH TRIUMPHANT',{x:.78,y:6.72,w:3.8,h:.22,fontFace:'Times New Roman',fontSize:8.5,bold:true,color:'D9BD8B',charSpacing:1.9,margin:0});slide.addText(clean(notes.preacherTeacher||source.preacherTeacher||''),{x:4.5,y:6.72,w:2.4,h:.22,fontFace:'Times New Roman',fontSize:8,color:'D8D5CE',charSpacing:1.2,margin:0,align:'right'});if(typeof slide.addNotes==='function')slide.addNotes([spec.notes||spec.body||spec.title])})
 return{buffer:await pptx.write({outputType:'nodebuffer'}),slideCount:specs.length,assets:generated.map(({data,...asset})=>asset),devotionAssets:devotionAssets.map(({data,...asset})=>asset)}
}
