import { useEffect, useMemo, useState } from 'react'
import { importSermonFields } from '../../netlify/lib/sermon-workspace-import.mjs'
import './SermonWorkspace.css'

const endpoint='/.netlify/functions/ministry-sermon-workspace'
const assetTypes=[
  ['photography','Photography','ti-camera','Shot list, reference links, and selected images'],
  ['slides','Slides & Visuals','ti-presentation','Presentation plan and visual brief'],
  ['quotes','Mic Drops','ti-quote','Suggested or verified quotations'],
  ['hooks','Facebook Hooks','ti-bolt','Opening lines for social posts'],
  ['facebook','Facebook Posts','ti-brand-facebook','One complete draft caption per sermon core idea'],
  ['reels','Reels','ti-video','Clips, scripts, and timestamps'],
  ['stories','Stories','ti-photo','Story sequence and captions'],
  ['podcast','Podcast','ti-microphone','Episode notes and audio link'],
  ['twin','AI Twin','ti-user-circle','Approved script and production brief'],
  ['ai-video','AI Videos','ti-movie','Storyboard and production links'],
]
const tabs=['Message','Builder Review','Notes','Visuals','Social','Recording','Published']
const newId=()=>globalThis.crypto?.randomUUID?.() || `id_${Date.now()}_${Math.random().toString(36).slice(2)}`
const blank={schemaVersion:1,revision:0,series:[],sermons:[]}
const freshSermon=(seriesId,member)=>({id:newId(),seriesId,title:'Untitled Sermon',date:new Date().toISOString().slice(0,10),serviceType:'Sunday',status:'Draft',version:1,bigIdea:'',scripture:'',outline:'',sourceNotes:'',builderReview:'',approvedNotes:'',recordingUrl:'',transcript:'',publishedUrl:'',assets:[],createdBy:member,updatedAt:new Date().toISOString()})
const assetTab=type=>['photography','slides'].includes(type)?'Visuals':['quotes','hooks','facebook','reels','stories'].includes(type)?'Social':type==='podcast'?'Recording':'Published'

export default function SermonWorkspace({currentMember,role}) {
  const [workspace,setWorkspace]=useState(blank)
  const [selectedId,setSelectedId]=useState(null)
  const [tab,setTab]=useState('Message')
  const [assetId,setAssetId]=useState(null)
  const [viewedType,setViewedType]=useState(null)
  const [state,setState]=useState('loading')
  const [message,setMessage]=useState('')
  const [dirty,setDirty]=useState(false)
  const [showSeries,setShowSeries]=useState(false)
  const [seriesTitle,setSeriesTitle]=useState('')
  const [newSermonSeries,setNewSermonSeries]=useState('')
  const [importOpen,setImportOpen]=useState(false)
  const [importSource,setImportSource]=useState('vault')
  const [vaultMember,setVaultMember]=useState(currentMember)
  const [vaultRecords,setVaultRecords]=useState([])
  const [vaultId,setVaultId]=useState('')
  const [importText,setImportText]=useState('')
  const [importFile,setImportFile]=useState(null)
  const [importBusy,setImportBusy]=useState(false)
  const [importError,setImportError]=useState('')
  const [importPreview,setImportPreview]=useState(null)
  const [generation,setGeneration]=useState(null)
  const [cover,setCover]=useState(null)
  const [postImages,setPostImages]=useState({})
  const [identityRefs,setIdentityRefs]=useState({})
  const [identityMessage,setIdentityMessage]=useState('')

  const load=async()=>{
    setState('loading');setMessage('')
    try { const response=await fetch(endpoint,{credentials:'include'});const data=await response.json();if(!response.ok)throw Error(data.error||'Could not load sermons.');setWorkspace(data);setSelectedId(id=>data.sermons.some(s=>s.id===id)?id:data.sermons[0]?.id||null);setDirty(false);setState('ready') }
    catch(error){setState('error');setMessage(error.message)}
  }
  useEffect(()=>{load()},[])
  useEffect(()=>{if(!dirty)return;const warn=event=>{event.preventDefault();event.returnValue=''};window.addEventListener('beforeunload',warn);return()=>window.removeEventListener('beforeunload',warn)},[dirty])
  const packageEndpoint='/.netlify/functions/sermon-workspace-package'
  const coverEndpoint='/.netlify/functions/sermon-cover'
  const requestCover=async(sermonId,regenerate=false)=>{const response=await fetch(coverEndpoint,{method:'POST',credentials:'include',headers:{'content-type':'application/json'},body:JSON.stringify({sermonId,regenerate})});const data=await response.json();if(!response.ok)throw Error(data.error||'Could not create cover image.');setCover(data);return data}
  useEffect(()=>{
    if(!selectedId||dirty||state!=='ready')return
    const selected=workspace.sermons.find(item=>item.id===selectedId)
    if(!selected)return
    let cancelled=false,busy=false
    setCover(null)
    const check=async()=>{if(cancelled||busy)return;busy=true;try{const response=await fetch(`${coverEndpoint}?sermonId=${encodeURIComponent(selectedId)}`,{credentials:'include'}),status=await response.json();if(!response.ok)throw Error(status.error||'Could not check the cover.');if(cancelled)return;setCover(status);if(status.state==='not-started'&&selected.title!=='Untitled Sermon'&&String(selected.outline||selected.bigIdea||'').trim())await requestCover(selectedId)}catch(error){if(!cancelled)setCover({state:'error',error:error.message})}finally{busy=false}}
    check();const timer=setInterval(check,5000);return()=>{cancelled=true;clearInterval(timer)}
  },[selectedId,workspace.revision,dirty,state])
  const startGeneration=async(id,revision)=>{const response=await fetch(packageEndpoint,{method:'POST',credentials:'include',headers:{'content-type':'application/json'},body:JSON.stringify({action:'start',sermonId:id,baseRevision:revision})});const data=await response.json();if(!response.ok)throw Error(data.error||'Could not start sermon generation.');setGeneration(data);return data}
  useEffect(()=>{
    if(!selectedId||dirty||state!=='ready')return
    const selected=workspace.sermons.find(item=>item.id===selectedId)
    if(!selected)return
    let cancelled=false,busy=false
    const check=async()=>{if(busy||cancelled)return;busy=true;try{
      const response=await fetch(`${packageEndpoint}?sermonId=${encodeURIComponent(selectedId)}`,{credentials:'include'}),status=await response.json();if(!response.ok)throw Error(status.error||'Could not check generation.');if(cancelled)return
      if(status.state==='not-started'&&String(selected.outline||'').trim().length>=80){await startGeneration(selectedId,workspace.revision);return}
      setGeneration(status)
      if(status.state==='ready'&&selected.generationJobId!==status.id){const applied=await fetch(packageEndpoint,{method:'POST',credentials:'include',headers:{'content-type':'application/json'},body:JSON.stringify({action:'apply',sermonId:selectedId,jobId:status.id,baseRevision:workspace.revision})});const result=await applied.json();if(!applied.ok)throw Error(result.error||'Could not save generated materials.');if(!cancelled){setWorkspace(result.workspace);setMessage('Draft notes, mic drops, and slides are ready for review.')}}
    }catch(error){if(!cancelled)setGeneration({state:'error',error:error.message})}finally{busy=false}}
    check();const timer=setInterval(check,5000);return()=>{cancelled=true;clearInterval(timer)}
  },[selectedId,workspace.revision,dirty,state])
  const sermon=workspace.sermons.find(item=>item.id===selectedId)
  useEffect(()=>{
    if(!selectedId||dirty||state!=='ready')return
    const posts=workspace.sermons.find(item=>item.id===selectedId)?.assets?.filter(item=>item.type==='facebook')||[]
    if(!posts.length){setPostImages({});return}
    let cancelled=false,busy=false
    const check=async()=>{if(cancelled||busy)return;busy=true;try{
      const statuses={}
      for(const post of posts){
        const params=new URLSearchParams({sermonId:selectedId,postId:post.id})
        const response=await fetch(`/.netlify/functions/sermon-post-image?${params}`,{credentials:'include'})
        const result=await response.json();statuses[post.id]=response.ok?result:{state:'error',error:result.error||'Photography unavailable.'}
      }
      if(cancelled)return
      setPostImages(statuses)
      const active=posts.filter(post=>['queued','generating'].includes(statuses[post.id]?.state)).length
      const next=active<2?posts.find(post=>statuses[post.id]?.state==='not-started'):null
      if(next){const response=await fetch('/.netlify/functions/sermon-post-image',{method:'POST',credentials:'include',headers:{'content-type':'application/json'},body:JSON.stringify({sermonId:selectedId,postId:next.id})});const result=await response.json();if(!cancelled)setPostImages(current=>({...current,[next.id]:response.ok?result:{state:'error',error:result.error||'Could not generate photography.'}}))}
    }catch(error){if(!cancelled)setPostImages({error:{state:'error',error:error.message}})}finally{busy=false}}
    setPostImages({});check();const timer=setInterval(check,6000);return()=>{cancelled=true;clearInterval(timer)}
  },[selectedId,workspace.revision,dirty,state])
  const series=workspace.series.find(item=>item.id===sermon?.seriesId)
  const asset=sermon?.assets.find(item=>item.id===assetId)
  const sorted=useMemo(()=>[...workspace.sermons].sort((a,b)=>(b.date||'').localeCompare(a.date||'')),[workspace.sermons])
  const change=updater=>{setWorkspace(current=>updater(current));setDirty(true);setMessage('')}
  const editSermon=patch=>change(current=>({...current,sermons:current.sermons.map(item=>item.id===selectedId?{...item,...patch,updatedAt:new Date().toISOString()}:item)}))
  const editAsset=patch=>change(current=>({...current,sermons:current.sermons.map(item=>item.id===selectedId?{...item,assets:item.assets.map(a=>a.id===assetId?{...a,...patch}:a)}:item)}))
  const addSeries=()=>{const title=seriesTitle.trim();if(!title)return;const id=newId();change(current=>({...current,series:[...current.series,{id,title,description:'',createdAt:new Date().toISOString()}]}));setNewSermonSeries(id);setSeriesTitle('');setShowSeries(false)}
  const addSermon=()=>{const item=freshSermon(newSermonSeries,currentMember);change(current=>({...current,sermons:[item,...current.sermons]}));setSelectedId(item.id);setAssetId(null);setViewedType(null);setTab('Message')}
  const addAsset=type=>{const id=newId();const item={id,type,title:assetTypes.find(a=>a[0]===type)?.[1]||type,content:'',status:'Draft',source:'Approved notes',sourceVersion:sermon.version||1,updatedAt:new Date().toISOString()};editSermon({assets:[...sermon.assets,item]});setAssetId(id);setTab(assetTab(type))}
  const save=async()=>{
    setState('saving');setMessage('')
    try {const response=await fetch(endpoint,{method:'PUT',credentials:'include',headers:{'content-type':'application/json'},body:JSON.stringify({baseRevision:workspace.revision,series:workspace.series,sermons:workspace.sermons})});const data=await response.json();if(!response.ok)throw Error(data.error||'Could not save.');setWorkspace(data);setDirty(false);setState('ready');setMessage('Saved for the ministry team. Sermon materials will generate when the manuscript has at least 80 characters.')}
    catch(error){setState('error');setMessage(error.message)}
  }
  const getJSON=async url=>{const response=await fetch(url,{credentials:'include'});const data=await response.json();if(!response.ok)throw Error(data.error||'Could not load the sermon.');return data}
  const loadVault=async member=>{setImportBusy(true);setImportError('');setVaultId('');setImportPreview(null);try{const data=await getJSON(`${endpoint}?source=vault&member=${encodeURIComponent(member)}`);setVaultRecords(data.records||[])}catch(error){setImportError(error.message)}finally{setImportBusy(false)}}
  const openImport=()=>{setImportOpen(true);setImportError('');setImportPreview(null);setImportSource('vault');loadVault(vaultMember)}
  const previewVault=async id=>{setVaultId(id);setImportPreview(null);if(!id)return;setImportBusy(true);setImportError('');try{const data=await getJSON(`${endpoint}?source=vault&member=${encodeURIComponent(vaultMember)}&recordId=${encodeURIComponent(id)}`);setImportPreview(importSermonFields({sermon:data.record.sermon,notes:data.record.notes,sourceName:'Apostolic Builder Vault'}))}catch(error){setImportError(error.message)}finally{setImportBusy(false)}}
  const previewFile=async file=>{setImportFile(file||null);setImportPreview(null);if(!file)return;setImportBusy(true);setImportError('');try{const ext=file.name.split('.').pop().toLowerCase();if(!['txt','json','docx','pdf'].includes(ext))throw Error('Choose a .txt, .json, .docx, or searchable .pdf file.');if(file.size>4_500_000)throw Error('Choose a file smaller than 4.5 MB.');let rawText='',builder=null;if(ext==='txt')rawText=await file.text();else if(ext==='json'){const payload=JSON.parse(await file.text());builder=payload.sermon||payload;if(typeof builder!=='object'||Array.isArray(builder))throw Error('This JSON file does not contain a sermon.')}else{const data=await new Promise((resolve,reject)=>{const reader=new FileReader();reader.onload=()=>resolve(String(reader.result).split(',')[1]);reader.onerror=()=>reject(Error('Could not read the file.'));reader.readAsDataURL(file)});const response=await fetch('/.netlify/functions/sermon-notes-import',{method:'POST',credentials:'include',headers:{'content-type':'application/json'},body:JSON.stringify({name:file.name,data})});const result=await response.json();if(!response.ok)throw Error(result.error||'Could not read the document.');rawText=result.text}setImportPreview(importSermonFields({sermon:builder,notes:ext==='json'?JSON.parse(await file.text()).notes:null,rawText,sourceName:file.name}));setImportText(rawText)}catch(error){setImportError(error.message)}finally{setImportBusy(false)}}
  const previewPaste=()=>{try{setImportError('');setImportPreview(importSermonFields({rawText:importText,sourceName:'Pasted text'}))}catch(error){setImportPreview(null);setImportError(error.message)}}
  const commitImport=async()=>{if(!importPreview||dirty)return;setImportBusy(true);setImportError('');try{let payload={baseRevision:workspace.revision,source:importSource};if(importSource==='vault')payload={...payload,vaultMember,recordId:vaultId};else if(importSource==='paste')payload.rawText=importText;else{payload.sourceName=importFile.name;if(importFile.name.toLowerCase().endsWith('.json')){const parsed=JSON.parse(await importFile.text());payload.sermon=parsed.sermon||parsed;payload.notes=parsed.notes||null}else payload.rawText=importText}const response=await fetch(endpoint,{method:'POST',credentials:'include',headers:{'content-type':'application/json'},body:JSON.stringify(payload)});const data=await response.json();if(!response.ok)throw Error(data.error||'Could not import the sermon.');setWorkspace(data.workspace);setSelectedId(data.sermonId);setTab('Message');setAssetId(null);setDirty(false);setState('ready');setMessage(data.alreadyImported?'This Vault sermon is already in the Workspace.':'Sermon imported into the Workspace.');setImportOpen(false)}catch(error){setImportError(error.message)}finally{setImportBusy(false)}}
  const checklist=['notes','slides','photography','facebook','reels','podcast'].map(type=>{
    const matching=type==='notes'?null:sermon?.assets.find(a=>a.type===type)
    return {type,label:type==='notes'?'Notes':assetTypes.find(a=>a[0]===type)?.[1],status:type==='notes'?(sermon?.approvedNotes?'Complete':sermon?.generatedNotes?'Draft':'Pending'):(matching?.status||'Pending')}
  })
  const completed=checklist.filter(item=>['Approved','Published','Complete'].includes(item.status)).length
  const field=(label,key,rows=0,placeholder='')=><label className="sw-field"><span>{label}</span>{rows?<textarea rows={rows} value={sermon[key]||''} placeholder={placeholder} onChange={event=>editSermon({[key]:event.target.value})}/>:<input value={sermon[key]||''} placeholder={placeholder} onChange={event=>editSermon({[key]:event.target.value})}/>}</label>
  const assetThumb=(type,icon)=><div className={`sw-asset-thumb sw-thumb-${type}`}>{['slides','facebook','reels','stories','ai-video'].includes(type)&&cover?.state==='ready'&&cover.image?<img src={cover.image} alt=""/>:<i className={`ti ${icon}`} aria-hidden="true"/>}</div>
  const assetLinks=(items,type,limit=Infinity)=><div className="sw-asset-items">{items.slice(0,limit).map(a=><button type="button" key={a.id} className="sw-asset-link" onClick={()=>{setViewedType(null);setTab(assetTab(type));setAssetId(a.id)}}><span className="sw-asset-name">{a.title}</span><span className="sw-asset-status">{a.status}</span></button>)}</div>
  const photoPosts=sermon?.assets.filter(a=>a.type==='facebook')||[]
  useEffect(()=>{if(viewedType!=='photography'||role!=='admin')return;fetch('/.netlify/functions/sermon-identities',{credentials:'include'}).then(response=>response.json()).then(data=>setIdentityRefs(Object.fromEntries((data.members||[]).map(item=>[item.member,item.uploaded])))).catch(()=>setIdentityMessage('Could not load identity references.'))},[viewedType,role])
  const uploadIdentity=async(member,file)=>{if(!file)return;setIdentityMessage(`Uploading ${member}…`);try{if(file.type!=='image/jpeg'||file.size>6_000_000)throw Error('Choose a JPEG smaller than 6 MB.');const base64=await new Promise((resolve,reject)=>{const reader=new FileReader();reader.onload=()=>resolve(String(reader.result).split(',')[1]);reader.onerror=()=>reject(Error('Could not read the photograph.'));reader.readAsDataURL(file)});const response=await fetch('/.netlify/functions/sermon-identities',{method:'PUT',credentials:'include',headers:{'content-type':'application/json'},body:JSON.stringify({member,imageBase64:base64})});const result=await response.json();if(!response.ok)throw Error(result.error||'Could not save the reference.');setIdentityRefs(current=>({...current,[member]:true}));setIdentityMessage(`${member}'s identity reference was saved privately.`)}catch(error){setIdentityMessage(error.message)}}
  const photoUrl=post=>`/.netlify/functions/sermon-post-image?${new URLSearchParams({sermonId:sermon.id,postId:post.id,image:'1',version:postImages[post.id]?.assetId||''})}`
  const photoPreview=(post)=><div className="sw-photo-item" key={post.id}>{postImages[post.id]?.state==='ready'?<img src={photoUrl(post)} alt={`Photograph for ${post.title}`} loading="lazy"/>:<div className="sw-photo-pending"><i className="ti ti-camera"/>{postImages[post.id]?.state==='error'?'Image unavailable':postImages[post.id]?.state==='generating'?'Creating image…':'Image queued'}</div>}<strong>{post.title}</strong><label className="sw-field"><span>Person in this photograph</span><select value={postImages[post.id]?.subject||'none'} onChange={async event=>{const subject=event.target.value;const response=await fetch('/.netlify/functions/sermon-post-image',{method:'POST',credentials:'include',headers:{'content-type':'application/json'},body:JSON.stringify({sermonId:sermon.id,postId:post.id,subject,regenerate:true})});const result=await response.json();setPostImages(current=>({...current,[post.id]:response.ok?result:{state:'error',error:result.error||'Could not create image.'}}))}} disabled={dirty}>{[['none','No person'],['Larry','Larry'],['Lorenzo','Lorenzo'],['Javin','Javin'],['Isaiah','Isaiah'],['Terica','Terica'],['Nyla','Nyla']].map(([value,label])=><option key={value} value={value}>{label}</option>)}</select></label>{postImages[post.id]?.state==='error'&&<small role="alert">{postImages[post.id].error}</small>}<button type="button" className="sw-view-all" disabled={dirty} onClick={async()=>{const response=await fetch('/.netlify/functions/sermon-post-image',{method:'POST',credentials:'include',headers:{'content-type':'application/json'},body:JSON.stringify({sermonId:sermon.id,postId:post.id,subject:postImages[post.id]?.subject||'none',regenerate:true})});const result=await response.json();setPostImages(current=>({...current,[post.id]:response.ok?result:{state:'error',error:result.error||'Could not retry image.'}}))}}>{postImages[post.id]?.state==='ready'?'Generate another':'Retry image'}</button></div>
  const assetCard=(type,label,icon,description)=>{if(type==='photography')return <article className="sw-asset-card" key={type}>{photoPosts[0]&&postImages[photoPosts[0].id]?.state==='ready'?<div className="sw-asset-thumb"><img src={photoUrl(photoPosts[0])} alt=""/></div>:assetThumb(type,icon)}<h4><i className={`ti ${icon}`}/> {label}</h4><small>{photoPosts.length} Facebook post image{photoPosts.length===1?'':'s'}</small><p className="sw-photo-summary">Photographs are generated from each saved post and its sermon theme.</p><button type="button" className="sw-card-action" onClick={()=>setViewedType(type)}>View photography</button></article>;const items=sermon.assets.filter(a=>a.type===type);return <article className="sw-asset-card" key={type}>{assetThumb(type,icon)}<h4><i className={`ti ${icon}`}/> {label}</h4>{description&&<p>{description}</p>}<small>{items.length} item{items.length===1?'':'s'}</small>{assetLinks(items,type,2)}{items.length>2&&<button type="button" className="sw-view-all" onClick={()=>setViewedType(type)}>View all {items.length} {label.toLowerCase()}</button>}<button type="button" className="sw-card-action" onClick={()=>addAsset(type)}>+ Add {label}</button></article>}

  return <div className="sw-shell">
    <header className="sw-top"><div><p className="sw-kicker">MINISTRY &amp; FELLOWSHIP / SERMON WORKSPACE</p><h1>Sermon Workspace</h1><p>One place for the message and everything produced from it.</p></div><div className="sw-top-actions"><button type="button" className="sw-quiet" onClick={load} disabled={dirty||state==='saving'}>Refresh</button><button type="button" className="sw-primary" onClick={save} disabled={!dirty||state==='saving'}>{state==='saving'?'Saving…':dirty?'Save changes':'Saved'}</button></div></header>
    {message&&<p className={`sw-message ${state==='error'?'sw-error':''}`} role="status">{message}{state==='error'&&dirty&&<span> Your edits remain on this screen. Copy them before refreshing if another member has saved changes.</span>}</p>}
    {dirty&&<p className="sw-unsaved" role="status">Unsaved changes · Save before leaving this page.</p>}
    <div className="sw-layout"><aside className="sw-list"><div className="sw-list-header"><h2>Sermons</h2><button type="button" onClick={addSermon} disabled={state==='loading'}>+ New</button></div><button type="button" className="sw-secondary sw-import-launch" onClick={openImport} disabled={dirty||state!=='ready'}>Import sermon</button><label className="sw-field"><span>Series for new sermon</span><select value={newSermonSeries} onChange={e=>setNewSermonSeries(e.target.value)}><option value="">Standalone sermon</option>{workspace.series.map(item=><option key={item.id} value={item.id}>{item.title}</option>)}</select></label><button type="button" className="sw-text-button" onClick={()=>setShowSeries(!showSeries)}>+ Create series</button>{showSeries&&<div className="sw-inline"><input aria-label="Series title" value={seriesTitle} onChange={e=>setSeriesTitle(e.target.value)} placeholder="Series title"/><button type="button" onClick={addSeries}>Add</button></div>}{sorted.map(item=><button type="button" key={item.id} className={`sw-sermon-link ${selectedId===item.id?'active':''}`} onClick={()=>{setSelectedId(item.id);setTab('Message');setAssetId(null);setViewedType(null)}}><small>{workspace.series.find(s=>s.id===item.seriesId)?.title||'Standalone'} · {item.date||'No date'}</small><strong>{item.title}</strong><span>{item.status} · v{item.version||1}</span></button>)}{state==='loading'&&<p className="sw-muted">Loading sermons…</p>}{state==='ready'&&!sorted.length&&<p className="sw-muted">Create a series or your first sermon to begin.</p>}</aside>
    <main className="sw-main">{sermon?<><div className="sw-sermon-heading"><div className="sw-cover-frame">{cover?.state==='ready'&&cover.image?<img src={cover.image} alt={`Photographic cover for ${sermon.title}`}/>:<div className="sw-cover-placeholder"><i className={`ti ${cover?.state==='error'?'ti-photo-off':'ti-photo-spark'}`}/><span>{['queued','generating'].includes(cover?.state)?'Creating cover…':'SERMON COVER'}</span></div>}</div><div className="sw-sermon-title"><p className="sw-kicker">{series?.title||'STANDALONE SERMON'}</p><h2>{sermon.title}</h2><p>{sermon.serviceType} · {sermon.date||'Date not set'} · <span className="sw-gold">{sermon.status} v{sermon.version||1}</span></p>{['ready','error'].includes(cover?.state)?<button type="button" className="sw-cover-action" disabled={dirty} onClick={()=>requestCover(sermon.id,true).catch(error=>setCover({state:'error',error:error.message}))}>{cover.state==='ready'?'Generate another cover':'Retry cover image'}</button>:<span className="sw-cover-hint">{['queued','generating'].includes(cover?.state)?'Creating a photographic cover from this sermon…':'A cover will generate after you save a title and theme.'}</span>}{cover?.state==='error'&&<small className="sw-cover-error">{cover.error}</small>}</div><label className="sw-status">Status<select value={sermon.status} onChange={e=>editSermon({status:e.target.value})}>{['Draft','In review','Approved','Preached','Published'].map(s=><option key={s}>{s}</option>)}</select></label></div>
      <section className="sw-generation" aria-live="polite"><div><strong>Sermon production</strong><p>{generation?.sermonId===sermon.id&&['queued','processing'].includes(generation.state)?'Brevity is drafting teaching notes, source-verified mic drops, and a slide deck. You can leave this page and return.':generation?.sermonId===sermon.id&&generation.state==='ready'?'Draft notes, mic drops, and slides are ready for review.':generation?.state==='error'?generation.error:'Save a manuscript of at least 80 characters to start generation.'}</p></div><button type="button" className="sw-secondary" disabled={dirty||String(sermon.outline||'').trim().length<80||['queued','processing'].includes(generation?.state)&&generation?.sermonId===sermon.id} onClick={()=>startGeneration(sermon.id,workspace.revision).catch(error=>setGeneration({state:'error',error:error.message}))}>{generation?.state==='error'?'Retry generation':'Generate materials'}</button></section>
      <nav className="sw-tabs" aria-label="Sermon production stages">{tabs.map((item,index)=><button type="button" key={item} className={tab===item?'active':''} onClick={()=>{setTab(item);setAssetId(null)}}><b>{index+1}</b>{item}</button>)}</nav>
      {asset?<section className="sw-panel"><button type="button" className="sw-text-button" onClick={()=>setAssetId(null)}>← Back to {tab}</button><div className="sw-row"><h3>{asset.title}</h3><select aria-label="Asset status" value={asset.status} onChange={e=>editAsset({status:e.target.value})}>{['Draft','In review','Approved','Published'].map(s=><option key={s}>{s}</option>)}</select></div><label className="sw-field"><span>Title</span><input value={asset.title} onChange={e=>editAsset({title:e.target.value})}/></label><label className="sw-field"><span>Source</span><select value={asset.source} onChange={e=>editAsset({source:e.target.value})}><option>Approved notes</option><option>Preached transcript</option><option>Original material</option></select></label><p className="sw-muted">Created from {asset.source.toLowerCase()} · sermon version {asset.sourceVersion}. Review attribution and accuracy before publishing.</p>{asset.type==='facebook'&&postImages[asset.id]?.state==='ready'&&<div className="sw-post-photo"><img src={photoUrl(asset)} alt={`Photograph for ${asset.title}`}/><button type="button" className="sw-text-button" onClick={()=>setViewedType('photography')}>Review photography</button></div>}{asset.type==='facebook'&&asset.sourceExcerpt&&<p className="sw-muted"><strong>Grounded in the sermon:</strong> “{asset.sourceExcerpt}”</p>}<label className="sw-field"><span>{asset.type==='facebook'?'Facebook caption draft':'Draft, brief, links, or production notes'}</span><textarea rows="12" value={asset.content} onChange={e=>editAsset({content:e.target.value,updatedAt:new Date().toISOString()})} placeholder="Add the content and production details here…"/></label></section>:<>
      {tab==='Message'&&<><div className="sw-columns"><section className="sw-panel sw-message-panel"><div className="sw-row"><h3>The message</h3><small>Source of truth · sermon v{sermon.version||1}</small></div><div className="sw-grid">{field('Sermon title','title')}{field('Scripture','scripture')}{field('Service type','serviceType')}<label className="sw-field"><span>Date</span><input type="date" value={sermon.date||''} onChange={e=>editSermon({date:e.target.value})}/></label></div>{field('Big idea','bigIdea',3,'The single governing truth of this message')}{field('Outline','outline',8,'Main movements and supporting passages')}{field('Ideas and source material','sourceNotes',6,'Paste ideas from Lorenzo’s conversations or other source material; preserve what he actually wrote.')}</section><aside className="sw-panel"><div className="sw-row"><h3><i className="ti ti-list-check sw-heading-icon"/> Production checklist</h3><small>{completed} of 6 complete</small></div>{checklist.map(item=><div className="sw-check" key={item.type}><i className={`ti ${['Approved','Published','Complete'].includes(item.status)?'ti-circle-check':'ti-circle'}`}/><span>{item.label}</span><em>{item.status}</em></div>)}<p className="sw-muted">Assets are linked to this sermon and carry their source version.</p></aside></div><section className="sw-panel sw-studio"><div className="sw-row"><h3>Content studio</h3><small>Create and manage all media from this sermon.</small></div><div className="sw-asset-grid">{assetTypes.filter(([type])=>['photography','slides','quotes','facebook','reels','podcast'].includes(type)).map(([type,label,icon])=>assetCard(type,label,icon))}</div></section></>}
      {tab==='Builder Review'&&<section className="sw-panel"><h3>Builder Review</h3><p className="sw-muted">Record suggestions and Lorenzo’s decisions here. The existing Apostolic Sermon Builder remains available as a separate tool in the Ministry menu.</p>{field('Review and decisions','builderReview',12,'Paste Builder feedback, then record what Lorenzo accepted, revised, or declined.')}{sermon.status==='Approved'&&<p className="sw-note">Approved version {sermon.version}. Revise the message and increase the version before treating new assets as approved.</p>}<button type="button" className="sw-secondary" onClick={()=>editSermon({version:(Number(sermon.version)||1)+1,status:'Draft'})}>Start next version</button></section>}
      {tab==='Notes'&&<section className="sw-panel"><h3>Generated teaching notes · Draft</h3><p className="sw-muted">Review the source, Scripture, and language before approving. Brevity never marks generated notes as approved.</p>{field('Teaching notes draft','generatedNotes',20,'Generate materials from a saved sermon manuscript.')}<button type="button" className="sw-secondary" disabled={!sermon.generatedNotes} onClick={()=>editSermon({approvedNotes:sermon.generatedNotes})}>Copy draft to approved notes</button><h3>Approved sermon notes</h3><p className="sw-muted">This is the reviewed manuscript or preaching outline that should govern pre-service assets.</p>{field('Notes','approvedNotes',20,'Paste or write Lorenzo’s approved notes here.')}</section>}
      {['Visuals','Social','Published'].includes(tab)&&<section className="sw-panel"><div className="sw-row"><div><h3>{tab==='Visuals'?'Visual studio':tab==='Social'?'Social content':'Published and AI media'}</h3><p className="sw-muted">{tab==='Social'?'Open each Facebook post to review its complete caption and source excerpt before publishing.':'Select an asset to write its brief, draft, link, and review status.'}</p></div></div>{tab==='Visuals'&&sermon.slideDeckUrl&&<p><a className="sw-secondary sw-download" href={sermon.slideDeckUrl}>Download draft slides (.pptx)</a></p>}{tab==='Published'&&field('Published sermon link','publishedUrl',0,'https://…')}<div className="sw-asset-grid">{assetTypes.filter(item=>assetTab(item[0])===tab).map(([type,label,icon,description])=>assetCard(type,label,icon,description))}</div></section>}
      {tab==='Recording'&&<section className="sw-panel"><h3>After the service</h3><p className="sw-muted">Keep what Lorenzo actually preached alongside the prepared notes. Check quotes and clips against this transcript.</p>{field('Recording link','recordingUrl',0,'https://…')}{field('Preached transcript','transcript',16,'Paste the service transcript with speaker labels and timestamps where available.')}{sermon.assets.filter(a=>a.type==='podcast').map(a=><button type="button" className="sw-asset-link" key={a.id} onClick={()=>setAssetId(a.id)}>{a.title} · {a.status}</button>)}<button type="button" className="sw-secondary" onClick={()=>addAsset('podcast')}>+ Add podcast asset</button></section>}
      <div className="sw-footer">Source of truth: this sermon record · {sermon.assets.length} connected assets · Last edited {sermon.updatedAt?new Date(sermon.updatedAt).toLocaleString():'now'}</div></>}
    </>:<section className="sw-empty"><i className="ti ti-book-2"/><h2>Build a connected sermon library</h2><p>Create or import a sermon to organize the message, production assets, and preached recording in one place.</p><button type="button" className="sw-primary" onClick={addSermon}>Create first sermon</button> <button type="button" className="sw-secondary" onClick={openImport}>Import sermon</button></section>}</main></div>
    {viewedType&&sermon&&<div className="sw-modal-backdrop" role="presentation" onClick={()=>setViewedType(null)}><section className="sw-asset-modal" role="dialog" aria-modal="true" aria-labelledby="sw-asset-list-title" onClick={event=>event.stopPropagation()}><div className="sw-row"><div><h2 id="sw-asset-list-title">{assetTypes.find(([type])=>type===viewedType)?.[1]}</h2><p className="sw-muted">{viewedType==='photography'?photoPosts.length:sermon.assets.filter(a=>a.type===viewedType).length} connected assets · {sermon.title}</p></div><button type="button" className="sw-quiet" onClick={()=>setViewedType(null)}>Close</button></div>{viewedType==='photography'?<>{role==='admin'&&<details className="sw-identity-manager"><summary>Manage private family photo references</summary><p className="sw-muted">Upload the exact approved JPEG for each person. These files stay in private sermon storage and replace the existing household reference for future images.</p><div className="sw-identity-grid">{['Larry','Lorenzo','Javin','Isaiah','Terica','Nyla'].map(member=><label key={member}>{member} · {identityRefs[member]?'Photo uploaded':'Using household reference'}<input type="file" accept="image/jpeg" onChange={event=>uploadIdentity(member,event.target.files?.[0])}/></label>)}</div>{identityMessage&&<p role="status" className="sw-muted">{identityMessage}</p>}</details>}<div className="sw-photo-grid">{photoPosts.length?photoPosts.map(photoPreview):<p className="sw-muted">Save Facebook posts to generate accompanying photographs.</p>}</div></>:<>{assetLinks(sermon.assets.filter(a=>a.type===viewedType),viewedType)}<button type="button" className="sw-secondary" onClick={()=>{addAsset(viewedType);setViewedType(null)}}>+ Add {assetTypes.find(([type])=>type===viewedType)?.[1]}</button></>}</section></div>}
    {importOpen&&<div className="sw-modal-backdrop" role="presentation"><section className="sw-import-modal" role="dialog" aria-modal="true" aria-labelledby="sw-import-title"><div className="sw-row"><h2 id="sw-import-title">Import sermon</h2><button type="button" className="sw-quiet" onClick={()=>setImportOpen(false)}>Close</button></div><p className="sw-muted">Review the extracted fields before adding a draft sermon. Existing Workspace sermons stay intact.</p><div className="sw-import-choices" role="group" aria-label="Import source">{[['vault','Sermon Builder Vault'],['file','Device file'],['paste','Paste text']].map(([value,label])=><button type="button" key={value} className={importSource===value?'active':''} onClick={()=>{setImportSource(value);setImportPreview(null);setImportError('')}}>{label}</button>)}</div>
      {importSource==='vault'&&<><label className="sw-field"><span>Vault owner</span><select value={vaultMember} onChange={event=>{setVaultMember(event.target.value);loadVault(event.target.value)}}>{[currentMember,...(role==='admin'?['Larry','Lorenzo','Terica','Nyla','Javin']:[])].filter((value,index,array)=>array.indexOf(value)===index).map(name=><option key={name}>{name}</option>)}</select></label><label className="sw-field"><span>Saved sermon</span><select value={vaultId} onChange={event=>previewVault(event.target.value)}><option value="">Choose a sermon</option>{vaultRecords.map(record=><option key={record.id} value={record.id}>{record.title}{record.series?` · ${record.series}`:''}</option>)}</select></label>{!importBusy&&!vaultRecords.length&&<p className="sw-muted">No synchronized sermons in this Vault. Open Apostolic Sermon Builder to synchronize saved sermons.</p>}</>}
      {importSource==='file'&&<label className="sw-field"><span>Choose a sermon file (.txt, .json, .docx, .pdf)</span><input type="file" accept=".txt,.json,.docx,.pdf" onChange={event=>previewFile(event.target.files?.[0])}/></label>}
      {importSource==='paste'&&<><label className="sw-field"><span>Paste sermon text</span><textarea rows="8" value={importText} onChange={event=>{setImportText(event.target.value);setImportPreview(null)}} placeholder="Title on the first line, followed by the manuscript…"/></label><button type="button" className="sw-secondary" onClick={previewPaste}>Preview pasted text</button></>}
      {importError&&<p className="sw-message sw-error" role="alert">{importError}</p>}{importBusy&&<p className="sw-muted" role="status">Reading sermon…</p>}{importPreview&&<div className="sw-import-preview"><h3>Review before import</h3><p><strong>Title:</strong> {importPreview.title}</p><p><strong>Scripture:</strong> {importPreview.scripture||'Not supplied'}</p><p><strong>Series:</strong> {importPreview.seriesTitle||'Standalone'}</p><p><strong>Big idea:</strong> {importPreview.bigIdea||'Not supplied'}</p><p><strong>Manuscript:</strong> {importPreview.outline.length.toLocaleString()} characters</p><pre>{importPreview.outline.slice(0,1000)||'No manuscript text was found; you can add it in the Workspace.'}</pre></div>}<div className="sw-import-actions"><button type="button" className="sw-quiet" onClick={()=>setImportOpen(false)}>Cancel</button><button type="button" className="sw-primary" disabled={!importPreview||importBusy} onClick={commitImport}>{importBusy?'Importing…':'Import draft sermon'}</button></div></section></div>}
  </div>
}
