import test from 'node:test'
import assert from 'node:assert/strict'
import {createEnhancementRepository,validateScreenshot} from '../../netlify/lib/enhancement-requests.mjs'
import {createEnhancementHandler} from '../../netlify/functions/enhancement-requests.mjs'
import {dispatchEnhancementNotifications} from '../../netlify/lib/enhancement-notifications.mjs'
import {similarRequests} from '../enhancements/model.js'
function memory(){const data=new Map(),versions=new Map();return {data,async get(key){return structuredClone(data.get(key)||null)},async getWithMetadata(key){return data.has(key)?{data:structuredClone(data.get(key)),etag:String(versions.get(key)||0)}:null},async setJSON(key,value,options={}){if(options.onlyIfNew&&data.has(key)||options.onlyIfMatch&&options.onlyIfMatch!==String(versions.get(key)||0))return {modified:false};data.set(key,structuredClone(value));versions.set(key,(versions.get(key)||0)+1);return {modified:true}},async list({prefix}){return {blobs:[...data.keys()].filter(key=>key.startsWith(prefix)).map(key=>({key}))}}}}
function setup(){const store=memory();let id=0,time=Date.parse('2026-10-09T14:00:00Z');return {store,repo:createEnhancementRepository({store,root:'house/',createId:()=>`id-${++id}`,now:()=>new Date(time+=1000)})}}
const idea={id:'request',title:'Meal prep reminders',description:'Remind me to thaw dinner the night before.',area:'Meals'}
const larry={member:'Larry',role:'admin'},terica={member:'Terica',role:'member'},nyla={member:'Nyla',role:'member'}
test('every member can submit, authorship and initial status come from the server, retries preserve the record',async()=>{const {repo}=setup();const {row}=await repo.create({...idea,createdBy:'Larry',status:'Available'},nyla);assert.equal(row.createdBy,'Nyla');assert.equal(row.status,'Received');assert.equal((await repo.create(idea,nyla)).existing,true);assert.equal((await repo.rows()).length,1);await assert.rejects(repo.create(idea,larry),/already used/);assert.equal((await repo.list(nyla)).canManage,false);assert.equal((await repo.list(terica)).canManage,true)})
test('support is unique and reversible, comments retain verified author and retry identity',async()=>{const {repo}=setup();await repo.create(idea,larry);await repo.change({id:idea.id,action:'support',support:true},nyla);await repo.change({id:idea.id,action:'support',support:true},nyla);assert.equal((await repo.get(idea.id)).supporters.length,2);await repo.change({id:idea.id,action:'support',support:false},nyla);assert.deepEqual((await repo.get(idea.id)).supporters,['Larry']);const comment={id:idea.id,action:'comment',commentId:'comment-1',text:'This helps with dinner.'};await repo.change(comment,nyla);await repo.change(comment,nyla);assert.equal((await repo.get(idea.id)).comments.length,1);assert.equal((await repo.get(idea.id)).comments[0].actor,'Nyla')})
test('only Larry and Terica can change status, stale versions cannot overwrite a newer decision',async()=>{const {repo}=setup();await repo.create(idea,nyla);const input={id:idea.id,action:'status',version:1,status:'Planned',priority:'High',note:'Review for next release.'};await assert.rejects(repo.change(input,{member:'Lorenzo',role:'admin'}),/Only Larry and Terica/);await assert.rejects(repo.change(input,nyla),/Only Larry and Terica/);await repo.change(input,terica);await assert.rejects(repo.change({...input,status:'Available'},larry),/changed/);const row=await repo.get(idea.id);assert.equal(row.status,'Planned');assert.equal(row.history.at(-1).actor,'Terica');assert.equal((await repo.list(nyla)).updates.length,1);await repo.change({action:'seen',id:idea.id},nyla);assert.equal((await repo.list(nyla)).updates.length,0)})
test('screenshots stay outside board listings and reject executable or invalid content',async()=>{const {repo,store}=setup();const png='data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAAfFcSJAAAADUlEQVQIHWP4z8DwHwAFgAI/ScLbtAAAAABJRU5ErkJggg==';await repo.create({...idea,screenshot:png},nyla);const listed=(await repo.list(larry)).rows[0];assert.equal(listed.hasScreenshot,true);assert.equal(listed.screenshot,undefined);assert.equal((await repo.get(idea.id)).screenshot,png);assert.equal(store.data.get('house/requests/request').screenshot,undefined);assert.throws(()=>validateScreenshot('data:image/svg+xml;base64,PHN2Zz4='),/PNG/);assert.throws(()=>validateScreenshot('data:image/png;base64,YWJj'),/invalid/)})
test('API rejects unauthenticated, switched-member, invalid IDs and unsupported requests',async()=>{const {repo}=setup();const event={httpMethod:'POST',body:JSON.stringify({...idea,action:'create',member:'Nyla'})};assert.equal((await createEnhancementHandler({authenticate:async()=>null,repository:()=>repo})(event)).statusCode,401);const api=createEnhancementHandler({authenticate:async()=>larry,repository:()=>repo,draft:async()=>({title:'Draft',area:'Meals'})});assert.equal((await api(event)).statusCode,409);assert.equal((await api({...event,body:JSON.stringify({...idea,action:'create',member:'Larry'})})).statusCode,200);assert.equal((await api({httpMethod:'GET',queryStringParameters:{id:'../private'}})).statusCode,400);assert.equal((await api({httpMethod:'DELETE'})).statusCode,405)})
test('notifications reach requester/supporters/managers, retry failures, and suppress successful repeats',async()=>{const {repo,store}=setup();await repo.create(idea,nyla);await repo.change({id:idea.id,action:'support',support:true},{member:'Javin'});const row=await repo.get(idea.id);await repo.change({id:idea.id,action:'status',version:row.version,status:'Under review',priority:'Normal',note:'Which reminder time works?'},terica);assert.ok((await repo.list(larry)).updates.some(item=>item.kind==='created'));assert.ok((await repo.list(nyla)).updates.some(item=>item.kind==='status'));const sent=[];const input={rows:await repo.rows(),devices:['Larry','Terica','Nyla','Javin'].map(member=>({id:member,member,subscription:{member}})),store,root:'house/',keys:{},now:new Date('2026-10-09T14:01:00Z'),deliver:async(subscription,message)=>sent.push([subscription.member,message.url])};assert.equal((await dispatchEnhancementNotifications(input)).sent,4);assert.equal((await dispatchEnhancementNotifications(input)).sent,0);assert.ok(sent.every(([,url])=>url==='/?enhancements=1'));const failed={...input,root:'failed/',deliver:async()=>{throw Error('Network')}};await dispatchEnhancementNotifications(failed);assert.equal((await dispatchEnhancementNotifications({...failed,now:new Date('2026-10-09T14:04:00Z'),deliver:input.deliver})).sent,4)})
test('similarity suggests candidates without merging IDs or changing requests',()=>{const rows=[{...idea,id:'a'},{...idea,id:'b',title:'Print weekly routine',description:'Weekly chores on paper.'}];assert.deepEqual(similarRequests('Meal prep reminders for dinner',rows).map(row=>row.id),['a'])})
