import test from 'node:test'
import assert from 'node:assert/strict'
import {createHash} from 'node:crypto'
import {createHouseholdArchive,archiveCutoff} from '../../netlify/lib/household-archive.mjs'
import {createArchiveHandler} from '../../netlify/functions/household-archive.mjs'
function memory(){const data=new Map(),versions=new Map();return {data,async get(key){return data.get(key)||null},async getWithMetadata(key){return data.has(key)?{data:data.get(key),etag:String(versions.get(key)||0)}:null},async setJSON(key,value,options={}){if(options.onlyIfNew&&data.has(key)||options.onlyIfMatch&&options.onlyIfMatch!==String(versions.get(key)||0))return {modified:false};data.set(key,value);versions.set(key,(versions.get(key)||0)+1);return {modified:true}},async list({prefix}){return {blobs:[...data.keys()].filter(k=>k.startsWith(prefix)).sort().map(key=>({key}))}}}}
function setup(){const stores=Object.fromEntries(['plans','shared','archive','meetings','actions'].map(x=>[x,memory()]));return {...stores,repo:createHouseholdArchive({...stores,householdId:'test',now:()=>new Date('2026-10-09T18:00:00Z')})}}
test('rolling archive includes pinned history and labels historical coverage without inventing completion',async()=>{const {repo,plans,archive}=setup();await plans.setJSON('test/daily-plans/2026-10-08',{date:'2026-10-08',household:{keyFocus:'Think tank'}});await archive.setJSON('test/days/2025-01-01',{date:'2025-01-01',kind:'day',pinned:true,title:'Keep'});await plans.setJSON('test/daily-plans/2025-02-01',{date:'2025-02-01'});const result=await repo.search({},{});assert.equal(archiveCutoff('2026-10-09'),'2025-10-09');assert.equal(result.rows.length,2);assert.match(result.rows[0].coverage,/were not captured/);assert.equal(result.rows[0].chores,undefined);assert.equal(result.rows[1].pinned,true)})
test('capture preserves pins and cleanup expires copies without deleting canonical plans or other source records',async()=>{const {repo,plans,archive}=setup();await plans.setJSON('test/daily-plans/2026-10-09',{date:'2026-10-09',household:{keyFocus:'Think tank'}});await archive.setJSON('test/days/2026-10-09',{date:'2026-10-09',pinned:true});await repo.capture();const day=await repo.day('2026-10-09');assert.equal(day.pinned,true);assert.ok(day.chores.every(x=>x.status!=='completed'));await plans.setJSON('test/daily-plans/2025-01-01',{date:'2025-01-01'});await archive.setJSON('test/days/2025-01-01',{date:'2025-01-01',plan:{private:'old'},pinned:false});await archive.setJSON('test/days/2025-01-02',{date:'2025-01-02',pinned:true});assert.deepEqual(await repo.prune(),{removed:1});assert.equal(await repo.day('2025-01-01'),null);assert.ok(await plans.get('test/daily-plans/2025-01-01'));assert.equal((await repo.day('2025-01-02')).pinned,true);await assert.rejects(repo.pin('2026-10-09',false,{role:'member'}),/Administrator/);await repo.pin('2026-10-09',false,{role:'admin'});assert.equal((await repo.day('2026-10-09')).pinned,false)})
test('meeting recall is scoped to the authenticated owner and operational audit recall excludes private categories',async()=>{const {repo,meetings,actions}=setup();for(const member of ['Larry','Terica']){const owner=createHash('sha256').update('test:'+member).digest('hex');await meetings.setJSON(owner+'/records/one',{id:member,date:'2026-10-09',kind:'morning',transcript:member+' private words'})}const result=await repo.search({kind:'meeting',member:'Terica'},{member:'Larry'});assert.equal(result.rows.length,0);assert.equal((await repo.search({kind:'meeting'},{member:'Larry'})).rows[0].id,'Larry');await actions.setJSON('test/audits/one',{id:'one',occurredAt:'2026-10-09T12:00:00Z',operations:[{type:'nutrition.log',description:'private'}]});await actions.setJSON('test/audits/two',{id:'two',occurredAt:'2026-10-09T12:00:00Z',summary:'Review routine',operations:[{type:'household.schedule.routine.create',description:'Morning'}]});assert.equal((await repo.search({kind:'changes'},{})).rows.length,1)})
test('archive endpoint requires authentication and guards capture',async()=>{const {repo}=setup();const request={httpMethod:'POST',body:JSON.stringify({action:'capture'})};assert.equal((await createArchiveHandler({authenticate:async()=>null,repository:()=>repo})(request)).statusCode,401);assert.equal((await createArchiveHandler({authenticate:async()=>({member:'Nyla',role:'member'}),repository:()=>repo})(request)).statusCode,403);await assert.rejects(repo.search({from:'2026-02-30'},{}),/valid date/);await assert.rejects(repo.search({kind:'secret'},{}),/record type/)})
