import { useEffect,useMemo,useState } from 'react'
import { HOUSEHOLD_MEMBERS } from '../homehq/projectData.js'
import { executeAssistantProposal,prepareDirectAction } from '../assistant/assistantApi.js'
import { getAcknowledgedSharedStateVersion,SHARED_STATE_EVENT,syncSharedState } from './sharedState.js'
import { calculatePerformance,classifyActivity,DEFAULT_PILLARS,INTELLIGENCE_STORAGE_KEY,intelligenceSummary,loadPerformanceSources,normalizeIntelligenceConfig,normalizePerformanceActivities,projectPerformance,resolveIntelligencePeriod } from './performanceIntelligence.js'
import { classifyCalendarActivities } from './performanceIntelligenceApi.js'
import { getHouseholdCalendarDate } from '../finance/financeTime.js'
import './HouseholdPerformanceIntelligence.css'

const pct=value=>value==null?'No Data':`${value}%`
const trend=(current,previous)=>current==null||previous==null?null:current-previous
const readConfig=()=>{try{return normalizeIntelligenceConfig(JSON.parse(localStorage.getItem(INTELLIGENCE_STORAGE_KEY)||'{}'),HOUSEHOLD_MEMBERS)}catch{return normalizeIntelligenceConfig({},HOUSEHOLD_MEMBERS)}}
const dayKey=date=>`${date.getFullYear()}-${String(date.getMonth()+1).padStart(2,'0')}-${String(date.getDate()).padStart(2,'0')}`
const rollingRange=days=>{const end=getHouseholdCalendarDate(),start=new Date(end);start.setDate(start.getDate()-days+1);return{preset:'custom',from:dayKey(start),to:dayKey(end),days,label:`${days}-day window`,previous:{}}}

function Score({value,onClick,label}){return <button type="button" className={`hpi-score${value==null?' is-empty':value<60?' is-off':value<80?' is-risk':' is-good'}`} onClick={onClick} disabled={!onClick} aria-label={`${label}: ${pct(value)}`}><strong>{pct(value)}</strong>{value!=null&&<span>{value>=80?'On Track':value>=60?'At Risk':'Off Track'}</span>}</button>}

function MetricHelp(){return <section className="hpi-metric-help"><article><i className="ti ti-clock"/><strong>Time Allocation</strong><p>Share of classified intentional minutes. It shows where time went—not performance.</p></article><article><i className="ti ti-target"/><strong>Pillar Attainment</strong><p>Completion against each member’s configured target, or plan completion when no target exists.</p></article><article><i className="ti ti-checklist"/><strong>Plan Adherence</strong><p>Completed qualifying activities divided by planned qualifying activities.</p></article></section>}

function Drilldown({detail,onClose,viewer,isAdmin}){if(!detail)return null;const hidden=!isAdmin&&detail.member!==viewer&&detail.privateDetails===false;return <div className="hpi-dialog-backdrop" onMouseDown={event=>event.target===event.currentTarget&&onClose()}><section className="hpi-dialog" role="dialog" aria-modal="true" aria-label="Score explanation"><header><div><span>Auditable score</span><h2>{detail.member} · {detail.name}</h2></div><button type="button" onClick={onClose} aria-label="Close score explanation"><i className="ti ti-x"/></button></header><div className="hpi-explanation"><article><span>Attainment</span><strong>{pct(detail.attainment)}</strong></article><article><span>Plan adherence</span><strong>{pct(detail.adherence)}</strong></article><article><span>Allocated time</span><strong>{detail.minutes} min</strong></article><article><span>Plan</span><strong>{detail.completed}/{detail.planned}</strong></article></div>{hidden?<p className="hpi-private"><i className="ti ti-lock"/> This member shares pillar totals only. Activity details remain private.</p>:<><h3>Targets</h3>{detail.targets.length?<div className="hpi-records">{detail.targets.map((item,index)=><article key={`${item.label}-${index}`}><strong>{item.label}</strong><span>{Math.round(item.actual)} of {Math.round(item.expected)} {item.unit}</span></article>)}</div>:<p className="hpi-empty">No explicit target is configured. The score uses completed versus planned qualifying activities.</p>}<h3>Supporting records</h3>{detail.activities.length?<div className="hpi-records">{detail.activities.map(item=><article key={`${item.kind}-${item.id}`}><div><strong>{item.title}</strong><small>{item.date} · {item.kind} · {Math.round(item.allocation)}% attribution</small></div><span>{item.completionEvidence==='elapsed-calendar'?'Elapsed calendar occurrence':item.completed?'Completed':'Planned / incomplete'}</span></article>)}</div>:<p className="hpi-empty">No activities are classified to this pillar for the selected period.</p>}</>}</section></div>}

function ConfigEditor({config,event,onCancel,onCommit,busy,error}){
  const [mode,setMode]=useState(event?'classification':'target')
  const [member,setMember]=useState(event?.owners?.find(item=>HOUSEHOLD_MEMBERS.includes(item))||HOUSEHOLD_MEMBERS[0])
  const [pillarId,setPillarId]=useState(event?.classification?.allocations?.[0]?.pillarId||config.pillars[0].id)
  const [secondary,setSecondary]=useState('')
  const [primaryPercent,setPrimaryPercent]=useState(100)
  const [label,setLabel]=useState('')
  const [targetCount,setTargetCount]=useState(1)
  const [frequency,setFrequency]=useState('weekly')
  const [saveRule,setSaveRule]=useState(false)
  const submit=()=>{
    let next={...config}
    if(mode==='classification'&&event){const allocations=[{pillarId,percent:secondary?Number(primaryPercent):100},...(secondary?[{pillarId:secondary,percent:100-Number(primaryPercent)}]:[])];next={...next,overrides:{...next.overrides,[event.id]:allocations}};if(saveRule)next.rules=[...next.rules,{id:`rule-${Date.now()}`,label:`${event.title} classification`,field:'title',match:'contains',value:event.title,member:'',allocations,active:true}]}
    if(mode==='target')next.targets=[...next.targets,{id:`target-${Date.now()}`,member,pillarId,label:label||`${config.pillars.find(item=>item.id===pillarId)?.name} commitment`,targetCount:Number(targetCount),targetMinutes:0,frequency,daysOfWeek:[],weight:1,minimum:0,active:true}]
    onCommit(next)
  }
  return <div className="hpi-dialog-backdrop"><section className="hpi-dialog hpi-editor" role="dialog" aria-modal="true" aria-label="Household Intelligence settings"><header><div><span>Action Mode protected</span><h2>{event?'Correct classification':'Add member target'}</h2></div><button onClick={onCancel} aria-label="Close editor"><i className="ti ti-x"/></button></header>{event?<><p className="hpi-editor-record"><strong>{event.title}</strong><span>{event.date} · {event.minutes} minutes</span></p><label>Primary pillar<select value={pillarId} onChange={e=>setPillarId(e.target.value)}>{config.pillars.map(item=><option key={item.id} value={item.id}>{item.name}</option>)}</select></label><label>Additional pillar, optional<select value={secondary} onChange={e=>setSecondary(e.target.value)}><option value="">None</option>{config.pillars.filter(item=>item.id!==pillarId).map(item=><option key={item.id} value={item.id}>{item.name}</option>)}</select></label>{secondary&&<label>Primary allocation: {primaryPercent}%<input type="range" min="5" max="95" step="5" value={primaryPercent} onChange={e=>setPrimaryPercent(e.target.value)}/><small>Total duration remains {event.minutes} minutes; it will not be double-counted.</small></label>}<label className="hpi-check"><input type="checkbox" checked={saveRule} onChange={e=>setSaveRule(e.target.checked)}/> Always classify matching event titles this way</label></>:<><label>Member<select value={member} onChange={e=>setMember(e.target.value)}>{HOUSEHOLD_MEMBERS.map(item=><option key={item}>{item}</option>)}</select></label><label>Pillar<select value={pillarId} onChange={e=>setPillarId(e.target.value)}>{config.pillars.map(item=><option key={item.id} value={item.id}>{item.name}</option>)}</select></label><label>Target description<input value={label} onChange={e=>setLabel(e.target.value)} placeholder="e.g. Complete five workouts"/></label><label>Target count<input type="number" min="1" value={targetCount} onChange={e=>setTargetCount(e.target.value)}/></label><label>Frequency<select value={frequency} onChange={e=>setFrequency(e.target.value)}><option value="daily">Daily</option><option value="weekly">Weekly</option><option value="monthly">Monthly</option><option value="period">Selected period</option></select></label></>}{error&&<p className="hpi-error">{error}</p>}<footer><button onClick={onCancel}>Cancel</button><button className="primary" onClick={submit} disabled={busy}>{busy?'Preparing…':'Review in Action Mode'}</button></footer></section></div>
}

export default function HouseholdPerformanceIntelligence({currentMember='Larry',isAdministrator=false}){
  const [preset,setPreset]=useState('week'),[custom,setCustom]=useState({from:'',to:''}),[revision,setRevision]=useState(0),[detail,setDetail]=useState(null),[editor,setEditor]=useState(null),[review,setReview]=useState(null),[busy,setBusy]=useState(false),[error,setError]=useState(''),[tab,setTab]=useState('attainment'),[aiClassifications,setAiClassifications]=useState({})
  const config=useMemo(readConfig,[revision])
  const period=useMemo(()=>resolveIntelligencePeriod(preset,{from:custom.from,to:custom.to}),[preset,custom])
  const sources=useMemo(()=>{const loaded=loadPerformanceSources();return{...loaded,calendarEvents:loaded.calendarEvents.map(event=>aiClassifications[event.id]?{...event,pillarAllocations:aiClassifications[event.id].allocations,classificationConfidence:aiClassifications[event.id].confidence}:event)}},[revision,aiClassifications])
  const activities=useMemo(()=>normalizePerformanceActivities({...sources,members:HOUSEHOLD_MEMBERS,config}),[sources,config])
  const model=useMemo(()=>projectPerformance(calculatePerformance({activities,config,members:HOUSEHOLD_MEMBERS,period,viewer:currentMember,isAdmin:isAdministrator})),[activities,config,period,currentMember,isAdministrator])
  const previous=useMemo(()=>calculatePerformance({activities,config,members:HOUSEHOLD_MEMBERS,period:{...period,...period.previous},viewer:currentMember,isAdmin:isAdministrator}),[activities,config,period,currentMember,isAdministrator])
  const rolling=useMemo(()=>[28,30,90].map(days=>({days,model:calculatePerformance({activities,config,members:HOUSEHOLD_MEMBERS,period:rollingRange(days),viewer:currentMember,isAdmin:isAdministrator})})),[activities,config,currentMember,isAdministrator])
  const brief=intelligenceSummary(model)
  useEffect(()=>{const refresh=()=>setRevision(value=>value+1);window.addEventListener(SHARED_STATE_EVENT,refresh);window.addEventListener('storage',refresh);return()=>{window.removeEventListener(SHARED_STATE_EVENT,refresh);window.removeEventListener('storage',refresh)}},[])
  const startCommit=async next=>{setBusy(true);setError('');try{const expectedVersion=getAcknowledgedSharedStateVersion(localStorage,INTELLIGENCE_STORAGE_KEY);const response=await prepareDirectAction({summary:'Update Household Intelligence targets or classifications',expectedVersion,operation:{type:'household.intelligence.config.update',targetId:'configuration',targetDate:'',description:'Update the reviewed Household Intelligence configuration',payload:{configJson:JSON.stringify(next)},allowedScopes:['this-item'],defaultScope:'this-item'}});setReview(response.proposal);setEditor(null)}catch(err){setError(err.message||'Action Mode could not prepare this change.')}finally{setBusy(false)}}
  const apply=async()=>{setBusy(true);setError('');try{await executeAssistantProposal({proposalId:review.id,selections:{},confirmed:true,confirmation:''});await syncSharedState();setReview(null);setRevision(value=>value+1)}catch(err){setError(err.message||'Action Mode could not apply this change.')}finally{setBusy(false)}}
  const openDetail=(member,pillar)=>setDetail({...pillar,member,privateDetails:config.privacy?.[member]?.details!==false})
  const runAiClassification=async()=>{const candidates=model.reviewQueue.filter(item=>item.kind==='calendar').slice(0,30);if(!candidates.length)return;setBusy(true);setError('');try{const response=await classifyCalendarActivities({events:candidates,pillars:config.pillars});setAiClassifications(current=>({...current,...Object.fromEntries((response.classifications||[]).map(item=>[item.id,item]))}))}catch(err){setError(err.message||'Brevity could not classify the calendar activities.')}finally{setBusy(false)}}
  return <div className="hpi-page"><header className="hpi-hero"><div><span>Household Management · Performance Intelligence</span><h1>Household Intelligence</h1><p>Auditable Seven Pillars attainment, plan adherence, time allocation, trends, and projected outcomes.</p></div>{isAdministrator&&<button type="button" onClick={()=>setEditor({type:'target'})}><i className="ti ti-target-arrow"/> Add member target</button>}</header>
    <nav className="hpi-periods" aria-label="Intelligence period">{[['today','Today'],['week','This Week'],['month','This Month'],['quarter','Quarter'],['custom','Custom']].map(([id,label])=><button key={id} className={preset===id?'active':''} onClick={()=>setPreset(id)}>{label}</button>)}</nav>{preset==='custom'&&<div className="hpi-custom"><label>From<input type="date" value={custom.from} onChange={e=>setCustom({...custom,from:e.target.value})}/></label><label>To<input type="date" value={custom.to} onChange={e=>setCustom({...custom,to:e.target.value})}/></label></div>}
    <MetricHelp/>
    <section className="hpi-overview"><article><span>Overall Household Alignment</span><strong>{pct(model.overall)}</strong><small>{trend(model.overall,previous.overall)==null?'No comparable prior data':`${trend(model.overall,previous.overall)>=0?'↑':'↓'} ${Math.abs(trend(model.overall,previous.overall))} points vs prior period`}</small></article><article><span>Plan Adherence</span><strong>{pct(model.planAdherence)}</strong><small>{model.activities.filter(item=>item.completed).length} of {model.activities.length} qualifying records complete</small></article><article><span>Classified Time</span><strong>{model.totalMinutes.toLocaleString()} min</strong><small>{model.unclassified.length} unclassified · {model.reviewQueue.length} awaiting review</small></article></section>
    <section className="hpi-history-strip"><article><span>Previous comparable period</span><strong>{pct(previous.overall)}</strong></article>{rolling.map(item=><article key={item.days}><span>{item.days===28?'4-week average':`${item.days}-day average`}</span><strong>{pct(item.model.overall)}</strong></article>)}</section>
    <section className="hpi-brief"><header><span>AI-ready household brief</span><h2>{brief.headline}</h2></header><div><article><strong>Strengths</strong>{brief.strengths.length?brief.strengths.map(item=><p key={item.id}>{item.name} · {pct(item.attainment)}</p>):<p>Insufficient data</p>}</article><article><strong>Attention Required</strong>{brief.attention.length?brief.attention.map(item=><p key={item.id}>{item.name} · {pct(item.attainment)} · {item.status}</p>):<p>Configure targets or complete planned work.</p>}</article></div><small>{brief.notice}</small></section>
    <section className="hpi-section"><header><div><span>Seven Pillars</span><h2>Pillar Balance</h2></div><div className="hpi-tabs"><button className={tab==='attainment'?'active':''} onClick={()=>setTab('attainment')}>Attainment</button><button className={tab==='time'?'active':''} onClick={()=>setTab('time')}>Time Allocation</button></div></header><div className="hpi-pillars">{model.householdPillars.map(item=><article key={item.id}><div><i className={`ti ${item.icon}`}/><span><strong>{item.name}</strong><small>{tab==='time'?`${item.minutes} classified minutes`:`${item.eligibleMembers} eligible member${item.eligibleMembers===1?'':'s'}`}</small></span></div><strong>{tab==='time'?pct(item.timeAllocation):pct(item.attainment)}</strong>{tab==='attainment'&&<footer><span>Projected {pct(item.projected)}</span><em className={`is-${item.status.toLowerCase().replace(' ','-')}`}>{item.status}</em></footer>}</article>)}</div></section>
    <section className="hpi-section"><header><div><span>Individual performance</span><h2>Member Scorecard</h2></div></header><div className="hpi-table-wrap"><table><thead><tr><th>Member</th>{config.pillars.map(item=><th key={item.id}>{item.name}</th>)}<th>Overall</th></tr></thead><tbody>{model.memberScores.map(member=>{const prior=previous.memberScores.find(item=>item.member===member.member),delta=trend(member.overall,prior?.overall);return <tr key={member.member}><th>{member.member}<small>{pct(member.planAdherence)} adherence · {delta==null?'no prior trend':`${delta>=0?'↑':'↓'} ${Math.abs(delta)} pts`}</small></th>{member.pillars.map(item=><td key={item.id}><Score value={item.attainment} label={`${member.member} ${item.name}`} onClick={()=>openDetail(member.member,item)}/></td>)}<td><Score value={member.overall} label={`${member.member} overall`}/></td></tr>})}</tbody></table></div></section>
    <section className="hpi-section"><header><div><span>Classification quality</span><h2>Review Queue</h2></div>{isAdministrator&&model.reviewQueue.some(item=>item.kind==='calendar')&&<button type="button" className="hpi-ai-button" onClick={runAiClassification} disabled={busy}><i className="ti ti-sparkles"/> {busy?'Classifying…':'Classify calendar with Brevity'}</button>}</header>{error&&!editor&&!review&&<p className="hpi-error">{error}</p>}{model.reviewQueue.length?<div className="hpi-review-list">{model.reviewQueue.slice(0,25).map(item=>isAdministrator?<button key={`${item.kind}-${item.id}`} onClick={()=>setEditor(item)}><span><strong>{item.title}</strong><small>{item.date} · {item.classification.confidence} confidence · {item.owners.join(', ')}</small></span><em>Correct classification</em></button>:<article key={`${item.kind}-${item.id}`}><span><strong>{item.title}</strong><small>{item.date} · awaiting administrator classification</small></span></article>)}</div>:<p className="hpi-empty">No medium- or low-confidence classifications need review in this period.</p>}<p className="hpi-method">Low-confidence records do not affect attainment until classified. Confirmed overrides and reusable rules take precedence over heuristic classification.</p></section>
    <section className="hpi-section"><header><div><span>Learned consistency</span><h2>Classification Rules</h2></div></header>{config.rules.length?<div className="hpi-review-list">{config.rules.map(rule=><article key={rule.id}><span><strong>{rule.label}</strong><small>{rule.field} {rule.match} “{rule.value}” · {rule.allocations.map(item=>`${config.pillars.find(pillar=>pillar.id===item.pillarId)?.name} ${Math.round(item.percent)}%`).join(', ')}</small></span>{isAdministrator&&<button type="button" onClick={()=>startCommit({...config,rules:config.rules.filter(item=>item.id!==rule.id)})}>Remove through Action Mode</button>}</article>)}</div>:<p className="hpi-empty">No reusable classification rules have been confirmed yet.</p>}</section>
    <section className="hpi-section"><header><div><span>Permission-aware visibility</span><h2>Privacy Sharing</h2></div></header><div className="hpi-privacy">{HOUSEHOLD_MEMBERS.map(member=><article key={member}><span><strong>{member}</strong><small>{config.privacy?.[member]?.details===false?'Shares pillar totals only':'Shares authorized activity details'}</small></span>{isAdministrator&&<button type="button" onClick={()=>startCommit({...config,privacy:{...config.privacy,[member]:{details:config.privacy?.[member]?.details===false}}})}>{config.privacy?.[member]?.details===false?'Share details':'Totals only'}</button>}</article>)}</div><p className="hpi-method">Private event titles are masked for unauthorized viewers even when their permitted aggregate contribution is used.</p></section>
    {detail&&<Drilldown detail={detail} onClose={()=>setDetail(null)} viewer={currentMember} isAdmin={isAdministrator}/>} {editor&&<ConfigEditor config={config} event={editor.type==='target'?null:editor} onCancel={()=>{setEditor(null);setError('')}} onCommit={startCommit} busy={busy} error={error}/>} {review&&<div className="hpi-dialog-backdrop"><section className="hpi-dialog" role="dialog" aria-modal="true" aria-label="Review Household Intelligence change"><header><div><span>Action Mode</span><h2>Review proposed intelligence change</h2></div><button onClick={()=>setReview(null)} aria-label="Close review"><i className="ti ti-x"/></button></header><p>{review.summary}</p><p className="hpi-safety"><i className="ti ti-shield-check"/> The exact synchronized version will be checked again. The change will be recorded in Audit History and can be undone.</p>{error&&<p className="hpi-error">{error}</p>}<footer><button onClick={()=>setReview(null)}>Cancel</button><button className="primary" onClick={apply} disabled={busy}>{busy?'Applying…':'Apply reviewed change'}</button></footer></section></div>}
  </div>
}
