import { useEffect, useMemo, useState } from 'react'
import { HOUSEHOLD_MEMBERS } from '../homehq/projectData.js'
import { SHARED_STATE_EVENT } from './sharedState.js'
import {
  HOUSEHOLD_SCHEDULE_STORAGE_KEY, WEEKDAYS, householdScheduleDate,
  invitationsForMember, normalizeHouseholdScheduleState, scheduleForMember,
} from './householdScheduleData.js'
import {
  requestHouseholdActionReview, scheduleBlockCreateOperation, scheduleBlockDeleteOperation,
  scheduleBlockUpdateOperation, scheduleInvitationOperation, scheduleOccurrenceOperation,
  scheduleRoutineCreateOperation, scheduleRoutineDeleteOperation, scheduleRoutineUpdateOperation,
} from './householdActionReview.js'
import './HouseholdSchedule.css'

const PILLARS=['Spiritual Maturity','Health & Nutrition','Physical Fitness','Household Management','Education','Finance','Ministry & Fellowship']
const HOURS=Array.from({length:18},(_,index)=>index+5)
const emptyBlock=member=>({title:'',date:householdScheduleDate(),startTime:'09:00',endTime:'10:00',owner:member,participants:[],pillar:'Household Management',notes:''})
const emptyRoutine=member=>({title:'',owner:member,participants:[],days:[1,2,3,4,5],startTime:'07:00',endTime:'08:00',pillar:'Household Management',notes:'',enabled:true})
function loadState(){try{return normalizeHouseholdScheduleState(JSON.parse(localStorage.getItem(HOUSEHOLD_SCHEDULE_STORAGE_KEY)||'{}'))}catch{return normalizeHouseholdScheduleState()}}
const timeLabel=value=>{const[hour,minute]=String(value||'00:00').split(':').map(Number);return new Date(2000,0,1,hour,minute).toLocaleTimeString('en-US',{hour:'numeric',minute:'2-digit'})}
const hourLabel=hour=>new Date(2000,0,1,hour,0).toLocaleTimeString('en-US',{hour:'numeric'})
const minutes=value=>{const[h,m]=String(value||'00:00').split(':').map(Number);return h*60+m}

function ReviewStatus({error,notice}){return <>{error&&<div className="household-operations-read-only" role="alert"><strong>Review could not be prepared.</strong> {error}</div>}{notice&&<div className="household-operations-read-only" role="status"><strong>Review required.</strong> {notice}</div>}</>}

export default function HouseholdSchedule({currentMember,mode='schedule',canEdit=true,isAdmin=false}){
  const[state,setState]=useState(loadState),[date,setDate]=useState(()=>householdScheduleDate())
  const[blockForm,setBlockForm]=useState(()=>emptyBlock(currentMember)),[routineForm,setRoutineForm]=useState(()=>emptyRoutine(currentMember))
  const[showAdd,setShowAdd]=useState(false),[editingId,setEditingId]=useState(''),[reviewBusy,setReviewBusy]=useState(''),[reviewError,setReviewError]=useState(''),[reviewNotice,setReviewNotice]=useState('')
  useEffect(()=>{setBlockForm(form=>({...form,owner:currentMember}));setRoutineForm(form=>({...form,owner:currentMember}))},[currentMember])
  useEffect(()=>{const refresh=event=>{if(event.type==='storage'&&event.key!==HOUSEHOLD_SCHEDULE_STORAGE_KEY)return;if(event.type===SHARED_STATE_EVENT&&!event.detail?.keys?.includes(HOUSEHOLD_SCHEDULE_STORAGE_KEY))return;setState(loadState())};window.addEventListener('storage',refresh);window.addEventListener(SHARED_STATE_EVENT,refresh);return()=>{window.removeEventListener('storage',refresh);window.removeEventListener(SHARED_STATE_EVENT,refresh)}},[])
  useEffect(()=>{if(!canEdit){setShowAdd(false);setEditingId('')}},[canEdit])

  const stage=async(summary,operation,key=operation.targetId||operation.type)=>{if(!canEdit)return false;setReviewBusy(key);setReviewError('');setReviewNotice('');try{await requestHouseholdActionReview({summary,operation});setReviewNotice('Action Mode has the proposal. Nothing changes until you approve it; the exact record version, actor, change, Audit History, and safe Undo will be preserved.');return true}catch(error){setReviewError(error.message||'Brevity could not prepare this household change for review.');return false}finally{setReviewBusy('')}}
  const schedule=useMemo(()=>scheduleForMember(state,date,currentMember),[state,date,currentMember])
  const invites=useMemo(()=>invitationsForMember(state,currentMember).sort((a,b)=>`${a.date}-${a.startTime}`.localeCompare(`${b.date}-${b.startTime}`)),[state,currentMember])
  const memberRoutines=useMemo(()=>state.routines.filter(item=>item.owner===currentMember||item.participants?.includes(currentMember)),[state,currentMember])
  const capacity=useMemo(()=>schedule.reduce((sum,item)=>sum+Math.max(0,minutes(item.endTime)-minutes(item.startTime)),0),[schedule])
  const ownerOptions=isAdmin?HOUSEHOLD_MEMBERS:[currentMember]
  const toggleParticipant=(form,setForm,member)=>setForm({...form,participants:form.participants.includes(member)?form.participants.filter(name=>name!==member):[...form.participants,member]})

  const saveBlock=async event=>{event.preventDefault();const before=state.blocks.find(item=>item.id===editingId);try{const operation=before?scheduleBlockUpdateOperation(before,blockForm):scheduleBlockCreateOperation(blockForm);if(await stage(before?`Review changes to ${before.title}`:`Review new time block ${blockForm.title}`,operation,'block-form')){setEditingId('');setBlockForm({...emptyBlock(currentMember),date});setShowAdd(false)}}catch(error){setReviewError(error.message)}}
  const saveRoutine=async event=>{event.preventDefault();const before=state.routines.find(item=>item.id===editingId);try{const operation=before?scheduleRoutineUpdateOperation(before,routineForm):scheduleRoutineCreateOperation(routineForm);if(await stage(before?`Review changes to ${before.title}`:`Review new routine ${routineForm.title}`,operation,'routine-form')){setEditingId('');setRoutineForm(emptyRoutine(currentMember));setShowAdd(false)}}catch(error){setReviewError(error.message)}}
  const editBlock=async item=>{if(item.sourceType==='routine'){if(window.confirm('Change this occurrence only? Press OK for this date only, or Cancel to edit the recurring routine.')){const start=window.prompt('Start time (HH:MM)',item.startTime);if(!start)return;const end=window.prompt('End time (HH:MM)',item.endTime);if(!end)return;await stage(`Review ${item.title} for ${date}`,scheduleOccurrenceOperation(item,date,{startTime:start,endTime:end,cancelled:false}),item.id);return}const routine=state.routines.find(candidate=>candidate.id===item.routineId);if(routine){setEditingId(routine.id);setRoutineForm({...routine,participants:routine.participants||[],days:routine.days||[]});setShowAdd(true)}return}setEditingId(item.id);setBlockForm({...item,participants:item.participants||[]});setShowAdd(true)}
  const removeBlock=item=>stage(item.sourceType==='routine'?`Review skipped routine ${item.title}`:`Review deletion of ${item.title}`,item.sourceType==='routine'?scheduleOccurrenceOperation(item,date,{cancelled:true}):scheduleBlockDeleteOperation(item),item.id)

  if(mode==='routines')return <div className="household-schedule"><header className="schedule-hero"><div><p>Household Management · Routines</p><h1>Routines</h1><span>Define recurring rhythms once. Each approved routine is projected into Schedule and Family Calendar from this authoritative record.</span></div>{canEdit&&<button onClick={()=>{setShowAdd(value=>!value);setEditingId('');setRoutineForm(emptyRoutine(currentMember))}}><i className={`ti ${showAdd?'ti-x':'ti-plus'}`}/> {showAdd?'Close':'Add routine'}</button>}</header>
    <ReviewStatus error={reviewError} notice={reviewNotice}/>
    {showAdd&&canEdit&&<form className="schedule-form" onSubmit={saveRoutine}><label className="wide"><span>Routine</span><input required value={routineForm.title} onChange={e=>setRoutineForm({...routineForm,title:e.target.value})} placeholder="Morning walk"/></label><label><span>Owner</span><select value={routineForm.owner} onChange={e=>setRoutineForm({...routineForm,owner:e.target.value})}>{ownerOptions.map(name=><option key={name}>{name}</option>)}</select></label><label><span>Pillar</span><select value={routineForm.pillar} onChange={e=>setRoutineForm({...routineForm,pillar:e.target.value})}>{PILLARS.map(name=><option key={name}>{name}</option>)}</select></label><label><span>Start</span><input type="time" value={routineForm.startTime} onChange={e=>setRoutineForm({...routineForm,startTime:e.target.value})}/></label><label><span>End</span><input type="time" value={routineForm.endTime} onChange={e=>setRoutineForm({...routineForm,endTime:e.target.value})}/></label><div className="wide schedule-choice-group"><span>Days</span><div>{WEEKDAYS.map((name,index)=><button type="button" className={routineForm.days.includes(index)?'active':''} onClick={()=>setRoutineForm({...routineForm,days:routineForm.days.includes(index)?routineForm.days.filter(day=>day!==index):[...routineForm.days,index]})} key={name}>{name.slice(0,3)}</button>)}</div></div><div className="wide schedule-choice-group"><span>Participants</span><div>{HOUSEHOLD_MEMBERS.filter(name=>name!==routineForm.owner).map(name=><button type="button" className={routineForm.participants.includes(name)?'active':''} onClick={()=>toggleParticipant(routineForm,setRoutineForm,name)} key={name}>{name}</button>)}</div></div><label className="wide"><span>Notes / standard</span><input value={routineForm.notes} onChange={e=>setRoutineForm({...routineForm,notes:e.target.value})}/></label><button className="wide schedule-save" type="submit" disabled={Boolean(reviewBusy)}>{reviewBusy==='routine-form'?'Preparing review…':editingId?'Review routine changes':'Review new routine'}</button></form>}
    <div className="routine-list">{!memberRoutines.length&&<div className="schedule-empty">No routines are assigned to {currentMember} yet.</div>}{memberRoutines.map(item=>{const owns=item.owner===currentMember||isAdmin;return <article key={item.id}><div><span>{item.pillar}</span><h3>{item.title}</h3><p>{item.days.map(day=>WEEKDAYS[day].slice(0,3)).join(' · ')} · {timeLabel(item.startTime)}–{timeLabel(item.endTime)}</p><small>{item.owner}{item.participants?.length?` · with ${item.participants.join(', ')}`:''}</small></div>{canEdit&&owns&&<div className="routine-actions"><button disabled={Boolean(reviewBusy)} onClick={()=>stage(`Review ${item.enabled?'pause':'resume'} for ${item.title}`,scheduleRoutineUpdateOperation(item,{...item,enabled:!item.enabled}),item.id)}>{item.enabled?'Pause':'Resume'}</button><button disabled={Boolean(reviewBusy)} onClick={()=>{setEditingId(item.id);setRoutineForm({...item,participants:item.participants||[],days:item.days||[]});setShowAdd(true)}}>Edit</button>{isAdmin&&<button disabled={Boolean(reviewBusy)} onClick={()=>stage(`Review deletion of ${item.title}`,scheduleRoutineDeleteOperation(item),item.id)}>Delete</button>}</div>}</article>})}</div>
  </div>

  return <div className="household-schedule"><header className="schedule-hero"><div><p>Household Management · Schedule</p><h1>My Schedule</h1><span>Time-block the day, answer household invitations, and review routines in one hour-by-hour view.</span></div>{canEdit&&<button onClick={()=>{setShowAdd(value=>!value);setEditingId('');setBlockForm({...emptyBlock(currentMember),date})}}><i className={`ti ${showAdd?'ti-x':'ti-plus'}`}/> {showAdd?'Close':'Add time block'}</button>}</header>
    <ReviewStatus error={reviewError} notice={reviewNotice}/>
    <section className="schedule-command"><label><span>Day</span><input type="date" value={date} onChange={e=>{setDate(e.target.value);setBlockForm(form=>({...form,date:e.target.value}))}}/></label><div><span>Scheduled</span><strong>{schedule.length} blocks</strong></div><div><span>Allocated</span><strong>{Math.round(capacity/60*10)/10} hrs</strong></div><div><span>Invitations</span><strong>{invites.length} pending</strong></div></section>
    {invites.length>0&&<section className="schedule-invitations"><header><div><p>Invitations</p><h2>Household invitations awaiting your response</h2></div></header>{invites.slice(0,5).map(item=><article key={item.id}><div><strong>{item.title}</strong><span>{item.date} · {timeLabel(item.startTime)}–{timeLabel(item.endTime)} · from {item.owner}</span></div>{canEdit&&<div><button disabled={Boolean(reviewBusy)} onClick={()=>stage(`Review acceptance of ${item.title}`,scheduleInvitationOperation(item,'accepted',currentMember),item.id)}>Accept</button><button disabled={Boolean(reviewBusy)} onClick={()=>stage(`Review decline of ${item.title}`,scheduleInvitationOperation(item,'declined',currentMember),item.id)}>Decline</button></div>}</article>)}</section>}
    {showAdd&&canEdit&&<form className="schedule-form" onSubmit={saveBlock}><label className="wide"><span>Time block</span><input required value={blockForm.title} onChange={e=>setBlockForm({...blockForm,title:e.target.value})} placeholder="Prepare lunch"/></label><label><span>Date</span><input type="date" value={blockForm.date} onChange={e=>setBlockForm({...blockForm,date:e.target.value})}/></label><label><span>Owner</span><select value={blockForm.owner} onChange={e=>setBlockForm({...blockForm,owner:e.target.value,participants:blockForm.participants.filter(name=>name!==e.target.value)})}>{ownerOptions.map(name=><option key={name}>{name}</option>)}</select></label><label><span>Pillar</span><select value={blockForm.pillar} onChange={e=>setBlockForm({...blockForm,pillar:e.target.value})}>{PILLARS.map(name=><option key={name}>{name}</option>)}</select></label><label><span>Start</span><input type="time" value={blockForm.startTime} onChange={e=>setBlockForm({...blockForm,startTime:e.target.value})}/></label><label><span>End</span><input type="time" value={blockForm.endTime} onChange={e=>setBlockForm({...blockForm,endTime:e.target.value})}/></label><div className="wide schedule-choice-group"><span>Invite household members</span><div>{HOUSEHOLD_MEMBERS.filter(name=>name!==blockForm.owner).map(name=><button type="button" className={blockForm.participants.includes(name)?'active':''} onClick={()=>toggleParticipant(blockForm,setBlockForm,name)} key={name}>{name}</button>)}</div></div><label className="wide"><span>Notes</span><input value={blockForm.notes} onChange={e=>setBlockForm({...blockForm,notes:e.target.value})}/></label><button className="wide schedule-save" type="submit" disabled={Boolean(reviewBusy)}>{reviewBusy==='block-form'?'Preparing review…':editingId?'Review block changes':'Review new time block'}</button></form>}
    <div className="schedule-day"><aside>{HOURS.map(hour=><div key={hour}><span>{hourLabel(hour)}</span></div>)}</aside><main>{HOURS.map(hour=><div className="schedule-hour-line" key={hour}/>)}{schedule.map(item=>{const start=minutes(item.startTime),end=minutes(item.endTime),top=Math.max(0,(start-300)/60*68),height=Math.max(38,(end-start)/60*68),owns=item.owner===currentMember||isAdmin,canRemove=item.sourceType==='routine'||isAdmin;return <article className={`schedule-block schedule-block--${item.sourceType}`} style={{top,height}} key={item.id}><div><span>{item.pillar}{item.sourceType==='routine'?' · Routine':''}</span><strong>{item.title}</strong><small>{timeLabel(item.startTime)}–{timeLabel(item.endTime)}{item.participants?.length?` · ${item.participants.join(', ')}`:''}</small></div>{canEdit&&owns&&<div><button disabled={Boolean(reviewBusy)} onClick={()=>editBlock(item)}>Edit</button>{canRemove&&<button disabled={Boolean(reviewBusy)} onClick={()=>removeBlock(item)} aria-label={`Review removal of ${item.title}`}>×</button>}</div>}</article>})}{!schedule.length&&<div className="schedule-empty-overlay">No time blocks yet. {canEdit?'Add a block or create a routine.':'Household planning permission is required to add one.'}</div>}</main></div>
  </div>
}
