import test from 'node:test'
import assert from 'node:assert/strict'
import {emptyHealth,healthSettings,applyHealthSnapshot,healthSummary,sharedHealthSummary,assistantHealthContext} from '../../netlify/lib/member-health.mjs'
import {createMemberHealthHandler} from '../../netlify/functions/member-health.mjs'
const now=new Date('2026-09-30T20:00:00Z'),id='aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa'
const settings={expectedVersion:0,deviceId:id,enabled:true,steps:true,workouts:true,assistantAccess:false,shareSteps:false,shareWorkouts:false,stepGoal:12000,confirmed:true}
const connected=()=>healthSettings(emptyHealth(),settings,now)
const snapshot=()=>({deviceId:id,consentRevision:1,capturedAt:now.toISOString(),timeZone:'America/New_York',days:Array.from({length:30},(_,i)=>({date:new Date(Date.parse('2026-09-30')-i*86400000).toISOString().slice(0,10),steps:i?null:8500,workoutCount:null,workoutMinutes:null}))})
test('health data and AI are private by default even for an administrator',async()=>{const value=applyHealthSnapshot(connected(),snapshot(),now);assert.equal(sharedHealthSummary(value,'Larry',now),null);assert.deepEqual(await assistantHealthContext('Larry',{read:async()=>({value})},now),{state:'not-authorized',member:'Larry'});assert.equal(healthSummary(value,'Larry',now).today.steps,8500)})
test('snapshot replacement is idempotent and corrections can lower totals without double counting',()=>{const first=applyHealthSnapshot(connected(),snapshot(),now);assert.equal(applyHealthSnapshot(first,snapshot(),now),first);const next=snapshot();next.capturedAt='2026-09-30T20:01:00Z';next.days[0].steps=8000;const updated=applyHealthSnapshot(first,next,new Date(next.capturedAt));assert.equal(updated.days.at(-1).steps,8000);assert.equal(updated.days[0].steps,null)})
test('revocation removes summaries and rejects queued uploads from the old consent',()=>{const value=applyHealthSnapshot(connected(),snapshot(),now),revoked=healthSettings(value,{...settings,expectedVersion:value.version,enabled:false},now);assert.deepEqual(revoked.days,[]);assert.equal(revoked.connection.assistantAccess,false);assert.throws(()=>applyHealthSnapshot(revoked,snapshot(),now),/disconnected/);assert.equal(sharedHealthSummary(revoked,'Larry',now),null)})
test('household sharing returns only the specific totals that the member chose',()=>{const value=applyHealthSnapshot(connected(),snapshot(),now);value.connection.shareSteps=true;const shared=sharedHealthSummary(value,'Larry',now);assert.equal(shared.steps,8500);for(const key of ['days','audit','deviceId','connection','workoutCount'])assert.equal(key in shared,false)})
test('source identity, consent version, date range and finite metrics are enforced',()=>{for(const change of [{deviceId:'bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbbb'},{consentRevision:0},{timeZone:'UTC'},{days:[]},{capturedAt:'bad'}])assert.throws(()=>applyHealthSnapshot(connected(),{...snapshot(),...change},now));const bad=snapshot();bad.days[0].steps=-1;assert.throws(()=>applyHealthSnapshot(connected(),bad,now));bad.days[0].steps=Infinity;assert.throws(()=>applyHealthSnapshot(connected(),bad,now));const duplicate=snapshot();duplicate.days[1].date=duplicate.days[0].date;assert.throws(()=>applyHealthSnapshot(connected(),duplicate,now))})
test('privacy changes require review, exact version, and explicit data type choices',()=>{assert.throws(()=>healthSettings(emptyHealth(),{...settings,confirmed:false},now));assert.throws(()=>healthSettings(connected(),settings,now),/changed/);assert.throws(()=>healthSettings(emptyHealth(),{...settings,steps:'yes'},now));const value=connected();value.connection.steps=false;assert.throws(()=>applyHealthSnapshot(value,snapshot(),now),/not authorized/)})
test('API ignores member query selectors and cannot mutate another member through its body',async()=>{const reads=[],writes=[];const repository={read:async member=>{reads.push(member);return {value:emptyHealth(),etag:null}},write:async(member,value)=>writes.push({member,value})};const handler=createMemberHealthHandler({readSession:async()=>({member:'Larry',role:'admin'}),repository,now:()=>now});const result=await handler({httpMethod:'GET',queryStringParameters:{member:'Terica'}});assert.equal(JSON.parse(result.body).member,'Larry');assert.deepEqual(reads,['Larry']);const bad=await handler({httpMethod:'POST',queryStringParameters:{action:'settings'},headers:{'content-type':'application/json'},body:JSON.stringify({...settings,member:'Terica'})});assert.equal(bad.statusCode,400);assert.equal(writes.length,0)})
test('API refuses unauthenticated requests and form submissions',async()=>{assert.equal((await createMemberHealthHandler({readSession:async()=>null})({httpMethod:'GET'})).statusCode,401);const h=createMemberHealthHandler({readSession:async()=>({member:'Larry'}),repository:{}});assert.equal((await h({httpMethod:'POST',queryStringParameters:{action:'settings'},headers:{}})).statusCode,415)})

test('AI receives only own summaries after explicit access and loses them on revocation',async()=>{let value=applyHealthSnapshot(connected(),snapshot(),now);value=healthSettings(value,{...settings,expectedVersion:value.version,assistantAccess:true},now);const reads=[];const repo={read:async member=>{reads.push(member);return{value}}};const result=await assistantHealthContext('Larry',repo,now);assert.equal(result.today.steps,8500);assert.equal(result.state,'available');assert.deepEqual(reads,['Larry']);for(const key of ['audit','connection','deviceId'])assert.equal(key in result,false);value=healthSettings(value,{...settings,expectedVersion:value.version,assistantAccess:false},now);assert.equal((await assistantHealthContext('Larry',repo,now)).state,'not-authorized')})
test('conditional-write conflicts do not report a successful stale health upload',async()=>{const value=connected();let writeCount=0;const handler=createMemberHealthHandler({readSession:async()=>({member:'Larry'}),repository:{read:async()=>({value,etag:'original-etag'}),write:async(member,next,etag)=>{assert.equal(etag,'original-etag');writeCount++;throw Object.assign(Error('Consent changed during save.'),{status:409})}},now:()=>now});const response=await handler({httpMethod:'POST',queryStringParameters:{action:'sync'},headers:{'content-type':'application/json'},body:JSON.stringify(snapshot())});assert.equal(response.statusCode,409);assert.equal(writeCount,1);assert.equal('today' in JSON.parse(response.body),false)})
