import test from 'node:test'
import assert from 'node:assert/strict'
import fs from 'node:fs'
import {retryRefresh,isTransientRefreshError} from './retry.js'

test('transient refresh failures retry automatically and eventually return data',async()=>{let calls=0;const value=await retryRefresh(async()=>{calls+=1;if(calls<3)throw new Error('network temporarily unavailable');return{ok:true}},{attempts:3,baseDelayMs:1});assert.deepEqual(value,{ok:true});assert.equal(calls,3)})

test('permanent refresh errors do not churn through retries',async()=>{let calls=0;await assert.rejects(()=>retryRefresh(async()=>{calls+=1;throw new Error('invalid credentials')},{attempts:3,baseDelayMs:1}),/invalid credentials/);assert.equal(calls,1);assert.equal(isTransientRefreshError(new Error('network timeout')),true);assert.equal(isTransientRefreshError(new Error('invalid credentials')),false)})

test('sermon artifacts are bound to reviewed active content and external publishing stays disabled',()=>{const workflow=fs.readFileSync(new URL('../../netlify/functions/sermon-workflow.mjs',import.meta.url),'utf8'),assets=fs.readFileSync(new URL('../../netlify/functions/sermon-slides-background.mjs',import.meta.url),'utf8'),state=fs.readFileSync(new URL('../../netlify/lib/sermon-workflow-state.mjs',import.meta.url),'utf8');for(const stage of ['notes','documents','documentPublishing','slides','visuals','devotions','complete'])assert.match(state,new RegExp(`['\"]${stage}['\"]`));for(const source of [workflow,assets]){assert.match(source,/requireReviewedActiveSermon/);assert.match(source,/sourceHash/);assert.match(source,/activeVersion/);assert.doesNotMatch(source,/publish(?:Sermon|SevenDay|DailyDevotion|Slide|Visual|DevotionTarget)/)}assert.match(workflow,/documentPublishing', 'skipped'/);assert.match(assets,/External publishing requires a reviewed, reversible workflow/)})

test('uploaded sermon notes skip unnecessary Word generation while retaining a local reviewed PDF',()=>{const workflow=fs.readFileSync(new URL('../../netlify/functions/sermon-workflow.mjs',import.meta.url),'utf8');assert.match(workflow,/pdfOnly = source\.sourceKind === 'notes'/);assert.match(workflow,/pdfOnly \? Promise\.resolve\(null\) : buildDocx/);assert.match(workflow,/buildPdf\(notes, source\)/);assert.doesNotMatch(workflow,/sermon-slides-background/)})

test('active sermon notes remain visible even when no dated devotion can be derived',()=>{const householdData=fs.readFileSync(new URL('../../netlify/functions/household-data.js',import.meta.url),'utf8');assert.match(householdData,/if \(!activeSermon\?\.sermonNotes\) return value/);assert.match(householdData,/if \(!devotion\) return \{ \.\.\.value, spiritual:retained \}/);assert.match(householdData,/sermonNotes: sharedSpiritualValue\(activeSermon\.sermonNotes\)/)})

test('sermon artifact destinations remain locked to the approved OneDrive folders',()=>{const targets=fs.readFileSync(new URL('../../netlify/lib/onedrive-targets.mjs',import.meta.url),'utf8');assert.match(targets,/IgBAFpOkyOC1TImi4vwdATDAAeeDqDWqd5NdChS4zVEGsyY/);assert.match(targets,/IgARcbb-ZETMTa8oWW81C-AYAbQ-ripTssZ9kc9xmP0aEAM/);assert.match(targets,/IgDXneTEyqhkQbijIB2DSCHgAacxlIATQBYvRb5QeOuZXE0/);const shared='IgAKn3pyfEBaRpkNW37-kbX3ARPmGXAi5ywV3dcn20pQ2qw';assert.equal((targets.match(new RegExp(shared,'g'))||[]).length,2);assert.match(targets,/images:.*IgAKn3pyfEBaRpkNW37-kbX3ARPmGXAi5ywV3dcn20pQ2qw/);assert.match(targets,/slides:.*IgAKn3pyfEBaRpkNW37-kbX3ARPmGXAi5ywV3dcn20pQ2qw/)})

test('operational completion checklist remains an executable product contract',()=>{const contract=fs.readFileSync(new URL('../../docs/STABILIZATION-COMPLETION-CHECKLIST.md',import.meta.url),'utf8');for(const term of ['seven-pillar executive view','Schedule, Routines, Operations, Inventory','localStorage is a recovery/offline cache','Scheduled chores require completion submission','Sermon uploads are represented as one durable workflow','Deprecated My Planner navigation may not return','Shared Spiritual Maturity remains household-scoped'])assert.match(contract,new RegExp(term.replace(/[.*+?^${}()|[\]\\]/g,'\\$&'),'i'))})
