import {useState} from 'react'
import {HOUSEHOLD_MEMBERS} from '../homehq/projectData.js'
import {householdScheduleDate,WEEKDAYS} from './householdScheduleData.js'
import {prepareDirectAction} from '../assistant/assistantApi.js'
import {requestActionReview,requestAssistantConversation} from '../assistant/actionEvents.js'
import {scheduleRoutineCreateOperation} from './householdActionReview.js'
export default function RoutineReview({currentMember,isAdmin,canEdit}){
 const [member,setMember]=useState(isAdmin?'Household':currentMember),[variant,setVariant]=useState(''),[result,setResult]=useState(null),[error,setError]=useState(''),[busy,setBusy]=useState(false),[selected,setSelected]=useState([])
 const analyze=async()=>{setBusy(true);setError('');try{const response=await fetch('/.netlify/functions/household-routine-review?'+new URLSearchParams({member,variant,date:householdScheduleDate()}),{cache:'no-store'}),data=await response.json();if(!response.ok)throw Error(data.error);setResult(data);setSelected([])}catch(e){setError(e.message)}finally{setBusy(false)}}
 const review=async()=>{setBusy(true);setError('');try{const operations=selected.map(i=>scheduleRoutineCreateOperation(result.proposals[i]));const data=await prepareDirectAction({summary:`Review ${member}’s proposed weekly routine blocks`,operations,expectedVersion:result.scheduleVersion});requestActionReview(data.proposal);setSelected([]);setResult(null)}catch(e){setError(e.message)}finally{setBusy(false)}}
 return <section className="routine-review" aria-label="Build routines from household records"><h2>Build my weekly routine</h2><p>Brevity combines saved chores, calendar commitments and routines. Proposed chore blocks protect 8 AM–noon focus time. Choose a Schedule A–D reference only when you want to review its morning times.</p><label>Member <select value={member} onChange={e=>{setMember(e.target.value);setResult(null)}}>{(isAdmin?['Household',...HOUSEHOLD_MEMBERS]:[currentMember]).map(x=><option key={x}>{x}</option>)}</select></label><label> Morning reference <select value={variant} onChange={e=>{setVariant(e.target.value);setResult(null)}}><option value="">Not yet agreed</option>{['A','B','C','D'].map(x=><option key={x}>{x}</option>)}</select></label><button disabled={busy} onClick={analyze}>{busy?'Reviewing sources…':'Review chores & calendars'}</button>{error&&<p role="alert">{error}</p>}{result&&<><p>{result.notice}</p>{result.week.map(day=><details key={`${day.member}:${day.date}`}><summary>{day.member} · {WEEKDAYS[day.weekday]} · {day.date} · {day.items.length} commitments</summary>{day.items.map((x,i)=><p key={x.id||i}><strong>{x.startTime||x.timing||'Time to agree'} {x.endTime?`– ${x.endTime}`:''} · {x.title}</strong><br/>{x.source} · {x.status||'Scheduled; not reported complete'}</p>)}{day.conflicts.map(x=><p key={x}>Timing conflict: {x}</p>)}</details>)}<h3>Proposed recurring blocks</h3>{result.proposals.map((x,i)=><label key={x.sourceId} style={{display:'block',margin:'12px 0'}}><input type="checkbox" checked={selected.includes(i)} disabled={!canEdit||!selected.includes(i)&&selected.length>=8} onChange={()=>setSelected(v=>v.includes(i)?v.filter(n=>n!==i):[...v,i])}/> {x.title} · {x.days.map(d=>WEEKDAYS[d]).join(', ')} · {x.startTime}–{x.endTime}<small style={{display:'block'}}>{x.owner} · {x.sourceTitle} · Proposed, not saved</small></label>)}{!result.proposals.length&&<p>No new conflict-free routine blocks are ready. Existing routines remain in the weekly view.</p>}{selected.length>0&&<button disabled={busy||!canEdit} onClick={review}>Review {selected.length} selected blocks</button>}<h3>Questions to settle</h3>{result.questions.map(x=><p key={x}>{x}</p>)}<button onClick={()=>requestAssistantConversation(`Help finalize ${member}'s weekly routine. Read their saved chores, recurring calendar commitments and Schedule A–D reference. Resolve these gaps one question at a time, preserving source IDs and avoiding duplicate chores or appointments: ${result.questions.join(' ')}. Prepare routine changes for Action Mode review, never mark scheduled work complete.`)}>Resolve with Brevity</button></>}</section>
}
