import test from 'node:test'
import assert from 'node:assert/strict'
import {buildRoutineReview,connectRoutineChores} from './routinePlanning.js'
import {buildDailyAgenda} from './dailyAgenda.js'
const base={date:'2026-10-09',member:'Nyla'}
test('routine proposal uses flex windows and respects Apple calendar ownership',()=>{const review=buildRoutineReview({...base,calendar:[{id:'work',source:'icloud',appleCalendarId:'nyla',appleCalendarOwner:'Nyla',owner:'Family',date:base.date,startTime:'14:00',endTime:'16:00',title:'Work'}]});assert.ok(review.week[0].items.some(x=>x.title==='Work'));assert.ok(!review.proposals.some(x=>x.days.includes(5)));assert.ok(review.proposals.every(x=>x.startTime>='12:00'));assert.ok(review.questions.some(x=>x.includes('no verified')));const other=buildRoutineReview({...base,calendar:[{id:'work',source:'icloud',appleCalendarId:'terica',appleCalendarOwner:'Terica',owner:'Family',date:base.date,startTime:'14:00',endTime:'16:00',title:'Other work'}]});assert.ok(!other.week[0].items.some(x=>x.title==='Other work'));assert.ok(other.proposals.some(x=>x.days.includes(5)))})
test('unverified calendars and unknown after-work times do not produce invented routine times',()=>{assert.equal(buildRoutineReview({...base,calendarAvailable:false}).proposals.length,0);const review=buildRoutineReview({...base,member:'Javin'});assert.ok(review.questions.some(x=>x.includes('After work')));assert.ok(!review.proposals.some(x=>x.notes.includes('After work')));assert.ok(!review.proposals.some(x=>x.days.includes(6)))})
test('linked routines inherit actual chore completion and coverage, never complete from the clock',()=>{const routine={id:'routine',owner:'Nyla',participants:['Javin'],notes:'[chore:task] Source',days:[5],startTime:'14:00',endTime:'14:30',enabled:true,title:'Clean'};const chore={id:'task',occurrenceId:'2026-10-09:task',owners:['Nyla'],status:'completed',occurrence:{coveredBy:'Larry'}};const linked=connectRoutineChores([routine],[chore])[0];assert.equal(linked.status,'completed');assert.equal(linked.owner,'Larry');assert.deepEqual(linked.participants,[]);assert.equal(connectRoutineChores([routine],[{...chore,status:'pending'}])[0].status,'pending');assert.equal(connectRoutineChores([routine],[])[0].cancelled,true);const agenda=buildDailyAgenda({plan:{date:base.date},schedule:{routines:[routine]},chores:[chore],member:'Larry',minute:1000});assert.equal(agenda.completed.length,1);assert.equal(agenda.pending.length,0)})
test('existing reviewed chore links are not proposed twice and invalid members are rejected',()=>{const first=buildRoutineReview(base);assert.ok(first.proposals.length>0);const p=first.proposals[0];const next=buildRoutineReview({...base,schedule:{routines:[{...p,id:'saved'}]}});assert.ok(!next.proposals.some(x=>x.sourceId===p.sourceId));assert.throws(()=>buildRoutineReview({...base,member:'Unknown'}),/household member/)})
