export const SHARED_STATE_EVENT = 'brevity-shared-state-updated'
export const SHARED_STATE_KEYS = [
  'lslj_finance_v9', 'lslj_budget_v1', 'lslj_actuals_v1', 'lslj_bal_overrides_v1',
  'lslj_tx_overrides_v1', 'lslj_tx_rules_v1', 'brevity_finance_categories_v1', 'brevity_finance_scenarios_v1',
  'fp_goals', 'homehq_items_v1', 'family_calendar_events_v1', 'brevity_daily_financial_alignment_v1', 'brevity_finance_timeframe_v1',
  'brevity_finance_meetings_v1', 'brevity_household_maintenance_v1', 'brevity_household_inventory_v1', 'brevity_household_finance_bridge_v1',
]
const ENDPOINT='/.netlify/functions/household-state',META_KEY='brevity_shared_state_meta_v1',REQUEST_TIMEOUT_MS=20000
export function hashValue(value=''){let hash=2166136261;for(let index=0;index<value.length;index+=1){hash^=value.charCodeAt(index);hash=Math.imul(hash,16777619)}return(hash>>>0).toString(16)}
function readMeta(storage){try{return JSON.parse(storage.getItem(META_KEY)||'{}')}catch{return{}}}function writeMeta(storage,meta){storage.setItem(META_KEY,JSON.stringify(meta))}
async function request(method,body){const controller=new AbortController(),timeout=setTimeout(()=>controller.abort(),REQUEST_TIMEOUT_MS);try{const response=await fetch(ENDPOINT,{method,credentials:'include',headers:{'content-type':'application/json'},body:body?JSON.stringify(body):undefined,signal:controller.signal}),payload=await response.json().catch(()=>({}));if(!response.ok){const error=new Error(payload.error||`Household synchronization failed (${response.status}).`);error.status=response.status;throw error}return payload}catch(error){if(error?.name==='AbortError')throw new Error('Household synchronization timed out. Local changes remain on this device.');throw error}finally{clearTimeout(timeout)}}
export function reconcileSharedRecords(storage,remoteRecords={},now=new Date().toISOString()){const meta=readMeta(storage),uploads=[],applied=[];SHARED_STATE_KEYS.forEach(key=>{const localValue=storage.getItem(key),localHash=localValue==null?'':hashValue(localValue),prior=meta[key],remote=remoteRecords[key],localChanged=Boolean(prior&&prior.hash!==localHash);if(remote&&(!prior||(!localChanged&&remote.updatedAt>(prior.updatedAt||'')))){if(localValue!=null&&localValue!==remote.value){try{storage.setItem(`${key}_local_backup_before_cloud`,localValue)}catch{}}storage.setItem(key,remote.value);meta[key]={hash:remote.hash||hashValue(remote.value),updatedAt:remote.updatedAt};if(localValue!==remote.value)applied.push(key);return}if(localValue==null)return;const updatedAt=localChanged||!prior?now:prior.updatedAt;meta[key]={hash:localHash,updatedAt};if(!remote||remote.hash!==localHash||remote.updatedAt<updatedAt)uploads.push({key,value:localValue,hash:localHash,updatedAt})});writeMeta(storage,meta);return{uploads,applied,meta}}
export async function syncSharedState(storage=window.localStorage){const remote=await request('GET'),result=reconcileSharedRecords(storage,remote.records||{}),responses=await Promise.allSettled(result.uploads.map(record=>request('PUT',record))),rejected=responses.filter(item=>item.status==='rejected');if(result.applied.length&&typeof window!=='undefined')window.dispatchEvent(new CustomEvent(SHARED_STATE_EVENT,{detail:{keys:result.applied}}));return{...result,rejected}}
export function startSharedStateSync({storage=window.localStorage,intervalMs=10000,onRemoteChange,onError}={}){let stopped=false,running=false;const run=async()=>{if(running||stopped)return;running=true;try{const result=await syncSharedState(storage);if(result.applied.length)onRemoteChange?.(result.applied);if(result.rejected.length)onError?.(result.rejected[0].reason)}catch(error){onError?.(error)}finally{running=false}};const timer=setInterval(run,intervalMs),visibility=()=>{if(document.visibilityState==='hidden')run()};document.addEventListener('visibilitychange',visibility);return()=>{stopped=true;clearInterval(timer);document.removeEventListener('visibilitychange',visibility)}}
