import {todayDirection} from './priorityDirection.js'
import {openCourseDecisions} from './chartCourseBriefing.js'
import {useState} from 'react'
import {useDailyAgenda} from './useDailyAgenda.js'
import {requestAssistantConversation} from '../assistant/actionEvents.js'
import './TodayOverview.css'
export default function TodayOverview({plan,currentMember,householdChores,calendarAppointments,calendarHealth,onStartRecap,onChartCourse,courseRunning=false,onOpenCalendar,onViewSchedule,onEditFocus,readOnly}){
 const [scope,setScope]=useState('mine'),agenda=useDailyAgenda({plan,member:currentMember,scope,chores:householdChores,appointments:calendarAppointments})
 const decisions=openCourseDecisions(plan)
 const primary=todayDirection(plan,agenda.priorities)
 const supporting=agenda.pending.filter(x=>plan.topPriorities?.length||!['assignment','timeline'].includes(x.sourceKind))
 const evening=agenda.clock.minute>=960,focus=plan.household?.keyFocus,ask=requestAssistantConversation
 return <section className="today-overview"><header><div><span>{new Date(`${plan.date}T12:00:00`).toLocaleDateString('en-US',{weekday:'long',month:'long',day:'numeric'})}</span><h1>Good {agenda.clock.minute<720?'morning':evening?'evening':'afternoon'}, {currentMember}.</h1></div><div className="today-overview-scope"><button aria-pressed={scope==='mine'} onClick={()=>setScope('mine')}>My day</button><button aria-pressed={scope==='household'} onClick={()=>setScope('household')}>Household</button></div></header>
 <section className="today-next-step"><span>{evening?'Evening Recap':'Today’s direction'}</span><h2>{evening?'Recognize today. Set tomorrow’s course.':primary?.title||'Chart the Course'}</h2><p>{evening?'Your recorded accomplishments and tomorrow’s commitments are ready to discuss.':primary?.explicitFocus?'Your agreed household focus.':primary?`${primary.startTime||primary.time||'Time to agree'} · ${primary.owner||primary.owners?.join(', ')||'Owner to confirm'}`:'Review your established routine and any changes for today.'}</p><button disabled={courseRunning} onClick={evening?onStartRecap:onChartCourse}><i className={`ti ${evening?'ti-microphone':'ti-sparkles'}`}/> {courseRunning?'Chart the Course is running':evening?'Start Evening Recap · 10 min':'Start Chart the Course'}</button></section>
 <section aria-label="Agreed priorities"><header><h2>Our agreed priorities</h2>{!readOnly&&<button onClick={onEditFocus}>{focus?'Edit focus':'Set today’s focus'}</button>}</header><ul>{agenda.priorities.slice(0,5).map(x=><li key={`${x.sourceKind}:${x.id}`}><time>{x.startTime||x.time||'Time to agree'}</time><div><strong>{x.title}</strong><small>{x.owner||x.owners?.join(', ')||'Owner to agree'}</small></div></li>)}</ul>{!agenda.priorities.length&&<p>No open priorities are recorded in today’s plan. Agree on them during Chart the Course.</p>}{agenda.priorities.length>5&&<details><summary>More agreed priorities · {agenda.priorities.length-5}</summary>{agenda.priorities.slice(5).map(x=><p key={`${x.sourceKind}:${x.id}`}>{x.startTime||x.time||'Time to agree'} · {x.title} · {x.owner||'Owner to agree'}</p>)}</details>}</section>
 {decisions.length>0&&<section aria-label="Decisions to settle"><h2>Decisions to settle</h2><ul>{decisions.slice(0,3).map((x,i)=><li key={x.id||i}><div><strong>{x.title}</strong><small>{x.owner||'Owner to agree'}</small></div></li>)}</ul>{decisions.length>3&&<details><summary>More decisions · {decisions.length-3}</summary>{decisions.slice(3).map((x,i)=><p key={x.id||i}>{x.title} · {x.owner||'Owner to agree'}</p>)}</details>}</section>}
 <div className="today-overview-columns"><section><header><h2>{scope==='household'?'Shared household commitments':'Your commitments & family events'}</h2><button onClick={onViewSchedule}>Next 7 days</button></header><ul>{supporting.slice(0,5).map(x=><li key={`${x.sourceKind}:${x.id}`}><time>{x.startTime||x.timing||'Time to agree'}</time><div><strong>{x.title}</strong><small>{x.owner||x.owners?.join(', ')||'Owner to agree'} · {x.block}</small></div></li>)}</ul>{!supporting.length&&<p>No open commitments were found in the loaded records.</p>}{calendarHealth?.state!=='ready'&&<button onClick={onOpenCalendar}>Calendar needs verification</button>}{agenda.completed.length>0&&<details><summary>Completed today · {agenda.completed.length}</summary>{agenda.completed.map(x=><p key={`${x.sourceKind}:${x.id}`}>{x.title}</p>)}</details>}</section>
 {agenda.gaps.length>0&&<section className="today-question"><span>Brevity noticed</span><h2>Let’s settle one thing.</h2><p>{agenda.gaps[0].title}: {agenda.gaps[0].owner&&agenda.gaps[0].owner!=='Family'?'what time will this happen?':'who owns this, and when will it happen?'}</p><button onClick={()=>ask(`Help resolve missing ownership or timing for ${agenda.gaps[0].title} on ${plan.date}. Read the exact saved source (${agenda.gaps[0].sourceKind}, ID ${agenda.gaps[0].id}) first. Ask one question at a time and propose a time within our daily rhythm without guessing availability.`)}>Talk with Brevity</button></section>}</div>
 {!evening&&<button className="today-recap-link" onClick={onStartRecap}>Evening Recap</button>}
 <details><summary>Daily schedule & changes</summary><p>Saved recurring routines and dated responsibilities appear automatically. Calendar appointments retain their own records.</p><p>{agenda.routines.length} saved routines apply today. Schedule A–D adjustments need a recorded wake time or an agreed variant; Brevity asks when that information is missing.</p><button onClick={()=>ask(`Review the established Schedules A–D for ${plan.date}. Read the saved schedule first, identify the applicable variant and only ask about missing information. Do not invent timing for unavailable variants.`)}>Review my schedule with Brevity</button></details></section>
}
